### ISSUE TITLE
Cannot read properties of undefined (reading 'Consumer')

### ISSUE THREAD

**Issue by gabrielmoncea** [react-navigation/react-navigation#10040]
### Current behavior

Test fails with following error:

```bash
TypeError: Cannot read properties of undefined (reading 'Consumer')

      at StackView.render (node_modules/@react-navigation/stack/lib/commonjs/views/Stack/StackView.tsx:431:11)
      at finishClassComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8459:31)
      at updateClassComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8409:24)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9990:16)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13800:12)
      at workLoopSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13728:5)
      at renderRootSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13691:7)
      at performSyncWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13404:18)
      at node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2537:26
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:468:12)

  console.error
    The above error occurred in the <StackView> component:
    
        at StackView (/Users/gabrielmoncha/Documents/selfapy-mobile/node_modules/@react-navigation/stack/lib/commonjs/views/Stack/StackView.tsx:63:70)
        at StackNavigator (/Users/gabrielmoncha/Documents/selfapy-mobile/node_modules/@react-navigation/stack/lib/commonjs/navigators/createStackNavigator.tsx:33:25)
        at EnsureSingleNavigator (/Users/gabrielmoncha/Documents/selfapy-mobile/node_modules/@react-navigation/core/lib/commonjs/EnsureSingleNavigator.tsx:21:49)
        at BaseNavigationContainer (/Users/gabrielmoncha/Documents/selfapy-mobile/node_modules/@react-navigation/core/lib/commonjs/BaseNavigationContainer.tsx:81:5)
        at ThemeProvider (/Users/gabrielmoncha/Documents/selfapy-mobile/node_modules/@react-navigation/native/lib/commonjs/theming/ThemeProvider.tsx:11:39)
        at NavigationContainerInner (/Users/gabrielmoncha/Documents/selfapy-mobile/node_modules/@react-navigation/native/lib/commonjs/NavigationContainer.tsx:55:5)
        at MockedNavigator (/Users/gabrielmoncha/Documents/selfapy-mobile/src/testUtils/MockedNavigator.tsx:27:3)
    
    Consider adding an error boundary to your tree to customize error handling behavior.
    Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.

      at logCapturedError (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10989:23)
      at update.callback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11022:5)
      at callCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3662:12)
      at commitUpdateQueue (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3683:9)
      at commitLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11855:11)
      at commitLayoutEffects (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14443:7)
      at Object.invokeGuardedCallbackProd (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11308:10)
```

`MockNavigator.test.tsx`
```typescript
import React from 'react';

import { render, cleanup } from '@testing-library/react-native';

import MockedNavigator from 'testUtils/MockedNavigator';

afterEach(cleanup);
describe('<MockedNavigator />', () => {
  it('should render correctly', () => {
    const { toJSON } = render(<MockedNavigator />);
    expect(toJSON()).toMatchSnapshot();
  });
});

```

`MockNavigator.tsx`
```typescript
import React, { ComponentType } from 'react';
import { View } from 'react-native';

import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator, StackNavigationOptions } from '@react-navigation/stack';

const Stack = createStackNavigator();

type Props = {
  componentName?: string;
  component?: ComponentType<any>;
  secondComponentName?: string;
  secondComponent?: ComponentType<any>;
  params?: object;
  secondParams?: object;
};

const screenOptions: StackNavigationOptions = {
  headerShown: false,
  animationEnabled: false,
};

const MockedNavigator = ({
  componentName = 'MockedComponent',
  component = () => <View />,
  secondComponentName = 'MockedSecondComponent',
  secondComponent = () => <View />,
  params = {},
  secondParams = {},
}: Props) => {
  return (
    <NavigationContainer>
      <Stack.Navigator screenOptions={screenOptions}>
        <Stack.Screen name={componentName} component={component} initialParams={params} />
        <Stack.Screen name={secondComponentName} component={secondComponent} initialParams={secondParams} />
      </Stack.Navigator>
    </NavigationContainer>
  );
};

export default MockedNavigator;

```

### Expected behavior

The test was suppose to render the component and generate / match the snapshot without throwing this error.

### Reproduction

https://github.com/gabrielmoncea/react-native-template/tree/main/template/src/testUtils.

For project installation, you need to first change to template directory
```
cd template
yarn && npx pod-install
```

Test run
`yarn test MockNavigator.test.tsx`

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.0.6
| @react-navigation/stack                | ^6.0.11
| react-native-safe-area-context         | ^3.2.0
| react-native-screens                   | ^3.7.0
| react-native-gesture-handler           | ^1.10.3
| react-native-reanimated                | 2.2.0
| react-native                           | 0.64.2
| node                                   | 16.9.1
| npm or yarn                            | 1.22.11

**Comment by mrbrentkelly** [comment]
Just ran into this issue after upgrading my app from react-navigation 5 to 6. Some snapshot tests are erroring out with...

```bash
TypeError: Cannot read property 'Consumer' of undefined

      at StackView.render (node_modules/@react-navigation/stack/lib/commonjs/views/Stack/StackView.tsx:431:11)
      at finishClassComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8459:31)
      at updateClassComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8409:24)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9990:16)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13800:12)
      at workLoopSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13728:5)
      at renderRootSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13691:7)
      at performSyncWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13404:18)
      at node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2537:26
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:468:12)
```

I'm using the following libs...

```
    "@react-navigation/bottom-tabs": "6.0.9",
    "@react-navigation/native": "6.0.6",
    "@react-navigation/stack": "6.0.11",
```

**Comment by mrbrentkelly** [comment]
> Just ran into this issue after upgrading my app from react-navigation 5 to 6. Some snapshot tests are erroring out with...
> 
> ```shell
> TypeError: Cannot read property 'Consumer' of undefined
> 
>       at StackView.render (node_modules/@react-navigation/stack/lib/commonjs/views/Stack/StackView.tsx:431:11)
>       at finishClassComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8459:31)
>       at updateClassComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8409:24)
>       at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9990:16)
>       at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13800:12)
>       at workLoopSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13728:5)
>       at renderRootSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13691:7)
>       at performSyncWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13404:18)
>       at node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2537:26
>       at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:468:12)
> ```
> 
> I'm using the following libs...
> 
> ```
>     "@react-navigation/bottom-tabs": "6.0.9",
>     "@react-navigation/native": "6.0.6",
>     "@react-navigation/stack": "6.0.11",
> ```

^^ I was able to **fix** the issue by installing the latest version of `react-native-safe-area-context` (3.3.2) and using their [Jest mock](https://github.com/th3rdwave/react-native-safe-area-context#testing) in my `JestSetup` file 👍 . After doing that my tests all passed again 🎉

**Comment by gabrielmoncea** [comment]
@mrbrentkelly I will give it a try and let you know

**Comment by johnhaup** [comment]
> > Just ran into this issue after upgrading my app from react-navigation 5 to 6. Some snapshot tests are erroring out with...
> > ```shell
> > TypeError: Cannot read property 'Consumer' of undefined
> > 
> >       at StackView.render (node_modules/@react-navigation/stack/lib/commonjs/views/Stack/StackView.tsx:431:11)
> >       at finishClassComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8459:31)
> >       at updateClassComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8409:24)
> >       at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9990:16)
> >       at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13800:12)
> >       at workLoopSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13728:5)
> >       at renderRootSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13691:7)
> >       at performSyncWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13404:18)
> >       at node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2537:26
> >       at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:468:12)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'm using the following libs...
> > ```
> >     "@react-navigation/bottom-tabs": "6.0.9",
> >     "@react-navigation/native": "6.0.6",
> >     "@react-navigation/stack": "6.0.11",
> > ```
> 
> ^^ I was able to **fix** the issue by installing the latest version of `react-native-safe-area-context` (3.3.2) and using their [Jest mock](https://github.com/th3rdwave/react-native-safe-area-context#testing) in my `JestSetup` file 👍 . After doing that my tests all passed again 🎉

Thanks, this fixed it for me!
