### ISSUE TITLE
[Android Expo EAS Dev Client]: requireNativeComponent: "RNCViewPager" was not found in the UIManager.

### ISSUE THREAD

**Issue by SrBrahma** [react-navigation/react-navigation#10124]
### Current behavior

After installing the material-top-tabs and its requirements in an Android Expo EAS Dev Client env, the error below is being raised when rendering any Material Top Tab component.

Maybe it's missing some link step.

I will EAS build asap, as it may fix this issue, but as this package is intended to work for normal managed Expo, it shouldn't be required at all. When I do it I will leave a feedback about it.

**Edit: I had EAS-built the project and it's now working. Still strange as this lib should work without EAS.**

<details>

```
Invariant Violation: requireNativeComponent: "RNCViewPager" was not found in the UIManager.

This error is located at:
    in RNCViewPager (created by PagerView)
    in PagerView (created by AnimatedComponent)
    in AnimatedComponent
    in AnimatedComponentWrapper (created by PagerViewAdapter)
    in PagerViewAdapter (created by TabView)
    in RCTView (created by View)
    in View (created by TabView)
    in TabView (created by MaterialTopTabView)
    in MaterialTopTabView (created by MaterialTopTabNavigator)
    in Unknown (created by MaterialTopTabNavigator)
    in MaterialTopTabNavigator (created by Management_Navigator)
    in Management_Navigator (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by CardContainer)
    in RCTView (created by View)
    in View (created by CardContainer)
    in RCTView (created by View)
    in View (created by CardContainer)
    in RCTView (created by View)
    in View
    in CardSheet (created by Card)
    in RCTView (created by View)
    in View (created by AnimatedComponent)
    in AnimatedComponent
    in AnimatedComponentWrapper (created by PanGestureHandler)
    in PanGestureHandler (created by PanGestureHandler)
    in PanGestureHandler (created by Card)
    in RCTView (created by View)
    in View (created by AnimatedComponent)
    in AnimatedComponent
    in AnimatedComponentWrapper (created by Card)
    in RCTView (created by View)
    in View (created by Card)
    in Card (created by CardContainer)
    in CardContainer (created by CardStack)
    in RCTView (created by View)
    in View (created by AnimatedComponent)
    in AnimatedComponent
    in AnimatedComponentWrapper (created by Screen)
    in Screen (created by MaybeScreen)
    in MaybeScreen (created by CardStack)
    in RCTView (created by View)
    in View (created by ScreenContainer)
    in ScreenContainer (created by MaybeScreenContainer)
    in MaybeScreenContainer (created by CardStack)
    in RCTView (created by View)
    in View (created by Background)
    in Background (created by CardStack)
    in CardStack (created by HeaderShownContext)
    in RCTView (created by View)
    in View (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by StackView)
    in GestureHandlerRootView
    in GestureHandlerRootView (created by StackView)
    in StackView (created by StackNavigator)
    in Unknown (created by StackNavigator)
    in StackNavigator (created by Root_Navigator)
    in CartProvider (created by Root_Navigator)
    in StoreProvider (created by Root_Navigator)
    in StoreProvider (created by Root_Navigator)
    in Root_Navigator (created by App)
    in RNCSafeAreaView (created by Wrappers)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by Wrappers)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by Wrappers)
    in Wrappers (created by App)
    in App (created by ExpoRoot)
    in ExpoRoot
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
at http://192.168.0.18:8081/__generated__/AppEntry.bundle?platform=android&dev=true&minify=false&app=com.tekhni.ahive&modulesOnly=false&runModule=true:81272:26 in registerError
at http://192.168.0.18:8081/__generated__/AppEntry.bundle?platform=android&dev=true&minify=false&app=com.tekhni.ahive&modulesOnly=false&runModule=true:81179:29 in errorImpl
at http://192.168.0.18:8081/__generated__/AppEntry.bundle?platform=android&dev=true&minify=false&app=com.tekhni.ahive&modulesOnly=false&runModule=true:81156:21 in error
at node_modules/@firebase/auth/dist/auth.esm.js:39:486 in <anonymous>
at node_modules/react-native/Libraries/Core/Devtools/parseHermesStack.js:105:17 in parseHermesStack
at http://192.168.0.18:8081/__generated__/AppEntry.bundle?platform=android&dev=true&minify=false&app=com.tekhni.ahive&modulesOnly=false&runModule=true:25810:21 in handleException
at node_modules/react-native/Libraries/Core/NativeExceptionsManager.js:98:5 in ExceptionsManager.reportException
at node_modules/@firebase/auth/dist/auth.esm.js:221:493 in ei
at node_modules/@firebase/auth/dist/auth.esm.js:222:67 in ii
at node_modules/@firebase/auth/dist/auth.esm.js:217:65 in <anonymous>
at http://192.168.0.18:8081/__generated__/AppEntry.bundle?platform=android&dev=true&minify=false&app=com.tekhni.ahive&modulesOnly=false&runModule=true:27213:31 in invoke
at node_modules/@firebase/auth/dist/auth.esm.js:215:54 in k.abort
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
at http://192.168.0.18:8081/__generated__/AppEntry.bundle?platform=android&dev=true&minify=false&app=com.tekhni.ahive&modulesOnly=false&runModule=true:3848:39 in __guard
at http://192.168.0.18:8081/__generated__/AppEntry.bundle?platform=android&dev=true&minify=false&app=com.tekhni.ahive&modulesOnly=false&runModule=true:3619:20 in callFunctionReturnFlushedQueue

Invariant Violation: requireNativeComponent: "RNCViewPager" was not found in the UIManager.

This error is located at:
    in RNCViewPager (created by PagerView)
    in PagerView (created by AnimatedComponent)
    in AnimatedComponent
    in AnimatedComponentWrapper (created by PagerViewAdapter)
    in PagerViewAdapter (created by TabView)
    in RCTView (created by View)
    in View (created by TabView)
    in TabView (created by MaterialTopTabView)
    in MaterialTopTabView (created by MaterialTopTabNavigator)
    in Unknown (created by MaterialTopTabNavigator)
    in MaterialTopTabNavigator (created by Management_Navigator)
    in Management_Navigator (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by CardContainer)
    in RCTView (created by View)
    in View (created by CardContainer)
    in RCTView (created by View)
    in View (created by CardContainer)
    in RCTView (created by View)
    in View
    in CardSheet (created by Card)
    in RCTView (created by View)
    in View (created by AnimatedComponent)
    in AnimatedComponent
    in AnimatedComponentWrapper (created by PanGestureHandler)
    in PanGestureHandler (created by PanGestureHandler)
    in PanGestureHandler (created by Card)
    in RCTView (created by View)
    in View (created by AnimatedComponent)
    in AnimatedComponent
    in AnimatedComponentWrapper (created by Card)
    in RCTView (created by View)
    in View (created by Card)
    in Card (created by CardContainer)
    in CardContainer (created by CardStack)
    in RCTView (created by View)
    in View (created by AnimatedComponent)
    in AnimatedComponent
    in AnimatedComponentWrapper (created by Screen)
    in Screen (created by MaybeScreen)
    in MaybeScreen (created by CardStack)
    in RCTView (created by View)
    in View (created by ScreenContainer)
    in ScreenContainer (created by MaybeScreenContainer)
    in MaybeScreenContainer (created by CardStack)
    in RCTView (created by View)
    in View (created by Background)
    in Background (created by CardStack)
    in CardStack (created by HeaderShownContext)
    in RCTView (created by View)
    in View (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by StackView)
    in GestureHandlerRootView
    in GestureHandlerRootView (created by StackView)
    in StackView (created by StackNavigator)
    in Unknown (created by StackNavigator)
    in StackNavigator (created by Root_Navigator)
    in CartProvider (created by Root_Navigator)
    in StoreProvider (created by Root_Navigator)
    in StoreProvider (created by Root_Navigator)
    in Root_Navigator (created by App)
    in RNCSafeAreaView (created by Wrappers)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by Wrappers)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by Wrappers)
    in Wrappers (created by App)
    in App (created by ExpoRoot)
    in ExpoRoot
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
at http://192.168.0.18:8081/__generated__/AppEntry.bundle?platform=android&dev=true&minify=false&app=com.tekhni.ahive&modulesOnly=false&runModule=true:81272:26 in registerError
at http://192.168.0.18:8081/__generated__/AppEntry.bundle?platform=android&dev=true&minify=false&app=com.tekhni.ahive&modulesOnly=false&runModule=true:81179:29 in errorImpl
at http://192.168.0.18:8081/__generated__/AppEntry.bundle?platform=android&dev=true&minify=false&app=com.tekhni.ahive&modulesOnly=false&runModule=true:81156:21 in error
at node_modules/@firebase/auth/dist/auth.esm.js:39:486 in <anonymous>
at node_modules/react-native/Libraries/Core/Devtools/parseHermesStack.js:105:17 in parseHermesStack
at http://192.168.0.18:8081/__generated__/AppEntry.bundle?platform=android&dev=true&minify=false&app=com.tekhni.ahive&modulesOnly=false&runModule=true:25810:21 in handleException
at http://192.168.0.18:8081/__generated__/AppEntry.bundle?platform=android&dev=true&minify=false&app=com.tekhni.ahive&modulesOnly=false&runModule=true:23235:28 in commitLayoutEffects
at http://192.168.0.18:8081/__generated__/AppEntry.bundle?platform=android&dev=true&minify=false&app=com.tekhni.ahive&modulesOnly=false&runModule=true:13695:39 in <unknown>
at node_modules/react-native/Libraries/Renderer/shims/ReactNativeViewConfigRegistry.js:32:0 in <global>
at node_modules/react-native/Libraries/EventEmitter/RCTEventEmitter.js:21:17 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:655:10 in setTimeout$argument_0
at node_modules/react-native/Libraries/Core/setUpXHR.js:31:0 in <global>
at node_modules/react-native/Libraries/Network/XMLHttpRequest.js:252:10 in get__response
at node_modules/react-native/Libraries/Utilities/stringifySafe.js:58:7 in replacer
at http://192.168.0.18:8081/__generated__/AppEntry.bundle?platform=android&dev=true&minify=false&app=com.tekhni.ahive&modulesOnly=false&runModule=true:3846:14 in __guard
at http://192.168.0.18:8081/__generated__/AppEntry.bundle?platform=android&dev=true&minify=false&app=com.tekhni.ahive&modulesOnly=false&runModule=true:3619:20 in callFunctionReturnFlushedQueue
```

</details>

### Expected behavior

Package should work when it's installed and shouldn't require an EAS build when on EAS.

### Reproduction

I had it working on Snack emulator. Must be an EAS related issue.

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [X] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | "6.0.6"
| @react-navigation/bottom-tabs          | "6.0.9"
| @react-navigation/material-top-tabs    | "^6.0.6"
| @react-navigation/stack                | "6.0.11"
| react-native-safe-area-context         | "3.3.2"
| react-native-screens                   | "~3.8.0"
| react-native-gesture-handler           | "~1.10.3"
| react-native-reanimated                | "~2.2.4"
| react-native-tab-view                  | "^3.1.1"
| react-native-pager-view                | "5.4.6"
| react-native                           | "0.64.3"
| expo                                   | "^43.0.2"
| node                                   | v14.18.0
| npm or yarn                            | yarn 3.1.0

**Comment by morwalz** [comment]
any update here '?

**Comment by SrBrahma** [comment]
> any update here '?

Build the EAS dev client and it will work

**Comment by morwalz** [comment]
it is working with expo go. 
but after making build  eas build --platform android --profile preview
app crashes with this error.  "requireNativeComponent: "RNCViewPager" was not found in the UIManager."
Not sure what do you mean by "Build the EAS dev client and it will work

"

**Comment by marco2216** [comment]
Also having this problem

**Comment by javidafandiyev** [comment]
@morwalz having the same problem, any updates?

**Comment by maoapp** [comment]
The same issue here :(

**Comment by devbiansor** [comment]
same issue
