### ISSUE TITLE
Can't make test snapshots with @react-navigation/material-top-tabs

### ISSUE THREAD

**Issue by emmarq** [react-navigation/react-navigation#10256]
### Current behavior

Running the following test case

```js
const ScreenA = ScreenFactory('Go to Screen B');
const ScreenB = ScreenFactory('Go to Screen A');

const { Navigator, Screen } = createMaterialTopTabNavigator();

const App = () => {
  return (
    <NavigationContainer>
      <Navigator>
        <Screen component={ScreenA} name="ScreenA" />
        <Screen component={ScreenB} name="ScreenB" />
      </Navigator>
    </NavigationContainer>
  );
};

describe('Navigation Container', () => {
  it('makes assertion with a top tab bar navigator', () => {
    const { toJSON } = render(<App />);

    expect(toJSON()).toMatchSnapshot();
  });
});
```

Trying to take a snapshot of a component tree with material top tab bar in it, it fails with

```
    Couldn't find a navigation context. Have you wrapped your app with 'NavigationContainer'? See https://reactnavigation.org/docs/getting-started for setup instructions.

      at Object.get getIsInitial [as getIsInitial] (node_modules/@react-navigation/core/lib/commonjs/NavigationStateContext.tsx:37:11)
      at printObjectProperties (node_modules/pretty-format/build/collections.js:173:32)
      at printComplexValue (node_modules/pretty-format/build/index.js:310:48)
      at printer (node_modules/pretty-format/build/index.js:393:10)
      at printObjectProperties (node_modules/pretty-format/build/collections.js:173:21)
      at printComplexValue (node_modules/pretty-format/build/index.js:310:48)
      at printer (node_modules/pretty-format/build/index.js:393:10)
      at printObjectProperties (node_modules/pretty-format/build/collections.js:173:21)
      at printComplexValue (node_modules/pretty-format/build/index.js:310:48)
      at printer (node_modules/pretty-format/build/index.js:393:10)
```

### Expected behavior

The snapshot can be taken and the test succeed

### Reproduction

https://github.com/emmarq/RnReplica/blob/error-1/__tests__/Navigation.test.js

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [X] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |6.0.6
| @react-navigation/material-top-tabs    |6.0.6
| @react-navigation/native-stack         |6.2.5
| react-native-safe-area-context         |3.3.2
| react-native-screens                   |3.10.1
| react-native-gesture-handler           |2.1.1
| react-native-reanimated                |2.3.1
| react-native-tab-view                  |3.1.1
| react-native-pager-view                |5.4.9
| react-native                           |0.66.4
| node                                   |14.17.1
| npm or yarn                            |1.22.0

**Comment by emmarq** [comment]
https://github.com/emmarq/RnReplica

**Comment by blwinters** [comment]
Same here

**Comment by blwinters** [comment]
This has been open for a year with a repro. Have any maintainers been able to investigate?
