### ISSUE TITLE
jest material-top-tabs "TypeError: Cannot read properties of undefined (reading 'Commands')"

### ISSUE THREAD

**Issue by Stewartarmbrecht** [react-navigation/react-navigation#10412]
### Current behavior

When running a jest test that uses @testing-library/react-native throws the following error when pressing the material top tab:

Component:

```
import * as React from 'react';
import { Ionicons } from '@expo/vector-icons';
import { createMaterialTopTabNavigator } from '@react-navigation/material-top-tabs'

import ActivitySettingsScreen from './ActivitySettingsScreen';
import ActivityEntriesScreen from './ActivityEntriesScreen';
import { View } from '../../components';

const ActivityDetails = createMaterialTopTabNavigator<ActivityDetailsTabParamList>();
export type ActivityDetailsTabParamList = {
  ActivityEntriesScreen: undefined;
  ActivitySettingsScreen: undefined;
};

export default function ActivityDetailsTopTabNavigator() {

  return (
    <ActivityDetails.Navigator
      screenOptions={{
        tabBarActiveTintColor: '#024B90',
        tabBarShowLabel: true,
        tabBarShowIcon: true,
      }}
      tabBarPosition='top'
      >
      <ActivityDetails.Screen
        name='ActivitySettingsScreen'
        component={ActivitySettingsScreen}
        options={{
          tabBarLabel: 'Settings',
          tabBarTestID: 'ActivitySettingsTab',
          //tabBarIcon: ({ color }) => <TabBarIcon name='settings' color={color} testID='ActivitySettingsTab' />,
        }}
      />
      <ActivityDetails.Screen
        name='ActivityEntriesScreen'
        component={ActivityEntriesScreen}
        options={{
          tabBarLabel: 'Entries',
          tabBarTestID: 'ActivityEntriesTab',
          //tabBarIcon: ({ color }) => <TabBarIcon name='list' color={color} testID='ActivityEntriesTab' />,
        }}
      /> 
    </ActivityDetails.Navigator>
  );
}

// You can explore the built-in icon families and icons on the web at:
// https://icons.expo.fyi/
function TabBarIcon(props: { name: React.ComponentProps<typeof Ionicons>['name']; color: string; testID?: string }) {
  const iconProps = {...props, testID: undefined};
  return <View testID={props.testID}><Ionicons size={20} {...iconProps} /></View>;
}

```

Test

```
import React from 'react';
import { fireEvent, within, render } from '@testing-library/react-native';
import Navigation from './features/navigation';

describe('Activity Entries Screen', () => {
  
  describe('With an existing activity', () => {
    // let targetScreen: ReactTestInstance;
    // let app: RenderAPI;
    
    // beforeEach(async () => {
    //   const appAndScreen = await TestUtilities.navigateToExistingActivity(TestUtilities.ToActivityScreen.EntriesScreen, true);
    //   targetScreen = appAndScreen.screen;
    //   app = appAndScreen.app;
    // })

    it('should display the list of entries', async () => {
      let app = render(<Navigation />);
      const activitiesScreen = await app.findByTestId("ActivitiesScreen");
      const activity1 = await within(activitiesScreen).findByText("Activities Screen");
      await fireEvent.press(activity1);
      //await new Promise((r) => setTimeout(r, 4000));
      const button = await app.findByTestId('ActivityEntriesTab')
      await fireEvent.press(button);
      const screen = await app.findByTestId("ActivityEntriesScreen");
      await within(screen).findByText('Activity Entries');
    });

  })
    
});

```

Test Results

```
 FAIL  ./index.test.tsx
  Activity Entries Screen
    With an existing activity
      ✕ should display the list of entries (456 ms)

  ● Activity Entries Screen › With an existing activity › should display the list of entries

    TypeError: Cannot read properties of undefined (reading 'Commands')

      22 |       //await new Promise((r) => setTimeout(r, 4000));
      23 |       const button = await app.findByTestId('ActivityEntriesTab')
    > 24 |       await fireEvent.press(button);
         |                       ^
      25 |       const screen = await app.findByTestId("ActivityEntriesScreen");
      26 |       await within(screen).findByText('Activity Entries');
      27 |     });

      at PagerView.setPage (node_modules/react-native-pager-view/lib/commonjs/PagerView.tsx:96:5)
      at Object.jumpTo (node_modules/react-native-tab-view/lib/commonjs/PagerViewAdapter.tsx:66:23)
      at onPress (node_modules/react-native-tab-view/lib/commonjs/TabBar.tsx:433:30)
      at node_modules/@testing-library/react-native/build/fireEvent.js:86:19
      at batchedUpdates (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13452:12)
      at act (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15280:14)
      at invokeEvent (node_modules/@testing-library/react-native/build/fireEvent.js:85:20)
      at Function.pressHandler [as press] (node_modules/@testing-library/react-native/build/fireEvent.js:93:44)
      at Object.<anonymous> (index.test.tsx:24:23)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        5.429 s, estimated 6 s
Ran all test suites related to changed files.

Watch Usage: Press w to show more.

```
### Expected behavior

fireEvent.press() does not throw an error.

I created a project that recreates the error.  Just run 

```
cd top-tab-error
yarn install
yarn test
```
### Reproduction

https://github.com/Stewartarmbrecht/material-top-tabs-error-repro

### Platform

- [ ] Android
- [ ] iOS
- [ ] Web

### Packages

- [ ] react-navigation-drawer
- [ ] react-navigation-stack
- [ ] react-navigation-tabs

### Environment

| package                                | version |
| -------------------------------------- | ------- |
|    "@react-navigation/bottom-tabs"| "^6.2.0"|
|    "@react-navigation/material-top-tabs"| "^6.1.1"|
|    "@react-navigation/native"| "^6.0.8"|
|    "@react-navigation/native-stack"| "^6.5.0"|
|    "expo"| "~44.0.0"|
|    "expo-status-bar"| "~1.2.0"|
|    "react"| "17.0.1"|
|    "react-dom"| "17.0.1"|
|    "react-native"| "0.64.3"|
|    "react-native-gesture-handler"| "~2.1.0"|
|    "react-native-pager-view"| "5.4.9"|
|    "react-native-reanimated"| "~2.3.1"|
|    "react-native-safe-area-context"| "3.3.2"|
|    "react-native-screens"| "~3.10.1"|
|    "react-native-tab-view"| "^3.1.1"|
|    "react-native-web"| "0.17.1"
|"@babel/core"| "^7.12.9"|
|"@testing-library/jest-native"| "^4.0.4"|
|"@testing-library/react-native"| "^9.0.0"|
|"@types/jest"| "^27.4.1"|
|"@types/react"| "~17.0.21"|
|"@types/react-native"| "~0.64.12"|
|"@types/react-test-renderer"| "^17.0.1"|
|"jest"| "^26.5.6"|
|"jest-expo"| "^44.0.1"|
|"react-test-renderer"| "^17.0.2"|
|"ts-jest"| "^26.5.6"|
|"typescript"| "~4.3.5"

**Comment by Stewartarmbrecht** [comment]
Must be submitting in the wrong place.  I don't have any of the packages that require version numbers.

**Comment by Stewartarmbrecht** [comment]
Going to resubmit with a simpler repro.

**Comment by Aure77** [comment]
Did you found a solution ?

**Comment by Stewartarmbrecht** [comment]
Re-opened issue: #10419
