### ISSUE TITLE
Material Top Tab Navigator usage leads to the App crash on a new react-native architecture 0.69.*

### ISSUE THREAD

**Issue by kirill268** [react-navigation/react-navigation#10782]
### Current behavior

Using code from [material-top-tab-navigator's Snack](https://snack.expo.io/?platform=android&name=Getting%20started%20%7C%20React%20Navigation&dependencies=%40expo%2Fvector-icons%40*%2C%40react-native-community%2Fmasked-view%40*%2Creact-native-gesture-handler%40*%2Creact-native-pager-view%40*%2Creact-native-paper%40%5E4.7.2%2Creact-native-reanimated%40*%2Creact-native-safe-area-context%40*%2Creact-native-screens%40*%2Creact-native-tab-view%40%5E3.0.0%2C%40react-navigation%2Fbottom-tabs%406.3.1%2C%40react-navigation%2Fdrawer%406.4.1%2C%40react-navigation%2Felements%401.3.3%2C%40react-navigation%2Fmaterial-bottom-tabs%406.2.1%2C%40react-navigation%2Fmaterial-top-tabs%406.2.1%2C%40react-navigation%2Fnative-stack%406.6.1%2C%40react-navigation%2Fnative%406.0.10%2C%40react-navigation%2Fstack%406.2.1&hideQueryParams=true&sourceUrl=https%3A%2F%2Freactnavigation.org%2Fexamples%2F6.x%2Fmaterial-top-tab-based-navigation-minimal.js)

When selecting a tab the App crashes

<img src="https://user-images.githubusercontent.com/102238005/186146719-31f37be3-6f4e-411d-aebf-124b27875147.gif" width="350">

### Expected behavior

I expect the app not to crash

### Reproduction

https://github.com/kirill268/newArcBugReporter

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [X] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [ ] @react-navigation/​native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.0.11
| @react-navigation/material-top-tabs    | ^6.2.2
| react-native-safe-area-context         | ^4.3.3
| react-native-screens                   | ^3.16.0 |
| react-native-tab-view                  | ^3.1.1
| react-native-pager-view                | ^5.4.25
| react-native                           | 0.69.4
| node                                   | v16.14.0
| npm                            | 8.3.1

**Comment by raajnadar** [comment]
You need to wait for new arch support in pager view - https://github.com/callstack/react-native-pager-view/issues/584

**Comment by raajnadar** [comment]
@kirill268 could yoy please try the latest version & let me know if that worked?

> Hey, new architecture support was added in 6.1.0

**Comment by sagarj-iprogrammer** [comment]
if upgrage react-native-tab-view from 3.1.1 to latest tabBarIndicatorStyle  not display or dynamic tabs

**Comment by sagarjeu** [comment]
@satya164  any update for this issue

**Comment by sagarj-iprogrammer** [comment]
@satya164  any update ?  or please  provide the all exact version of package for navigation  for RN 0.72

**Comment by okwasniewski** [comment]
Hey @sagarj-iprogrammer 

Can you check with the latest versions of pager-view and tab-view? And if the crash still persists please provide output from Android logcat.

**Comment by sagarj-iprogrammer** [comment]
"@react-navigation/material-top-tabs": "6.3.0",
    "@react-navigation/native": "6.0.13",
    "@react-navigation/native-stack": "6.9.0",
    "@react-navigation/stack": "^6.3.2",
    "react": "18.2.0",
    "react-native": "0.72.2",
    "react-native-gesture-handler": "2.13.1",
    "react-native-pager-view": "^6.2.1",
    "react-native-safe-area-context": "4.7.2",
    "react-native-screens": "^3.25.0",
    "react-native-tab-view": "^3.5.2"
    
    
    Logcat : 2023-10-10 15:38:16.874  4388-4388  libc                    keystore2                            A  crash_dump helper failed to exec, or was killed

**Comment by sagarj-iprogrammer** [comment]
@okwasniewski 
--------- beginning of crash
2023-10-10 15:46:47.864  5162-28923 ActivityManager         system_server                        E  ANR in com.toptab (com.toptab/.MainActivity)
                                                                                                    PID: 28747
                                                                                                    Reason: Input dispatching timed out (720b24a com.toptab/com.toptab.MainActivity (server) is not responding. Waited 10005ms for MotionEvent)
                                                                                                    Parent: com.toptab/.MainActivity
                                                                                                    Frozen: false
                                                                                                    Load: 18.61 / 19.29 / 19.52
                                                                                                    ------ Current CPU Core Info ------
                                                                                                    - offline : 
                                                                                                    - online : 0-7
                                                                                                    - AP Temp = 434
                                                                                                                                 0           1           2           3           4           5           6           7
                                                                                                    ------------------------------------------------------------------------------------------------------------------
                                                                                                    scaling_cur_freq       1053000     1053000     1053000     1053000     1664000     1664000     1664000     1664000
                                                                                                    scaling_governor     schedutil   schedutil   schedutil   schedutil   schedutil   schedutil   schedutil   schedutil
                                                                                                    scaling_max_freq       1742000     1742000     1742000     1742000     2314000     2314000     2314000     2314000
                                                                                                    ------------------------------------------------------------------------------------------------------------------
                                                                                                    CPU usage from 0ms to 11358ms later (2023-10-10 15:46:36.454 to 2023-10-10 15:46:47.812):
                                                                                                      50% 5162/system_server: 17% user + 33% kernel / faults: 3921 minor 13 major
                                                                                                      48% 32210/com.google.android.gm: 32% user + 16% kernel / faults: 3612 minor 4 major
                                                                                                      11% 4739/android.hardware.audio.service: 6% user + 5.7% kernel
                                                                                                      10% 17020/com.google.android.googlequicksearchbox:interactor: 8% user + 2.5% kernel / faults: 1190 minor 21 major
                                                                                                      9.2% 12529/adbd: 3% user + 6.1% kernel / faults: 914 minor
                                                                                                      8.3% 2106/sugov:0: 0% user + 8.3% kernel
                                                                                                      8.3% 4820/audioserver: 5.1% user + 3.2% kernel / faults: 236 minor
                                                                                                      1.1% 4925/media.codec: 0.8% user + 0.3% kernel / faults: 6898 minor
                                                                                                      6.7% 7992/com.samsung.android.honeyboard: 3.3% user + 3.3% kernel / faults: 926 minor 1 major
                                                                                                      5.4% 5501/com.android.systemui: 2.6% user + 2.8% kernel / faults: 1287 minor
                                                                                                      5.3% 28747/com.toptab: 2.6% user + 2.7% kernel / faults: 4936 minor
                                                                                                      0.8% 4949/media.swcodec: 0.3% user + 0.4% kernel / faults: 6096 minor
                                                                                                      5% 4833/surfaceflinger: 1.2% user + 3.7% kernel / faults: 168 minor
                                                                                                      0.7% 4893/media.extractor: 0.2% user + 0.4% kernel / faults: 4176 minor
                                                                                                      3.2% 2107/sugov:4: 0% user + 3.2% kernel
                                                                                                      3.1% 14949/kworker/u16:3: 0% user + 3.1% kernel / faults: 23 minor
                                                                                                      2.9% 5451/com.android.phone: 1.6% user + 1.2% kernel / faults: 410 minor
                                                                                                      2.7% 15670/kworker/u16:4: 0% user + 2.7% kernel / faults: 23 minor
                                                                                                      0.6% 7201/com.sec.android.diagmonagent: 0.3% user + 0.3% kernel / faults: 590 minor 5 major
                                                                                                      2.4% 5776/com.sec.imsservice: 1% user + 1.4% kernel / faults: 686 minor 2 major
                                                                                                      2.4% 28098/kworker/u16:0: 0% user + 2.4% kernel / faults: 16 minor
                                                                                                      0.3% 5752/com.sec.sve: 0.1% user + 0.1% kernel / faults: 739 minor 1 major
                                                                                                      1.8% 7229/com.sec.android.sdhms: 1% user + 0.7% kernel / faults: 413 minor 1 major
                                                                                                      1.2% 4172/logd: 0.4% user + 0.7% kernel / faults: 23 minor
                                                                                                      1.1% 13285/kworker/u16:2: 0% user + 1.1% kernel / faults: 3 minor
                                                                                                      0.9% 3144/ueventd: 0.7% user + 0.2% kernel / faults: 5 minor
                                                                                                      0.2% 25186/kworker/u16:1: 0% user + 0.2% kernel / faults: 3 minor
                                                                                                      0.7% 4761/android.hardware.sensors@2.0-service.multihal: 0.2% user + 0.5% kernel / faults: 1 minor
                                                                                                      0.7% 5486/com.android.networkstack.process: 0.5% user + 0.2% kernel / faults: 261 minor
                                                                                                      0.7% 28870/logcat: 0.3% user + 0.4% kernel
                                                                                                      0.6% 4729/netd: 0% user + 0.5% kernel / faults: 238 minor
                                                                                                      0% 30660/com.android.bluetooth: 0% user + 0% kernel / faults: 203 minor
                                                                                                      0.5% 8/rcu_preempt: 0% user + 0.5% kernel
                                                                                                      0% 4417/tombstoned: 0% user + 0% kernel
                                                                                                      0.4% 9/rcu_sched: 0% user + 0.4% kernel
                                                                                                      0.4% 2205/irq/165-1198000: 0% user + 0.4% kernel
                                                                                                      0.4% 4728/statsd: 0.1% user + 0.2% kernel / faults: 124 minor
                                                                                                      0% 5786/com.android.se: 0% user + 0% kernel / faults: 234 minor
                                                                                                      0.3% 24152/com.google.process.location: 0.2% user + 0% kernel / faults: 69 minor
                                                                                                      0.3% 32589/com.google.android.gms.persistent: 0.2% user + 0% kernel / faults: 18 minor
                                                                                                      0% 1/init: 0% user + 0% kernel
----------------------------------------------------------------------------------------------------------------------------------------------------------------------


Native animation workaround, frame lost as result of race condition
                                                                                                    com.facebook.react.bridge.JSApplicationCausedNativeException: Illegal node ID set as an input for Animated.multiply node
                                                                                                    	at com.facebook.react.animated.MultiplicationAnimatedNode.update(MultiplicationAnimatedNode.java:41)
                                                                                                    	at com.facebook.react.animated.NativeAnimatedNodesManager.updateNodes(NativeAnimatedNodesManager.java:730)
                                                                                                    	at com.facebook.react.animated.NativeAnimatedNodesManager.runUpdates(NativeAnimatedNodesManager.java:631)
                                                                                                    	at com.facebook.react.animated.NativeAnimatedModule$1.doFrameGuarded(NativeAnimatedModule.java:243)
                                                                                                    	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
                                                                                                    	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
                                                                                                    	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1106)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:792)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8751)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by sajorahasan** [comment]
Hi @okwasniewski 

We are using the latest version of pager-view & tab-view but still facing the crash.

````
ANR in com.devdigital.excelindustries.development (com.devdigital.excelindustries.development/.MainActivity)
                                                                                                    PID: 11499
                                                                                                    Reason: Input dispatching timed out (285d1a4 com.devdigital.excelindustries.development/com.devdigital.excelindustries.development.MainActivity (server) is not responding. Waited 5003ms for MotionEvent(deviceId=3, eventTime=4470312723000, source=TOUCHSCREEN | STYLUS, displayId=0, action=DOWN, actionButton=0x00000000, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, classification=NONE, edgeFlags=0x00000000, xPrecision=27.3, yPrecision=17.1, xCursorPosition=nan, yCursorPosition=nan, pointers=[0: (139.0, 553.9)]), policyFlags=0x62000000)
                                                                                                    Parent: com.devdigital.excelindustries.development/.MainActivity
                                                                                                    ErrorId: f966397a-1b33-4e8c-b0da-046d62f69ece
                                                                                                    Frozen: false
                                                                                                    Load: 0.37 / 0.42 / 0.33
                                                                                                    ----- Output from /proc/pressure/memory -----
                                                                                                    some avg10=0.00 avg60=0.00 avg300=0.02 total=15207695
                                                                                                    full avg10=0.00 avg60=0.00 avg300=0.00 total=9123187
                                                                                                    ----- End output from /proc/pressure/memory -----
                                                                                                    ----- Output from /proc/pressure/cpu -----
                                                                                                    some avg10=0.40 avg60=0.58 avg300=0.89 total=106822501
                                                                                                    full avg10=0.00 avg60=0.00 avg300=0.00 total=0
                                                                                                    ----- End output from /proc/pressure/cpu -----
                                                                                                    ----- Output from /proc/pressure/io -----
                                                                                                    some avg10=0.00 avg60=0.00 avg300=0.06 total=23642805
                                                                                                    full avg10=0.00 avg60=0.00 avg300=0.04 total=9974338
                                                                                                    ----- End output from /proc/pressure/io -----
`````

````
CPU usage from 108804ms to -2ms ago (2023-10-12 18:55:47.122 to 2023-10-12 18:57:35.928):
                                                                                                      1.5% 381/android.hardware.graphics.composer3-service.ranchu: 0.1% user + 1.4% kernel
                                                                                                      1.2% 545/system_server: 0.7% user + 0.5% kernel / faults: 13365 minor 29 major
                                                                                                      1% 992/com.google.android.apps.nexuslauncher: 0.4% user + 0.6% kernel / faults: 539 minor 43 major
                                                                                                      0.9% 395/surfaceflinger: 0.4% user + 0.4% kernel / faults: 93 minor 17 major
                                                                                                      0.4% 10852/kworker/0:2-events: 0% user + 0.4% kernel
                                                                                                      0.3% 370/android.hardware.sensors-service.multihal: 0.1% user + 0.1% kernel
                                                                                                      0.2% 758/com.android.systemui: 0.1% user + 0.1% kernel / faults: 5780 minor 1184 major
                                                                                                      0.1% 943/com.android.phone: 0.1% user + 0% kernel / faults: 2535 minor 15 major
                                                                                                      0.1% 151/logd: 0% user + 0.1% kernel / faults: 599 minor 41 major
                                                                                                      0.1% 13/ksoftirqd/0: 0% user + 0.1% kernel
                                                                                                    5.9% TOTAL: 2.8% user + 1.6% kernel + 0% iowait + 1.3% irq + 0% softirq
                                                                                                    CPU usage from 14ms to 281ms later (2023-10-12 18:57:35.940 to 2023-10-12 18:57:36.207):
                                                                                                      61% 11499/com.devdigital.excelindustries.development: 34% user + 26% kernel / faults: 3452 minor
                                                                                                        56% 11504/Signal Catcher: 30% user + 26% kernel
                                                                                                      47% 545/system_server: 23% user + 23% kernel / faults: 2504 minor
                                                                                                        23% 551/Signal Catcher: 15% user + 7.9% kernel
                                                                                                        11% 554/HeapTaskDaemon: 11% user + 0% kernel
                                                                                                        11% 11762/AnrAuxiliaryTas: 3.9% user + 7.9% kernel
                                                                                                      4.3% 10852/kworker/0:2-virtio_vsock: 0% user + 4.3% kernel
                                                                                                    33% TOTAL: 16% user + 15% kernel + 1.8% irq
````

**Comment by sagarjeu** [comment]
Any update
