### ISSUE TITLE
Jest Typescript @react-navigation/native SyntaxError: Cannot use import statement outside a module 

### ISSUE THREAD

**Issue by brunoamorim616** [react-navigation/react-navigation#11055]
### Current behavior

I'm trying to run a simple test for my app but jest is reporting a "SyntaxError: Cannot use import statement outside a module" error

I followed the following guide for using jest for testing: https://reactnavigation.org/docs/testing/
but it still not working:

`
$ /home/.../Documents/projects/javascript/react-native-white-label-builder/whitelabel-app/node_modules/.bin/jest
 FAIL  __tests__/App-test.tsx
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /home/.../Documents/projects/javascript/react-native-white-label-builder/whitelabel-app/node_modules/react-native-paper/lib/module/core/Provider.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import * as React from 'react';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

       5 |   DefaultTheme,
       6 |   NavigationContainer,
    >  7 | } from '@react-navigation/native';
         |                                   ^
       8 | import {Provider} from 'react-native-paper';
       9 | import {useColorScheme} from 'react-native';
      10 | import Routes from './routes';

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1449:14)
      at Object.<anonymous> (src/App.tsx:7:35)
      at Object.<anonymous> (__tests__/App-test.tsx:8:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.378 s
Ran all test suites.
error Command failed with exit code 1.
`

--

here's my package.json

`
{
  "name": "whitelabel",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx"
  },
  "dependencies": {
    "@react-navigation/bottom-tabs": "^6.4.0",
    "@react-navigation/drawer": "^6.5.0",
    "@react-navigation/native": "^6.0.16",
    "@react-navigation/native-stack": "^6.9.1",
    "react": "18.1.0",
    "react-native": "0.70.3",
    "react-native-gesture-handler": "^2.7.1",
    "react-native-paper": "5.0.0-rc.10",
    "react-native-reanimated": "^2.11.0",
    "react-native-safe-area-context": "^4.4.1",
    "react-native-screens": "^3.18.2",
    "react-native-vector-icons": "^9.2.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.5",
    "@babel/preset-env": "^7.20.2",
    "@babel/preset-typescript": "^7.18.6",
    "@babel/runtime": "^7.20.6",
    "@callstack/eslint-config": "^13.0.2",
    "@react-native-community/eslint-config": "^3.2.0",
    "@testing-library/jest-native": "^5.3.0",
    "@testing-library/react-native": "^11.5.0",
    "@tsconfig/react-native": "^2.0.2",
    "@types/jest": "^29.2.3",
    "@types/react": "^18.0.21",
    "@types/react-native": "^0.70.4",
    "@types/react-native-vector-icons": "^6.4.12",
    "@types/react-test-renderer": "^18.0.0",
    "@typescript-eslint/eslint-plugin": "^5.37.0",
    "@typescript-eslint/parser": "^5.37.0",
    "babel-jest": "^29.3.1",
    "eslint": "^8.28.0",
    "jest": "^29.3.1",
    "metro-react-native-babel-preset": "^0.73.3",
    "react-test-renderer": "18.1.0",
    "ts-jest": "^29.0.3",
    "typescript": "^4.9.3"
  },
  "jest": {
    "preset": "react-native",
    "setupFilesAfterEnv": [
      "@testing-library/jest-native/extend-expect",
      "<rootDir>/jest/setup.js"
    ],
    "transform": {
      "^.+\\.[t|j]sx?$": "babel-jest",
      "^.+\\.tsx?$": [
        "ts-jest",
        {
          "tsconfig": "tsconfig.spec.json"
        }
      ]
    },
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ]
  }
}
`

### Expected behavior

Expected to run the tests without any problem.

### Reproduction

https://github.com/brunoamorim616/react-native-white-label-builder

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/​bottom-tabs
- [X] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [X] @react-navigation/​native-stack
- [ ] react-native-tab-view
- [ ] flipper-plugin-react-navigation

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.16|
| @react-navigation/bottom-tabs          | 6.4.3|
| @react-navigation/drawer               |6.5.3 |
| @react-navigation/native-stack         | 6.9.1| 
| react-native-safe-area-context         | 4.4.1|
| react-native-screens                   | 3.18.2|
| react-native-gesture-handler           | 2.7.1 |
| react-native-reanimated                | 2.11.0| 
| react-native                           | 0.70.3|
| node                                   | 16.X|
| npm or yarn                            |  yarn 1.22.19|

**Comment by brunoamorim616** [comment]
Was able to try other solutions and it's not a issue related to the library react-navigation.
I am closing this issue.
Found the solution in this topic on a [react-native-testing-library issue ]( https://github.com/callstack/react-native-testing-library/issues/398#issuecomment-648317437).
