### ISSUE TITLE
"No view found for id" Bottom Tabs navigation error on Android with new architecture enabled

### ISSUE THREAD

**Issue by cnguyen812** [react-navigation/react-navigation#11384]
### Current behavior

With the React Native new architecture enabled on Android, the bottom tab navigation seems to be throwing exceptions when switching tabs. The app seemingly still works. 

However, if there is a nested navigator, it'll throw with `No view found for id ...` after a few switches and you'll need to restart the app. As a workaround, these errors seem to go away if `detachInactiveScreens` is set to `false` on the tab navigator eg. `<BottomTabs.Navigator detachInactiveScreens={false}>`.

These are the errors when checking the Android logcat:

On tab switch (with or without detachInactiveScreens):
```
setState called without a StateWrapper
```

On tab switch:
```
com.facebook.react.uimanager.IllegalViewOperationException: removeViewAt tried to remove a React View that was actually reused. This indicates a bug in the Differ (specifically instruction ordering). [274]
	at com.facebook.react.fabric.mounting.SurfaceMountingManager.removeViewAt(SurfaceMountingManager.java:436)
	at com.facebook.react.fabric.mounting.mountitems.IntBufferBatchMountItem.execute(IntBufferBatchMountItem.java:148)
	at com.facebook.react.fabric.mounting.MountItemDispatcher.executeOrEnqueue(MountItemDispatcher.java:351)
	at com.facebook.react.fabric.mounting.MountItemDispatcher.dispatchMountItems(MountItemDispatcher.java:274)
	at com.facebook.react.fabric.mounting.MountItemDispatcher.tryDispatchMountItems(MountItemDispatcher.java:120)
	at com.facebook.react.fabric.FabricUIManager$DispatchUIFrameCallback.doFrameGuarded(FabricUIManager.java:1245)
	at com.facebook.react.fabric.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
	at android.view.Choreographer.doFrame(Choreographer.java:727)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

```
java.lang.IllegalStateException: addViewAt: cannot insert view [274] into parent [90]: View already has a parent: [-1]  Parent: ScreensFrameLayout View: Screen
	at com.facebook.react.fabric.mounting.SurfaceMountingManager.addViewAt(SurfaceMountingManager.java:372)
	at com.facebook.react.fabric.mounting.mountitems.IntBufferBatchMountItem.execute(IntBufferBatchMountItem.java:146)
	at com.facebook.react.fabric.mounting.MountItemDispatcher.executeOrEnqueue(MountItemDispatcher.java:351)
	at com.facebook.react.fabric.mounting.MountItemDispatcher.dispatchMountItems(MountItemDispatcher.java:274)
	at com.facebook.react.fabric.mounting.MountItemDispatcher.tryDispatchMountItems(MountItemDispatcher.java:120)
	at com.facebook.react.fabric.FabricUIManager$DispatchUIFrameCallback.doFrameGuarded(FabricUIManager.java:1245)
	at com.facebook.react.fabric.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
	at android.view.Choreographer.doFrame(Choreographer.java:727)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

With nested navigator, after a few tab switches:
```
java.lang.IllegalArgumentException: No view found for id 0x196 (unknown) for fragment ScreenFragment{78e001e} (f6bd6569-c944-4f94-b2c9-616cfebed673 id=0x196)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:513)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2106)
	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1971)
	at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:311)
	at com.swmansion.rnscreens.ScreenContainer.onUpdate(ScreenContainer.kt:366)
	at com.swmansion.rnscreens.ScreenContainer.performUpdates(ScreenContainer.kt:311)
	at com.swmansion.rnscreens.ScreenContainer.performUpdatesNow(ScreenContainer.kt:303)
	at com.swmansion.rnscreens.ScreenContainer.setFragmentManager(ScreenContainer.kt:127)
	at com.swmansion.rnscreens.ScreenContainer.setupFragmentManager(ScreenContainer.kt:180)
	at com.swmansion.rnscreens.ScreenContainer.onAttachedToWindow(ScreenContainer.kt:217)
	at android.view.View.dispatchAttachedToWindow(View.java:20479)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3489)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
	at android.view.ViewGroup.addViewInner(ViewGroup.java:5278)
	at android.view.ViewGroup.addView(ViewGroup.java:5064)
	at android.view.ViewGroup.addView(ViewGroup.java:5004)
	at androidx.fragment.app.FragmentStateManager.addViewToContainer(FragmentStateManager.java:833)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:523)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2106)
	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1971)
	at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:311)
	at com.swmansion.rnscreens.ScreenContainer.onUpdate(ScreenContainer.kt:366)
	at com.swmansion.rnscreens.ScreenContainer.performUpdates(ScreenContainer.kt:311)
	at com.swmansion.rnscreens.ScreenContainer.performUpdatesNow(ScreenContainer.kt:303)
	at com.swmansion.rnscreens.ScreenContainer.notifyChildUpdate(ScreenContainer.kt:87)
	at com.swmansion.rnscreens.Screen.setActivityState(Screen.kt:132)
	at com.swmansion.rnscreens.ScreenViewManager.setActivityState(ScreenViewManager.kt:49)
	at com.swmansion.rnscreens.ScreenViewManager.setActivityState(ScreenViewManager.kt:34)
	at com.swmansion.rnscreens.ScreenViewManager.setActivityState(ScreenViewManager.kt:21)
	at com.facebook.react.viewmanagers.RNSScreenManagerDelegate.setProperty(RNSScreenManagerDelegate.java:81)
	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:46)
	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:84)
	at com.facebook.react.views.view.ReactViewManagerWrapper$DefaultViewManager.updateProperties(ReactViewManagerWrapper.kt:59)
	at com.facebook.react.fabric.mounting.SurfaceMountingManager.updateProps(SurfaceMountingManager.java:872)
	at com.facebook.react.fabric.mounting.mountitems.IntBufferBatchMountItem.execute(IntBufferBatchMountItem.java:153)
	at com.facebook.react.fabric.mounting.MountItemDispatcher.executeOrEnqueue(MountItemDispatcher.java:351)
	at com.facebook.react.fabric.mounting.MountItemDispatcher.dispatchMountItems(MountItemDispatcher.java:274)
	at com.facebook.react.fabric.mounting.MountItemDispatcher.tryDispatchMountItems(MountItemDispatcher.java:120)
	at com.facebook.react.fabric.FabricUIManager$DispatchUIFrameCallback.doFrameGuarded(FabricUIManager.java:1245)
	at com.facebook.react.fabric.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
	at android.view.Choreographer.doFrame(Choreographer.java:727)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

https://github.com/react-navigation/react-navigation/assets/37308213/29a6f193-21c9-4d43-8b9e-24b25c9bfe03

### Expected behavior

No errors when switching tabs after enabling the new architecture on Android. 

### Reproduction

https://github.com/cnguyen812/min-repro-navigation-bug

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.6
| @react-navigation/bottom-tabs          | 6.5.7
| @react-navigation/stack                | 6.3.16
| react-native-safe-area-context         | 4.5.3
| react-native-screens                   | 3.20.0
| react-native-gesture-handler           | 2.10.1
| react                              | 18.2.0
| react-native                           | 0.71.7
| node                                   | 18.14.2
| npm or yarn                            | yarn

**Comment by baransu** [comment]
We're experiencing the same errors with Drawer as well.

**Comment by JohnathanWhite** [comment]
+1

**Comment by horne3754sg** [comment]
I am encountering this issue, but only on Android.

**Comment by MagtonHub** [comment]
+1 on Android only!

**Comment by thipoeta** [comment]
same here, +1 on Android

**Comment by leiferikbjorkli** [comment]
+1

**Comment by lomen-KangSoonCheol** [comment]
same here, +1 On android

**Comment by gomestai** [comment]
+1 on android

**Comment by andersonhcc** [comment]
+1

**Comment by andersonhcc** [comment]
same here, +1 on android

**Comment by shaeinst** [comment]
Any update on this?

**Comment by Leesiyi** [comment]
+1

**Comment by kwaller** [comment]
bump, still happening. Anybody find a work around? Every 3rd visit to a page via tab navigator crashes the app with the same error as OP

**Comment by chao-wang-medtasker** [comment]
+1 experiencing the same issue :(

**Comment by tamacoconutlab** [comment]
+1 experiencing the same issue

**Comment by bemulima** [comment]
I have the same error( Are there any solutions by another way not for long time?

**Comment by bemulima** [comment]
If you looking for an another way and using react native paper [Using BottomNavigation with React Navigation](https://callstack.github.io/react-native-paper/docs/guides/bottom-navigation/) working without bug

**Comment by pc9** [comment]
Try setting `detachInactiveScreens={false}` [https://reactnavigation.org/docs/bottom-tab-navigator/#detachinactivescreens](https://reactnavigation.org/docs/bottom-tab-navigator/#detachinactivescreens). Worked for me.

**Comment by danidaryaweesh** [comment]
I'm also experiencing this issue on RN 0.73.1 and latest React-navigation version. I tried @bemulima Solution with React-native-paper and it works with no issues. Have anyone found any solution for this?

**Comment by danidaryaweesh** [comment]
Worked for me by disabling Fabric (new architecture) for now.

**Comment by saheem128** [comment]
I encounter this issue when switching rapidly to and from a bottom tab with nested stack navigator.

**Comment by leonbahley123** [comment]
> detachInactiveScreens={false}

worked

**Comment by tcloudAce** [comment]
+1

**Comment by renyufei8023** [comment]
+1,new architecture enabled

**Comment by sanchezzzs** [comment]
same, newArchEnabled=true

**Comment by k2ker** [comment]
same here, +1 on android

**Comment by DudaMatiasS** [comment]
same here with Stack, only android

**Comment by shuo-hiwintech** [comment]
+1

**Comment by pierroo** [comment]
has there been any news on this matter?
did you guys find a solution, beside using detachInactiveScreens={false} which seems rather ugly for performance?
