### ISSUE TITLE
RN 73: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by UNIDY2002** [react-navigation/react-navigation#11670]
### Current behavior

When running the APP in debug mode, I can see the following error:
```
TypeError: Cannot read property 'map' of undefined

This error is located at:
    in Unknown (created by Header)
    in Header (created by HeaderSegment)
    in HeaderSegment (created by Header)
    in Header (created by HeaderContainer)
    in RCTView (created by View)
    in View (created by HeaderContainer)
    in RCTView (created by View)
    in View
    in Unknown (created by HeaderContainer)
    in HeaderContainer (created by CardContainer)
    in RCTView (created by View)
    in View (created by CardContainer)
    in RCTView (created by View)
    in View
    in CardSheet (created by Card)
    in RCTView (created by View)
    in View
    in Unknown (created by PanGestureHandler)
    in PanGestureHandler (created by PanGestureHandler)
    in PanGestureHandler (created by Card)
    in RCTView (created by View)
    in View
    in Unknown (created by Card)
    in RCTView (created by View)
    in View (created by Card)
    in Card (created by CardContainer)
    in CardContainer (created by CardStack)
    in RNSScreen
    in Unknown (created by InnerScreen)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by InnerScreen)
    in InnerScreen (created by Screen)
    in Screen (created by MaybeScreen)
    in MaybeScreen (created by CardStack)
    in RNSScreenContainer (created by ScreenContainer)
    in ScreenContainer (created by MaybeScreenContainer)
    in MaybeScreenContainer (created by CardStack)
    in RCTView (created by View)
    in View (created by Background)
    in Background (created by CardStack)
    in CardStack (created by HeaderShownContext)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by StackView)
    in RNGestureHandlerRootView (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by StackView)
    in StackView (created by StackNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by StackNavigator)
    in StackNavigator (created by MyStack)
    in MyStack (created by App)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in ReproducerApp(RootComponent), js engine: hermes
```

When running `yarn test` with the default test suite provided by the RN template, I can see the following error:
```
  console.error
    [react-native-gesture-handler] react-native-gesture-handler module was not found. Make sure you're running your app on the native platform and your code is linked properly (cd ios && pod install && cd ..).
    
    For installation instructions, please refer to https://docs.swmansion.com/react-native-gesture-handler/docs/#installation

      2 | import { Button, View } from 'react-native';
      3 | import { NavigationContainer } from '@react-navigation/native';
    > 4 | import { createStackNavigator } from '@react-navigation/stack';
        | ^
      5 |
      6 | function HomeScreen({ navigation }) {
      7 |   return (

      at Object.error (node_modules/react-native-gesture-handler/lib/commonjs/RNGestureHandlerModule.ts:7:11)
      at Object.<anonymous> (node_modules/react-native-gesture-handler/lib/commonjs/init.ts:2:1)
      at Object.<anonymous> (node_modules/react-native-gesture-handler/lib/commonjs/index.ts:1:1)
      at Object.require (node_modules/@react-navigation/stack/src/views/GestureHandlerNative.tsx:2:1)
      at Object.require (node_modules/@react-navigation/stack/src/views/GestureHandler.ios.tsx:1:1)
      at Object.require (node_modules/@react-navigation/stack/src/views/Stack/StackView.tsx:24:1)
      at Object.require (node_modules/@react-navigation/stack/src/navigators/createStackNavigator.tsx:22:1)
      at Object.require (node_modules/@react-navigation/stack/src/index.tsx:9:1)
      at Object.require (App.tsx:4:1)
      at Object.require (__tests__/App.test.tsx:7:1)

  console.error
    The above error occurred in the <ForwardRef> component:
    
        at /home/unidy/repos/navigation-test/ReproducerApp/node_modules/react-native/Libraries/Animated/createAnimatedComponent.js:36:57
        at Header (/home/unidy/repos/navigation-test/ReproducerApp/node_modules/@react-navigation/elements/src/Header/Header.tsx:46:35)
        at useState (/home/unidy/repos/navigation-test/ReproducerApp/node_modules/@react-navigation/stack/src/views/Header/HeaderSegment.tsx:36:55)
        at back (/home/unidy/repos/navigation-test/ReproducerApp/node_modules/@react-navigation/stack/src/views/Header/Header.tsx:12:3)
        at View
        at Component (/home/unidy/repos/navigation-test/ReproducerApp/node_modules/react-native/jest/mockComponent.js:30:18)
        at View
        at Component (/home/unidy/repos/navigation-test/ReproducerApp/node_modules/react-native/jest/mockComponent.js:30:18)
        at /home/unidy/repos/navigation-test/ReproducerApp/node_modules/react-native/Libraries/Animated/createAnimatedComponent.js:36:57
        at mode (/home/unidy/repos/navigation-test/ReproducerApp/node_modules/@react-navigation/stack/src/views/Header/HeaderContainer.tsx:40:3)
        at View
        at Component (/home/unidy/repos/navigation-test/ReproducerApp/node_modules/react-native/jest/mockComponent.js:30:18)
        at style (/home/unidy/repos/navigation-test/ReproducerApp/node_modules/@react-navigation/elements/src/Background.tsx:9:38)
        at CardStack (/home/unidy/repos/navigation-test/ReproducerApp/node_modules/@react-navigation/stack/src/views/Stack/CardStack.tsx:385:29)
        at RNCSafeAreaProvider
        at Component (/home/unidy/repos/navigation-test/ReproducerApp/node_modules/react-native/jest/mockNativeComponent.js:17:18)
        at children (/home/unidy/repos/navigation-test/ReproducerApp/node_modules/react-native-safe-area-context/src/SafeAreaContext.tsx:35:3)
        at children (/home/unidy/repos/navigation-test/ReproducerApp/node_modules/@react-navigation/elements/src/SafeAreaProviderCompat.tsx:34:50)
        at View
        at Component (/home/unidy/repos/navigation-test/ReproducerApp/node_modules/react-native/jest/mockComponent.js:30:18)
        at GestureHandlerRootView
        at StackView (/home/unidy/repos/navigation-test/ReproducerApp/node_modules/@react-navigation/stack/src/views/Stack/StackView.tsx:63:31)
        at children (/home/unidy/repos/navigation-test/ReproducerApp/node_modules/@react-navigation/core/src/PreventRemoveProvider.tsx:45:49)
        at render (/home/unidy/repos/navigation-test/ReproducerApp/node_modules/@react-navigation/core/src/useComponent.tsx:10:30)
        at children (/home/unidy/repos/navigation-test/ReproducerApp/node_modules/@react-navigation/core/src/useComponent.tsx:26:26)
        at id (/home/unidy/repos/navigation-test/ReproducerApp/node_modules/@react-navigation/stack/src/navigators/createStackNavigator.tsx:34:3)
        at MyStack
        at children (/home/unidy/repos/navigation-test/ReproducerApp/node_modules/@react-navigation/core/src/EnsureSingleNavigator.tsx:20:49)
        at initialState (/home/unidy/repos/navigation-test/ReproducerApp/node_modules/@react-navigation/core/src/BaseNavigationContainer.tsx:82:7)
        at value (/home/unidy/repos/navigation-test/ReproducerApp/node_modules/@react-navigation/native/src/theming/ThemeProvider.tsx:11:41)
        at theme (/home/unidy/repos/navigation-test/ReproducerApp/node_modules/@react-navigation/native/src/NavigationContainer.tsx:55:5)
        at App
    
    Consider adding an error boundary to your tree to customize error handling behavior.
    Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.

      14 |
      15 | it('renders correctly', () => {
    > 16 |   renderer.create(<App />);
         |            ^
      17 | });
      18 |

      at logCapturedError (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8661:23)
      at update.callback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8694:5)
      at callCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:4092:12)
      at commitUpdateQueue (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:4113:9)
      at commitLayoutEffectOnFiber (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13232:13)
      at commitLayoutMountEffects_complete (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14330:9)
      at commitLayoutEffects_begin (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14316:7)
      at commitLayoutEffects (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14301:3)
      at commitRootImpl (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:16062:5)
      at commitRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15933:5)
      at performSyncWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15454:3)
      at flushSyncCallbacks (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2597:22)
      at flushSyncCallbacksOnlyInLegacyMode (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2576:5)
      at scheduleUpdateOnFiber (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14910:7)
      at updateContainer (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:17770:5)
      at Object.create (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:18510:3)
      at Object.create (__tests__/App.test.tsx:16:12)

 FAIL  __tests__/App.test.tsx
  ✕ renders correctly (87 ms)

  ● renders correctly

    TypeError: Cannot read properties of undefined (reading 'map')

      14 |
      15 | it('renders correctly', () => {
    > 16 |   renderer.create(<App />);
         |            ^
      17 | });
      18 |

      at AnimatedTransform.map [as _get] (node_modules/react-native/Libraries/Animated/nodes/AnimatedTransform.js:100:29)
      at AnimatedTransform._get [as __getValue] (node_modules/react-native/Libraries/Animated/nodes/AnimatedTransform.js:40:17)
      at AnimatedStyle.__getValue (node_modules/react-native/Libraries/Animated/nodes/AnimatedStyle.js:64:29)
      at AnimatedProps.__getValue (node_modules/react-native/Libraries/Animated/nodes/AnimatedProps.js:56:28)
      at __getValue (node_modules/react-native/Libraries/Animated/useAnimatedProps.js:125:13)
      at reduceAnimatedProps (node_modules/react-native/Libraries/Animated/useAnimatedProps.js:116:11)
      at node_modules/react-native/Libraries/Animated/createAnimatedComponent.js:36:57
      at renderWithHooks (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6351:18)
      at updateForwardRef (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9150:20)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11361:16)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15811:12)
      at workLoopSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15745:5)
      at renderRootSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15717:7)
      at performSyncWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15422:20)
      at flushSyncCallbacks (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2597:22)
      at flushSyncCallbacksOnlyInLegacyMode (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2576:5)
      at scheduleUpdateOnFiber (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14910:7)
      at updateContainer (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:17770:5)
      at Object.create (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:18510:3)
      at Object.create (__tests__/App.test.tsx:16:12)
```

On RN 72, everything worked just fine.

Could anyone help me look into what is going wrong?

Thank you!

### Expected behavior

The error should not show up.

### Reproduction

https://github.com/UNIDY2002/repro-rn-73-react-navigation

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.9 |
| @react-navigation/bottom-tabs          | N/A |
| @react-navigation/drawer               | N/A |
| @react-navigation/material-top-tabs    | N/A |
| @react-navigation/stack                | 6.3.20 |
| @react-navigation/native-stack         | N/A |
| react-native-safe-area-context         | 4.7.4 |
| react-native-screens                   | 3.27.0 |
| react-native-gesture-handler           | 2.13.4 |
| react-native-reanimated                | N/A |
| react-native-tab-view                  | N/A |
| react-native-pager-view                | N/A |
| react-native                           | 0.73.0-rc.3 |
| expo                                   | N/A |
| node                                   | 20.8.0 (local) / 18 (actions) |
| npm or yarn                            | 1.22.19 |

**Comment by UNIDY2002** [comment]
Should be fixed by https://github.com/facebook/react-native/pull/41176. Closing.
