### ISSUE TITLE
Jest raising error `useLegacyImplementation` prop is not available with Reanimated 3

### ISSUE THREAD

**Issue by SarahBunker** [react-navigation/react-navigation#11722]
### Current behavior

Basic jest test suite that tests that the app renders correctly fails with the error:

```
$ npm run test

> jest_Reanimated@0.0.1 test
> jest

  console.error
    The above error occurred in the <DrawerViewBase> component:
    
        at state (/home/sarahnd/HomeFile/jest_Reanimated/node_modules/@react-navigation/drawer/src/views/DrawerView.tsx:68:3)
        at View
        at Component (/home/sarahnd/HomeFile/jest_Reanimated/node_modules/react-native/jest/mockComponent.js:30:18)
        at GestureHandlerRootView
        at RNCSafeAreaProvider
        at Component (/home/sarahnd/HomeFile/jest_Reanimated/node_modules/react-native/jest/mockNativeComponent.js:17:18)
        at children (/home/sarahnd/HomeFile/jest_Reanimated/node_modules/react-native-safe-area-context/src/SafeAreaContext.tsx:35:3)
        at children (/home/sarahnd/HomeFile/jest_Reanimated/node_modules/@react-navigation/elements/src/SafeAreaProviderCompat.tsx:34:50)
        at navigation (/home/sarahnd/HomeFile/jest_Reanimated/node_modules/@react-navigation/drawer/src/views/DrawerView.tsx:302:38)
        at children (/home/sarahnd/HomeFile/jest_Reanimated/node_modules/@react-navigation/core/src/PreventRemoveProvider.tsx:45:49)
        at render (/home/sarahnd/HomeFile/jest_Reanimated/node_modules/@react-navigation/core/src/useComponent.tsx:10:30)
        at children (/home/sarahnd/HomeFile/jest_Reanimated/node_modules/@react-navigation/core/src/useComponent.tsx:26:26)
        at id (/home/sarahnd/HomeFile/jest_Reanimated/node_modules/@react-navigation/drawer/src/navigators/createDrawerNavigator.tsx:32:3)
        at children (/home/sarahnd/HomeFile/jest_Reanimated/node_modules/@react-navigation/core/src/EnsureSingleNavigator.tsx:20:49)
        at initialState (/home/sarahnd/HomeFile/jest_Reanimated/node_modules/@react-navigation/core/src/BaseNavigationContainer.tsx:82:7)
        at value (/home/sarahnd/HomeFile/jest_Reanimated/node_modules/@react-navigation/native/src/theming/ThemeProvider.tsx:11:41)
        at theme (/home/sarahnd/HomeFile/jest_Reanimated/node_modules/@react-navigation/native/src/NavigationContainer.tsx:55:5)
        at App
    
    Consider adding an error boundary to your tree to customize error handling behavior.
    Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.

      14 |
      15 | it('renders correctly', () => {
    > 16 |   renderer.create(<App />);
         |            ^
      17 | });
      18 |

      at logCapturedError (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8661:23)
      at update.callback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8694:5)
      at callCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:4092:12)
      at commitUpdateQueue (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:4113:9)
      at commitLayoutEffectOnFiber (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13232:13)
      at commitLayoutMountEffects_complete (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14330:9)
      at commitLayoutEffects_begin (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14316:7)
      at commitLayoutEffects (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14301:3)
      at commitRootImpl (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:16062:5)
      at commitRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15933:5)
      at performSyncWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15454:3)
      at flushSyncCallbacks (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2597:22)
      at flushSyncCallbacksOnlyInLegacyMode (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2576:5)
      at scheduleUpdateOnFiber (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14910:7)
      at updateContainer (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:17770:5)
      at Object.create (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:18510:3)
      at Object.create (__tests__/App.test.tsx:16:12)

 FAIL  __tests__/App.test.tsx
  ✕ renders correctly (82 ms)

  ● renders correctly

    The `useLegacyImplementation` prop is not available with Reanimated 3 as it no longer includes support for Reanimated 1 legacy API. Remove the `useLegacyImplementation` prop from `Drawer.Navigator` to be able to use it.

      14 |
      15 | it('renders correctly', () => {
    > 16 |   renderer.create(<App />);
         |            ^
      17 | });
      18 |

      at DrawerViewBase (node_modules/@react-navigation/drawer/src/views/DrawerView.tsx:87:11)
      at renderWithHooks (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6351:18)
      at mountIndeterminateComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9855:13)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11312:16)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15811:12)
      at workLoopSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15745:5)
      at renderRootSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15717:7)
      at performSyncWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15422:20)
      at flushSyncCallbacks (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2597:22)
      at flushSyncCallbacksOnlyInLegacyMode (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2576:5)
      at scheduleUpdateOnFiber (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14910:7)
      at updateContainer (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:17770:5)
      at Object.create (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:18510:3)
      at Object.create (__tests__/App.test.tsx:16:12)
```

### Expected behavior

Since I am not using the `useLegacyImplementation` prop in my code I expect it to not have this error.

### Reproduction

https://github.com/SarahBunker/jest_Reanimated-

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

The versions in the repo I created to reproduce the issue

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/drawer               | "^6.6.6"
| react-native-safe-area-context         | "^4.7.4"
| react-native-screens                   | "^3.27.0"
| react-native-gesture-handler           | "^2.14.0"
| react-native-reanimated                | "^3.5.4"
| react-native                           | "0.72.7"
| node                                   | ">=16"
| npm or yarn                            | "8.19.2"
| react  | "18.2.0"

The versions in my project that I originally found the issue in:

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | "^6.1.9"
| @react-navigation/bottom-tabs          | 
| @react-navigation/drawer               | "^6.6.6"
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                | "^6.3.20"
| @react-navigation/native-stack         | "^6.1.9"
| react-native-safe-area-context         | "^4.7.4"
| react-native-screens                   | "^3.27.0"
| react-native-gesture-handler           | "^2.14.0"
| react-native-reanimated                | "^3.5.4"
| react-native                           | "0.72.6"
| node                                   | ">=16"
| npm or yarn                            | "8.19.2"
| react  | "18.2.0"

There is a difference in the react-native	patch version, and the original project has a few more dependencies that I think are unneccesary since I am moving from stack to drawer navigation. But I thought I would include in case it is relevant.

**Comment by SarahBunker** [comment]
Bot asked for version numbers for bottom-tabs and material top tabs which I am not using so I don't have versions.

**Comment by capella55** [comment]
@SarahBunker Any luck?

**Comment by VadimZP** [comment]
Any updates?

**Comment by Stewartarmbrecht** [comment]
Getting this error as well.  Were you able to resolve it?

**Comment by Stewartarmbrecht** [comment]
I got around this error by adding the useLegacyImplementation prop and setting it to false:

`        <Drawer screenOptions={{
            drawerType: 'permanent',
          }}
          useLegacyImplementation={false}
        >
`
