### ISSUE TITLE
Cannot find module ‘./PlatformHelpers’ from ‘createNavigationContainer.js’

### ISSUE THREAD

**Issue by octohedron** [react-navigation/react-navigation#2310]
Trying to test my `react-native` app with `jest` and it's throwing

`Cannot find module ‘./PlatformHelpers’ from ‘createNavigationContainer.js’`

For some reason the fix at #256 doesn't work for me.
```json
"jest": {
    "preset": "react-native",
    "collectCoverageFrom": [
      "**/*.{js,jsx}",
      "!**/loggerMiddleware.js",
      "!**/index.android.js",
      "!**/node_modules/**",
      "!**/android/**",
      "!**/ios/**",
      "!**/index.ios.js",
      "!**/AppRouter.js",
      "!**/snapshot.js",
      "!**/coverage/**",
      "!**/AppView.js",
      "!**/vendor/**",
      "!**/config/**",
      "!**/data/**",
      "!**/test/**"
    ],
    "haste": {
      "defaultPlatform": "ios",
      "platforms": [
        "android",
        "ios"
      ],
      "providesModuleNodeModules": [
        "react-native"
      ]
    },
    "globals": {
      "__TEST__": true
    },
    "moduleNameMapper": {
      "^image![a-zA-Z0-9$_-]+$": "GlobalImageStub",
      "^[@./a-zA-Z0-9$_-]+\\.(png|gif)$": "RelativeImageStub",
      "^React$": "<rootDir>node_modules/react",
      "\\./datepicker$": "<rootDir>/node_modules/tcomb-form-native/lib/templates/bootstrap/datepicker.ios.js",
      "\\./select$": "<rootDir>/node_modules/tcomb-form-native/lib/templates/bootstrap/select.ios.js"
    },
    "modulePathIgnorePatterns": [
      "<rootDir>/node_modules/react-native/Libraries/react-native/",
      "<rootDir>/node_modules/react-native/packager/",
      "<rootDir>/node_modules/react-native-intercom/*",
      "<rootDir>/node_modules/react-native-fabric/",
      "<rootDir>/node_modules/apollo-client/"
    ],
    "transformIgnorePatterns": [
      "node_modules/(?!(jest-)?react-native|tcomb-form-native|react-clone-referenced-element|apollo-client|react-navigation)"
    ],
    "setupFiles": [
      "<rootDir>/node_modules/react-native/jest/setup.js",
      "./jest-setup.js"
    ],
    "testEnvironment": "node",
    "testResultsProcessor": "./node_modules/jest-junit",
    "collectCoverage": true,
    "verbose": true
  },
```

Keeps throwing `Cannot find module ‘./PlatformHelpers’ from ‘createNavigationContainer.js’`

Dependencies
```json
"dependencies": {
    "apollo-client": "^1.9.0",
    "art": "^0.10.1",
    "babel-cli": "~6.6.5",
    "bluebird": "^3.3.5",
    "crypto-js": "^3.1.9-1",
    "d3": "^4.10.0",
    "d3-shape": "^1.0.6",
    "es6-symbol": "^3.1.0",
    "event-emitter": "^0.3.4",
    "graphql": "^0.6.2",
    "graphql-tag": "^1.3.1",
    "immutable": "^3.7.6",
    "lodash": "^4.11.0",
    "moment": "^2.16.0",
    "parse": "~1.8.2",
    "react": "^16.0.0-alpha.12",
    "react-apollo": "^1.4.5",
    "react-dom": "^16.0.0-alpha.12",
    "react-native": "0.45.1",
    "react-native-action-button": "github:octohedron/react-native-action-button#de061b0700867133e3b1c995022d2eac279214fa",
    "react-native-code-push": "2.1.0-beta",
    "react-native-datepicker": "^1.4.2",
    "react-native-fabric": "^0.4.1",
    "react-native-intercom": "^6.2.0",
    "react-native-keyboard-aware-scrollview": "^1.1.7",
    "react-native-keyboard-spacer": "^0.3.0",
    "react-native-modal-picker": "github:octohedron/react-native-modal-picker#174997eb5b58841d58b0550e795ab9f70e3bba4d",
    "react-native-scrollable-tab-view": "^0.7.4",
    "react-navigation": "^1.0.0-beta.12",
    "react-redux": "^5.0.5",
    "react-timer-mixin": "~0.13.3",
    "redux": "^3.7.1",
    "redux-logger": "^3.0.6",
    "redux-loop": "^2.2.2",
    "redux-persist": "^1.5.6",
    "redux-promise": "^0.5.3",
    "redux-thunk": "^2.2.0",
    "tcomb-form-native": "^0.6.6"
  },
  "devDependencies": {
    "apollo-test-utils": "0.3.2",
    "babel-core": "^6.9.0",
    "babel-eslint": "^6.0.2",
    "babel-jest": "19.0.0",
    "babel-polyfill": "^6.9.0",
    "babel-preset-react-native": "1.9.1",
    "babel-register": "^6.9.0",
    "buffer": "^5.0.2",
    "chai": "^3.5.0",
    "chokidar-cli": "^1.2.0",
    "deep-eql": "^2.0.1",
    "enzyme": "^2.9.1",
    "eslint": "^3.17.0",
    "eslint-plugin-babel": "^3.2.0",
    "eslint-plugin-react": "^4.3.0",
    "install": "^0.8.4",
    "jest": "^20.0.4",
    "jest-junit": "^1.0.4",
    "mocha": "^2.4.5",
    "npm": "^4.0.5",
    "redux-mock-store": "^1.2.1",
    "rimraf": "^2.5.2",
    "sinon": "^1.17.4"
  },
```
``` bash
$ node -v
v 8.1.4
$ npm -v
5.0.3
```

I went to the `node_modules/react-navigation` folder and renamed `PlatformHelpers.native.js` to `PlatformHelpers.js` and it fixed it, is this fixed somewhere else and I missed it? Otherwise I'll just fork the repo and add the file.

**Comment by spencercarli** [comment]
Would you be able to put together a demo of this problem to aid in debugging? Thanks!

**Comment by octohedron** [comment]
Unfortunately, I don't have time at the moment, I will just fork it and add the file myself, can't afford having to rename the file every time I need to re-install the module.

**Comment by karlas** [comment]
Same problem here. As @octohedron , have to rename file

Created a quick script in my package.json file to rename it:

`"fix-react-navigation-web": "mv ./node_modules/react-navigation/lib/PlatformHelpers.native.js ./node_modules/react-navigation/lib/PlatformHelpers.js"`

**Comment by kelset** [comment]
Pinging OP @octohedron since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

**Comment by mschipperheyn** [comment]
@kelset this error occurs to me on every jest test (even if the test doesn't reference any react-native component). Using `react-navigation` 1.0.0-beta.21 and `react-native` 0.49.5

```
Cannot find module './PlatformHelpers' from 'createNavigationContainer.js'
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:191:17)
      at Object.<anonymous> (node_modules/react-navigation/src/createNavigationContainer.js:40:119)
```

package.json
```
"jest": {
		"haste": {
			"defaultPlatform": "android",
			"platforms": [
				"ios",
				"android"
			],
			"providesModuleNodeModules": [
				"react-native"
			]
		},
		"preset": "react-native",
		"transformIgnorePatterns": [
			"node_modules/(realm)/"
		],
		"snapshotSerializers": [
			"enzyme-to-json/serializer"
		],
		"setupTestFrameworkScriptFile": "./test/setupJest.js",
		"moduleDirectories": [
			"node_modules"
		],
		"transform": {
			"^.+\\.jsx?$": "babel-jest"
		},
		"unmockedModulePathPatterns": [
			"promise",
			"source-map"
		]
	},
```

setupJest.js
```
import React from 'react';
import FormData from 'react-native/Libraries/Network/FormData';

global.FormData = FormData;

jest.mock('react-native-progress', () => 'RnProgress');
jest.mock('react-native-fs', () => 'RnFS');
jest.mock('react-native-scrollable-tab-view', () => 'RNScrollableTabView');
jest.mock('react-native-cookies', () => 'RNCookieManagerIOS');
jest.mock('react-native-fetch-blob', () => ({
	DocumentDir: () => {},
	polyfill: () => {}
}));

```

**Comment by januswel** [comment]
Add below lines to your `.flowconfig` options section.

```
module.file_ext=.web.js
module.file_ext=.native.js
```

This works for my env.

**Comment by oo7rm** [comment]
When I run npm test I am also gettibg this error 

![screenshot from 2018-01-20 04-35-30](https://user-images.githubusercontent.com/15632202/35175814-7f84f588-fd9b-11e7-89d5-367308633484.png)

My package.json 





```{
     "name": "crowdAlert",
    "version": "0.1.0",
    "private": true,
    "devDependencies": {
    "jest-expo": "~18.0.0",
    "react-native-scripts": "0.0.31",
    "react-test-renderer": "16.0.0-alpha.12"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "node node_modules/jest/bin/jest.js --coverage"
  },
  "jest": {
    "preset": "jest-expo",
    "transformIgnorePatterns": [
      "!node_modules/"
    ]
  },
  "dependencies": {
    "babel-preset-react-native": "2.1.0",
    "exp": "^42.1.0",
    "expo": "^18.0.0",
    "firebase": "^4.1.3",
    "jest-cli": "20.0.4",
    "native-base": "2.2.0",
    "react": "16.0.0-alpha.12",
    "react-native": "https://github.com/expo/react-native/archive/sdk-18.0.1.tar.gz",
    "react-native-check-box": "^1.0.4",
    "react-native-material-bottom-navigation": "^0.5.1",
    "react-native-prompt": "^1.0.0",
    "react-native-smart-loading-spinner-overlay": "^1.0.2",
    "react-native-vector-icons": "^4.2.0",
    "react-navigation": "^1.0.0-beta.27"
  }
}```

**Comment by ssorallen** [comment]
@januswel Your solution partially works, except it causes Flow to treat files ending only in `.js` as `any`. The following config fixed this error for me:

```
[options]
module.file_ext=.js
module.file_ext=.web.js
module.file_ext=.native.js
```

**Comment by oo7rm** [comment]
@ssorallen i tried your method , but it is not working it returns the same output as I have shown above.

**Comment by brentvatne** [comment]
this should be resolved. if it is not working as expected still on the latest version, please create a new issue with a runnable example on https://snack.expo.io -- thanks!
