### ISSUE TITLE
ENOENT: no such file or directory, open 'react-navigation/src/views/CardStack/CardStack.js'

### ISSUE THREAD

**Issue by wzup** [react-navigation/react-navigation#4773]
## The issue tracker is reserved for bug reports only.

Bug

Is this package back compatible?
Why I can't use v2 immediately after v1 removal?

---

### Current Behavior

```batch
error: bundling failed: Error: ENOENT: no such file or directory, open '/Users/user/app/node_modules/react-navigation/src/views/CardStack/CardStack.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Module._readSourceCode (/Users/user/app/node_modules/metro/src/node-haste/Module.js:206:29)
    at Module._getCacheProps (/Users/user/app/node_modules/metro/src/node-haste/Module.js:398:29)
    at Module._readFromTransformCache (/Users/user/app/node_modules/metro/src/node-haste/Module.js:359:29)
    at Module.readCached (/Users/user/app/node_modules/metro/src/node-haste/Module.js:346:19)
    at /Users/user/app/node_modules/metro/src/node-haste/Module.js:327:29
    at Generator.next (<anonymous>)
    at step (/Users/user/app/node_modules/metro/src/node-haste/Module.js:11:445)
    at /Users/user/app/node_modules/metro/src/node-haste/Module.js:11:675
```

### Expected Behavior

No errors

### How to reproduce

Before "react-navigation": "^1.5.8",
After "react-navigation": "^2.9.2",
```
npm rm -S react-navigation
npm i -S react-navigation
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.8 => 2.9.2
| react-native     |0.54.2
| node             |8.11.3
| npm or yarn      |5.6.0

**Comment by brentvatne** [comment]
i guess you might be importing that view by path? importing by path is not part of the public api, you need to import from react-navigation root. also try restarting packager and clearing cache (google for how to clear react native packager cache for more info)
