### ISSUE TITLE
Cannot build with metro and babel 7

### ISSUE THREAD

**Issue by ajcrites** [react-navigation/react-navigation#4983]
### Current Behavior
When you have configured a react-native project to build with babel 7, running `react-native start` with `react-native run-ios` does not build. 

```
error: bundling failed: TypeError: comments is not iterable
    at PluginPass.Program (test-project/node_modules/@babel/plugin-transform-flow-strip-types/lib/index.js:58:31)
    at newFn (test-project/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (test-project/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (test-project/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (test-project/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (test-project/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (test-project/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (test-project/node_modules/@babel/traverse/lib/context.js:146:19)
    at Function.traverse.node (test-project/node_modules/@babel/traverse/lib/index.js:94:17)
```

The actual issue occurs here: https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-flow-strip-types/src/index.js#L28 because `comments` is `null`.

I've confirmed that this is caused by `react-navigation`.  It can be caused by importing and using `createStackNavigator` or `createTabsNavigator`. Other methods are untested.

### Expected Behavior
The project should build and deploy to the running test device.

### How to reproduce
Setting up a react native project to build with babel 7:

```
npx react-native-cli init test-project
cd test-project
rm .babelrc
yarn add --dev @babel/plugin-transform-runtime @babel/runtime
```

```js
// babel.config.js
module.exports = function(api) {
  api.cache(false);
  return {
    "presets": ["module:metro-react-native-babel-preset"],
    "plugins": ["@babel/transform-runtime"],
  };
}
```

Note that this happens regardless of whether you add `@babel/core` and the babel 7 bridge.

Then, run `react-native start` and `react-native run-ios` (not tested with Android).

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.14.0
| react-native     | 0.57.0
| node             | 9 and 10
| npm or yarn      | yarn 1.9

**Comment by brentvatne** [comment]
Feel free to send a PR when you've figured it out! I don't have time at the moment to investigae

**Comment by AlicanC** [comment]
Try adding `exclude: ['**/*.png', '...']` to your `babel.config.js`:
```javascript
/* @flow */

module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: ['@babel/transform-runtime'],
  exclude: ['**/*.png', '**/*.gif'],
};

```
