### ISSUE TITLE
Jest testing with Expo failed ,  SyntaxError: Unexpected identifier 

### ISSUE THREAD

**Issue by JackJackNg** [react-navigation/react-navigation#5574]
### Current Behavior

- What code are you running and what is happening?
i am trying to do jest snapshot testing with typescript. But when i try to do snapshot testing the <App> component using createDrawerNavigator and createSwitchNavigator , it gave me the following error 
`yarn test `
test failed with `SyntaxError: Unexpected identifier`
```
 ● Test suite failed to run

    C:\github\expo-react-navigtaion-testing\node_modules\@react-navigation\native\src\createAppContainer.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import React from 'react';
                                                                                                    ^^^^^

    SyntaxError: Unexpected identifier

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
      at Object.<anonymous> (node_modules/react-navigation/NavigationTestUtils.js:1:154)
```

I tried to add   `"transformIgnorePatterns"` add pack.json jest setting , but it is not working and does't 
seem like related to this issue as well

```
Test Suites: 0 of 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2s, estimated 4s
  console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8851
    The above error occurred in the <DrawerView> component:
        in DrawerView (created by Navigator)
        in Navigator (at createAppContainer.js:326)
        in NavigationContainer

    React will try to recreate this component tree from scratch using the error boundary you provided, NavigationContainer.

 FAIL  __tests__/App.test.tsxreact-test-renderer/cjs/react-test-renderer.development.js:8851
  App snapshot
    × renders the loading screen (68ms)

  ● App snapshot › renders the loading screen

    TypeError: Cannot read property 'default' of undefined

      at new DrawerView (node_modules/react-navigation-drawer/dist/views/DrawerView.js:15:423)
      at constructClassInstance (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3426:18)
      at updateClassComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6550:5)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7426:16)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10996:12)
      at workLoop (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11028:24)
      at renderRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11111:7)
      at performWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11985:7)
      at performWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11897:7)
      at performSyncWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11871:3)

```

### Expected Behavior

- What do you expect should be happening?
jest snapshot success

### How to reproduce
```

yarn

yarn test //test failed

```
repo : https://github.com/JackJackNg/expo-react-navigtaion-testing.git

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.9 
| expo | sdk 32 |
| react-native  | 0.57 
| node             | 10.10.0
| npm or yarn      | yarn

**Comment by JackJackNg** [comment]
i not sure whether it is related to react-navigation. because it look like it is some problems with my jest setup

**Comment by brentvatne** [comment]
sorry we don't provide support for jest. you're right about `transformIgnorePatterns`, check out what jest-expo uses

**Comment by mehranabi** [comment]
Hi, Thanks for this amazing library, I have the same problem, any fix @JackJackNg ?

**Comment by brentvatne** [comment]
you might want to use something like this in your jest config:
- https://github.com/expo/expo/blob/7c30288bebb64ae3086b3a00f151c5982cd9fbc6/packages/jest-expo/jest-preset.json#L24-L26

and mock react-native-gesture-handler like this:
- https://github.com/expo/expo/blob/7c30288bebb64ae3086b3a00f151c5982cd9fbc6/packages/jest-expo/src/preset/setup.js#L167-L199

**Comment by yukster** [comment]
This is what fixed it for me: https://github.com/kmagiera/react-native-gesture-handler/issues/344#issuecomment-470252647
