### ISSUE TITLE
Unable to resolve module

### ISSUE THREAD

**Issue by TaroXin** [react-navigation/react-navigation#6067]
### Current Behavior

When i run `react-native run-android`, i got this:
`
error: bundling failed: Error: Unable to resolve module `../../../src/eact-navigation/native` from `/Users/yangxin/Desktop/YchProjects/YunyouMiniPOS/node_modules/react-navigation/src/react-navigation.js`: The module `../../../src/eact-navigation/native` could not be found from `/Users/yangxin/Desktop/YchProjects/YunyouMiniPOS/node_modules/react-navigation/src/react-navigation.js`. Indeed, none of these files exist:
  * `/Users/yangxin/Desktop/YchProjects/YunyouMiniPOS/src/eact-navigation/native(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
  * `/Users/yangxin/Desktop/YchProjects/YunyouMiniPOS/src/eact-navigation/native/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
    at ModuleResolver.resolveDependency (/Users/yangxin/Desktop/YchProjects/YunyouMiniPOS/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:120:15)
    at ResolutionRequest.resolveDependency (/Users/yangxin/Desktop/YchProjects/YunyouMiniPOS/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:49:18)
    at DependencyGraph.resolveDependency (/Users/yangxin/Desktop/YchProjects/YunyouMiniPOS/node_modules/metro/src/node-haste/DependencyGraph.js:218:16)
    at Object.resolve (/Users/yangxin/Desktop/YchProjects/YunyouMiniPOS/node_modules/metro/src/lib/transformHelpers.js:141:30)
    at dependencies.map.result (/Users/yangxin/Desktop/YchProjects/YunyouMiniPOS/node_modules/metro/src/DeltaBundler/traverseDependencies.js:373:31)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/yangxin/Desktop/YchProjects/YunyouMiniPOS/node_modules/metro/src/DeltaBundler/traverseDependencies.js:369:18)
    at /Users/yangxin/Desktop/YchProjects/YunyouMiniPOS/node_modules/metro/src/DeltaBundler/traverseDependencies.js:188:33
    at Generator.next (<anonymous>)
    at step (/Users/yangxin/Desktop/YchProjects/YunyouMiniPOS/node_modules/metro/src/DeltaBundler/traverseDependencies.js:298:30)
`

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.11.0
| react-native     | 0.57.8
| node             | 8.11.1
| npm or yarn      | yarn 1.6.0

**Comment by satya164** [comment]
Seems like there's a problem in your code. Closing the issue.

If you believe this is a bug in the library, please open a new issue with a proper runnable repro.
