### ISSUE TITLE
React-Native 0.60 and ReactNavigation

### ISSUE THREAD

**Issue by KaviduAloka** [react-navigation/react-navigation#6068]
As React-Native 0.60 is being published, react-native-navigation is not working like it was in **0.59**. Loads of errors are occurring. Specially when it comes to linking `gesture-handler`. Please look into this.

**Comment by mrigo** [comment]
+1

**Comment by M1seRy** [comment]
+1

**Comment by liuspatt** [comment]
+1

**Comment by salomaosnff** [comment]
+1

**Comment by svipas** [comment]
# Problem

I don't know if it's related, but I couldn't launch the project with suggestions in this page: https://reactnavigation.org/docs/en/getting-started.html#installation which says to add `react-native-gesture-handler` to `react-native.config.js` and then do `react-native link react-native-gesture-handler` (which does nothing and if I add by hand I get the error too).

# Solution

So I managed to fix it by simply ignoring these recommendations and by adding `react-native-gesture-handler` to `Podfile` and then I was able to launch the project.

# Errors

```
In file included from /Users/svipas/Documents/Retailer-ipad-app/node_modules/react-native-gesture-handler/ios/RNGestureHandler.h:3:
/Users/svipas/Documents/Retailer-ipad-app/node_modules/react-native-gesture-handler/ios/RNGestureHandlerEvents.h:1:9: fatal error: 'React/RCTEventDispatcher.h' file not found
#import <React/RCTEventDispatcher.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~


In file included from /Users/svipas/Documents/Retailer-ipad-app/node_modules/react-native-gesture-handler/ios/RNGestureHandler.h:3:
/Users/svipas/Documents/Retailer-ipad-app/node_modules/react-native-gesture-handler/ios/RNGestureHandlerEvents.h:1:9: fatal error: 'React/RCTEventDispatcher.h' file not found
#import <React/RCTEventDispatcher.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

In file included from /Users/svipas/Documents/Retailer-ipad-app/node_modules/react-native-gesture-handler/ios/RNGestureHandler.h:3:
/Users/svipas/Documents/Retailer-ipad-app/node_modules/react-native-gesture-handler/ios/RNGestureHandlerEvents.h:1:9: fatal error: 'React/RCTEventDispatcher.h' file not found
#import <React/RCTEventDispatcher.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~


** BUILD FAILED **
```

**Comment by PL-SQL** [comment]
![image](https://user-images.githubusercontent.com/37580744/61016859-c0328f80-a3c3-11e9-9a3e-e98fe86fd095.png)

**Comment by concuacon** [comment]
same problem in Android =)) 
<img width="859" alt="Screen Shot 2019-07-11 at 5 50 01 PM" src="https://user-images.githubusercontent.com/11958061/61045191-92216f80-a404-11e9-9435-d984269199c4.png">

**Comment by concuacon** [comment]
same issue :)

**Comment by satya164** [comment]
Please check the latest docs: https://reactnavigation.org/docs/en/getting-started.html

**Comment by mrigo** [comment]
Following the latest docs works for iOS with react-native run-android but for Android with react-native run-android I've got this:

```
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
/Users/Mattia/Documents/Projects/Efesto/Maikii/Faba/Faba/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerEvent.java:3: error: package android.support.v4.util does not exist
import android.support.v4.util.Pools;
                              ^
/Users/Mattia/Documents/Projects/Efesto/Maikii/Faba/Faba/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerEvent.java:19: error: package Pools does not exist
  private static final Pools.SynchronizedPool<RNGestureHandlerEvent> EVENTS_POOL =
                            ^
/Users/Mattia/Documents/Projects/Efesto/Maikii/Faba/Faba/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerStateChangeEvent.java:3: error: package android.support.v4.util does not exist
import android.support.v4.util.Pools;
                              ^
/Users/Mattia/Documents/Projects/Efesto/Maikii/Faba/Faba/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerStateChangeEvent.java:19: error: package Pools does not exist
  private static final Pools.SynchronizedPool<RNGestureHandlerStateChangeEvent> EVENTS_POOL =
                            ^
/Users/Mattia/Documents/Projects/Efesto/Maikii/Faba/Faba/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerEvent.java:20: error: package Pools does not exist
          new Pools.SynchronizedPool<>(TOUCH_EVENTS_POOL_SIZE);
                   ^
/Users/Mattia/Documents/Projects/Efesto/Maikii/Faba/Faba/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerStateChangeEvent.java:20: error: package Pools does not exist
          new Pools.SynchronizedPool<>(TOUCH_EVENTS_POOL_SIZE);
                   ^
Note: /Users/Mattia/Documents/Projects/Efesto/Maikii/Faba/Faba/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
6 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-gesture-handler:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

    at checkExecSyncError (child_process.js:601:13)
    at execFileSync (child_process.js:621:13)
    at runOnAllDevices (/Users/Mattia/Documents/Projects/Efesto/Maikii/Faba/Faba/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:75:39)
    at buildAndRun (/Users/Mattia/Documents/Projects/Efesto/Maikii/Faba/Faba/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:137:41)
    at then.result (/Users/Mattia/Documents/Projects/Efesto/Maikii/Faba/Faba/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:103:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

I've clean the project with ./android/gradlew clean and re-run the project but nothing...
Thanks!

**Comment by mrigo** [comment]
Sorry
```
rm -rf node_modules
npm i
```
and all works!

Thanks!

**Comment by bailer** [comment]
> Please check the latest docs: https://reactnavigation.org/docs/en/getting-started.html

Not enough for it to work on iOS. I had to manually add this to the Podfile `pod 'RNGestureHandler', :podspec => '../node_modules/react-native-gesture-handler/RNGestureHandler.podspec'` and then run `pod install` for it to work. This was on a totally fresh react-native project for RN 0.60
