### ISSUE TITLE
[ANDROID ONLY] Application crash when navigate from child to parent view

### ISSUE THREAD

**Issue by jb82240** [react-navigation/react-navigation#6096]
### Current Behavior

 I'm facing an issue with my react-native app on Android devices (prod and emulators). I have a home stack where I have many routes: for display events, display details of one events, and login, signup and a last one to fill extra infos after signup. 
My issue is when I go to my home page -> click an event for details ->  register me -> enter personal details. Then I navigate to the page with events details, I have this bug which crash my app:

`
 E/unknown:ReactNative: Exception in native call
    com.facebook.react.uimanager.IllegalViewOperationException: Trying to remove a view index above child count 6 view tag: 209
     detail: View tag:209
      children(6): [
    14825,14855,14337,14867,14879,14893,
     ],
      indicesToRemove(1): [
    6,
     ],
      tagsToDelete(1): [
    14409,
     ]
        at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:389)
        at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:227)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:917)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1025)
`

With Android studio I saw that the unknown tag is link to my home page where I display events. With the layout inspector I see there are many view that disappears. Have you ever see this bug? Moreover is really just with Android. I have any issues with iOS.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  "^3.0.0"
| react-native     | "0.59.9"
| node             | "v10.13.0"
| yarn      | "1.15.2"

**Comment by matthamil** [comment]
Hello! Can you create a reproducible example in a public GitHub repo or as a [Snack](https://snack.expo.io)? Code snippets are great, but a cloneable repo that has only the parts necessary to reproduce your issue is even better. Thanks!

**Comment by matthamil** [comment]
Closing due to inactivity

**Comment by jb82240** [comment]
I find why this issue appear. If you are on android and use radio buttons, go to your node_modules and in the radio button library find UIManager. Then, comment the "experimental" feature which use UIManager only for Android devices and check. Finally, two choices: make your own component without this 'feature' or in your ComponentDidMount disable this feature manually. The solution is here: https://github.com/facebook/react-native/issues/13984#issuecomment-343826572
