### ISSUE TITLE
Error: While trying to resolve module `react-navigation-drawer`

### ISSUE THREAD

**Issue by rochapablo** [react-navigation/react-navigation#6219]
After upgrade to 3.12.1, it stops run.

---

### Current Behavior

```
error: bundling failed: Error: While trying to resolve module `react-navigation-drawer` from file `my-app/node_modules/react-navigation/src/react-navigation.js`, the package `my-app/node_modules/react-navigation-drawer/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`my-app/node_modules/react-navigation-drawer/src/index.js`. Indeed, none of these files exist:

  * `my-app/node_modules/react-navigation-drawer/src/index.js(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
  * `my-app/node_modules/react-navigation-drawer/src/index.js/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
    at ResolutionRequest.resolveDependency (my-app/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:65:15)
    at DependencyGraph.resolveDependency (my-app/node_modules/metro/src/node-haste/DependencyGraph.js:283:16)
    at Object.resolve (my-app/node_modules/metro/src/lib/transformHelpers.js:264:42)
    at dependencies.map.result (my-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:399:31)
    at Array.map (<anonymous>)
    at resolveDependencies (my-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:18)
    at my-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:269:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (my-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
    at _next (my-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:107:9)
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.12.1
| react-native     | 0.60.5
| node             | 10.15.0
| npm or yarn      | 6.10.3 (npm)

**Comment by rochapablo** [comment]
Hey! Yeh, just give me some time.
