### ISSUE TITLE
[Android] react native 0.60.5 - Expect view tag to be set for com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView

### ISSUE THREAD

**Issue by mrigo** [react-navigation/react-navigation#6302]
### Current Behavior

This is the error I have:

```java
2019-09-16 12:23:01.960 15524-15651/com.maikii.myfaba E/GooglePlayServicesUtil: The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.
2019-09-16 12:23:09.534 15524-15524/com.maikii.myfaba E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.maikii.myfaba, PID: 15524
    java.lang.RuntimeException: java.lang.IllegalStateException: Expect view tag to be set for com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView{90683fa V.E...... ......ID 0,0-1080,1731}
        at com.facebook.react.bridge.ReactContext.handleException(ReactContext.java:335)
        at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:26)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

### Expected Behavior

No compile errors.

### How to reproduce

- create new app no expo
- install react native 0.60.5
- install react navigation 4.0.0
- install react native gesture handler 1.4.1
- react-native run-android

I've tried all other solutions but nothing...
clean, rebuild, autolinking, manual linking, jetify, nothing works...

I'm still experiencing this issue and always getting

```
Expect view tag to be set for com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView
```

### Your Environment

my package:
```javascript
"react": "16.8.6",
"react-native": "0.60.5",
"react-native-gesture-handler": "^1.4.1",
"react-native-reanimated": "^1.2.0",
"react-navigation": "^4.0.0",
```
and

```javascript
"postinstall": "npx jetify"
```

thanks for any helps, I've been stuck for days :(

**Comment by satya164** [comment]
Please open an issue in gesture-handler repo since it's bug in that library https://github.com/kmagiera/react-native-gesture-handler

**Comment by mrigo** [comment]
I've open it but had no response :'( I'm stuck, I don't know what to do :(
