### ISSUE TITLE
How to deal with NavigationEvents when testing with JestJs?

### ISSUE THREAD

**Issue by medmo7** [react-navigation/react-navigation#6542]
### Current Behavior
I'm having some troubles Jest testing a component which uses `import {NavigationEvents} from 'react-navigation'
`
this is the part of the component where i use it:

```
render() {
    const spinner = this.state.isLoading ? (
      <ActivityIndicator size="large" />
    ) : null;
    return (
      <ScrollView 
        style={styles.container} 
        keyboardDismissMode="on-drag"
        testID='SettingContainer'>
        <NavigationEvents
          onWillBlur={payload =>
            locationGetter.checkLocationData(
              payload,
              'Settings',
              this.props.t,
              this.props.location,
              'getPrayerPage',
            )
          }
        />
```
Now when i run this basic test :

```
import 'react-native';
import React from 'react';
import renderer from 'react-test-renderer';
import {I18nextProvider} from 'react-i18next';
import i18n from 'config/i18nForTest';
import {Settings} from 'containers/Settings'; // to get redux connected component import Setting without {}
// import configureStore from 'redux-mock-store';
// import { Provider } from 'react-redux';

// const mockStore = configureStore([]);
// const store = mockStore({ contacts: [ ] });
it('Does Settings renders correctly?', () => {
  const tree = renderer
    .create(
      <Settings t={key => key}  />,
    )
    .toJSON();
  expect(tree).toMatchSnapshot();
});
```
i get this error : 
```
    Invariant Violation: withNavigation can only be used on a view hierarchy of a navigator. The wrapped component is unable to get access to navigation from props or context.

      at React (node_modules/@react-navigation/core/lib/commonjs/utils/invariant.js:45:11)
      at node_modules/@react-navigation/core/lib/commonjs/views/withNavigation.js:10:41
      at updateContextConsumer (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7275:19)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7441:14)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10138:12)
      at workLoop (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10170:24)
      at renderRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10256:7)
      at performWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11121:7)
      at performWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11033:7)
      at performSyncWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11007:3)

Test Suites: 1 failed, 1 passed, 2 total
Tests:       1 failed, 3 passed, 4 total
Snapshots:   3 passed, 3 total
Time:        2.083s
Ran all test suites.
  console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8060
    The above error occurred in the <Context.Consumer> component:
        in withNavigation(NavigationEvents) (at Settings.js:116)
        in View (created by View)
        in View (at ScrollViewMock.js:29)
        in RCTScrollView (created by _class)
        in _class (at ScrollViewMock.js:27)
        in ScrollViewMock (at Settings.js:112)
        in Settings (at setting.test.js:21
) 

```

 Jest config in package.json:

 ```
"jest": {
    "verbose":true,
    "setupFiles": ["<rootDir>/jest.setup.js"],
    "preset": "react-native",
    "testMatch": [
      "<rootDir>/tests/**/*.test.js?(x)",
      "<rootDir>/src/**/*.test.js"
    ],
    "transformIgnorePatterns": ["node_modules/(?!(jest-)?react-native|react-navigation|@react-native-community|@react-navigation/.*)" 
    ],
    "transform": {
      "^.+\\.(js)$": "<rootDir>/node_modules/react-native/jest/preprocessor.js"
    }
  }
```

### Expected Behavior
![image](https://user-images.githubusercontent.com/32428883/71663119-3bae4180-2d54-11ea-9f39-17346fa789cc.png)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | "4.0.0"
| react-native     | "0.59.9"
| node             | v12.9.0
| npm or yarn      | 6.10.3

**Comment by medmo7** [comment]
I'm adding an update to my question as i have now a different error after i added a mock to react-navigation.
the mock i used is like this:

```
const navigation = jest.genMockFromModule('react-navigation');

module.exports = navigation;
```

and the new error is like this:

```
`createNavigationContainer()` has been removed. Use `createAppContainer()` instead. You can also import createAppContainer directly from `@react-navigation/native`.

      1 | 
    > 2 | const navigation = jest.genMockFromModule('react-navigation');
        |                       ^
      3 | 
      4 | module.exports = navigation;
      5 | 

      at Object.get createNavigationContainer [as createNavigationContainer] (node_modules/react-navigation/src/deprecations.js:11:11)
      at Object.get [as createNavigationContainer] (node_modules/react-navigation/src/react-navigation.js:4:249)
          at Array.forEach (<anonymous>)
      at Object.<anonymous> (__mocks__/react-navigation.js:2:23
```)

Any help would be greatly appreciated. Thanks!

**Comment by medmo7** [comment]
If someone have the same problem, for me the solution was to add this mock jest.setup.js

```
jest.mock('react-navigation', () =>({
  NavigationEvents: 'mockNavigationEvents',
}))
```

**Comment by mittalprayag25** [comment]
> If someone have the same problem, for me the solution was to add this mock jest.setup.js
> 
> ```
> jest.mock('react-navigation', () =>({
>   NavigationEvents: 'mockNavigationEvents',
> }))
> ```

@medmo7  Perfect. Just need to add in your test case ...

**Comment by medmo7** [comment]
@mittalprayag25  i used it in jest.setup.js as i need to mock if for other test files.
