### ISSUE TITLE
Android: crash on pop/goBack

### ISSUE THREAD

**Issue by Hirbod** [react-navigation/react-navigation#6767]
Newest version, ejected from expo, Alpha Screen Version 22.
Cross-Posting, since I don't know if the error is caused by screens or navigation-ex. Please close if not related to this package.

https://github.com/kmagiera/react-native-screens/issues/266

When I have a TabStack, and the screen implements another native Stack with 2 screens, following both screens and pressing backbutton 2 times to return to my main tab, the app crashes.

```bash
Process: com.nummernschild, PID: 8759
01-05 20:56:32.695  8759  8759 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.appcompat.app.AppCompatActivity.setSupportActionBar(androidx.appcompat.widget.Toolbar)' on a null object reference
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at com.swmansion.rnscreens.ScreenStackHeaderConfig.onUpdate(ScreenStackHeaderConfig.java:135)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at com.swmansion.rnscreens.ScreenStackHeaderConfig.onAttachedToWindow(ScreenStackHeaderConfig.java:70)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at android.view.View.dispatchAttachedToWindow(View.java:19553)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3430)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at android.view.ViewGroup.addViewInner(ViewGroup.java:5149)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at android.view.ViewGroup.addView(ViewGroup.java:4935)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at android.view.ViewGroup.addView(ViewGroup.java:4875)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at android.view.ViewGroup.addView(ViewGroup.java:4848)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:887)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.addAddedFragments(FragmentManagerImpl.java:2100)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1874)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1830)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
01-05 20:56:32.695  8759  8759 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

```tsx

            <NavigationNativeContainer>
                <Root.Navigator
                    screenOptions={{
                        headerShown: false,
                        headerTintColor: 'white',
                        headerLargeTitle: true,
                        headerStyle: {backgroundColor: '#b7cd23'},
                    }}
                >
                    {
                        props.app.authToken && true && props.app.authToken !== "" ? (
                            <>
                                <Stack.Screen name="Home" component={tabStack} />
                                <Stack.Screen options={{
                                    presentation: "push",
                                    headerShown: true,
                                    title: "Chat",
                                    headerLargeTitle: false
                                }} name="Message" component={Message}/>
                                <Stack.Screen options={{
                                    presentation: "modal",
                                    headerShown: false,
                                    title: "User",
                                    headerLargeTitle: false
                                }} name="User" component={User}/>
                            </>
                        ) : (
                            <Stack.Screen name="Login" component={Login} />
                        )
                    }
                </Root.Navigator>
            </NavigationNativeContainer>
```

...

```tsx
                <Tab.Screen
                    name="Chats"
                    component={chatStack}
                    options={{
                        tabBarBadge: props.app.user.plates.length && props.app.unreadMessages > 0 ? props.app.unreadMessages : false,
                        tabBarLabel: 'Chats',
                        tabBarIcon: ({color, size = 25}) => (
                            <Entypo style={{height: 30, width: 30}} name="chat" color={color} size={size}/>
                        ),
                    }}
                />
```

```tsx
const chatStack = () => {
    const Stack = createNativeStackNavigator();
    return React.useMemo(() => {
        return (
            <Stack.Navigator
                screenOptions={{
                    headerShown: true,
                    headerTintColor: 'white',
                    headerLargeTitle: true,
                    headerStyle: {backgroundColor: '#b7cd23'},
                }}
            >
                <Stack.Screen name="Messages" options={{title: "Chats"}} component={Messages}/>
            </Stack.Navigator>
        );
    },[]);
};
```

Inside the ChatStack, I open another modal which is defined in the rootStack. This one causes the crash.

**Comment by satya164** [comment]
Hey, native-stack has been moved to [software-mansion/react-native-screens](https://github.com/software-mansion/react-native-screens). Please track the issue here: https://github.com/software-mansion/react-native-screens/issues/366
