### ISSUE TITLE
Jest tests failing on cannot read property 'propTypes' of undefined

### ISSUE THREAD

**Issue by bartolkaruza** [react-navigation/react-navigation#6783]
### Current Behavior
Running yarn test fails on undefined value

```
 FAIL  __tests__/App-test.js
  ● Test suite failed to run

    TypeError: Cannot read property 'propTypes' of undefined

      at propTypes (node_modules/react-native/Libraries/Animated/src/createAnimatedComponent.js:178:31)
      at Object.oldCreate [as createAnimatedComponent] (node_modules/react-native/jest/setup.js:143:23)
      at Object.BaseButton (node_modules/@react-navigation/stack/lib/commonjs/views/BorderlessButton.tsx:5:61)
      at Object.<anonymous> (node_modules/@react-navigation/stack/lib/commonjs/views/TouchableItem.tsx:19:1)
```

### Expected Behavior
Passing test

### How to reproduce

Clean test project ```react-native init test --version 0.61.0-rc.2``` 

Install peer deps:
```
yarn add react-native-gesture-handler
yarn add react-native-screens
yarn add react-native-reanimated
yarn add @react-native-community/masked-view
```

mock masked-view (__mocks__/@react-native-community/masked-view.js)
```
import {View} from 'react-native';

export default View;
```

and react-native-gesture-handler (__mocks__/react-native-gesture-handler.js)
```
export default {
  attachGestureHandler: () => {},
  createGestureHandler: () => {},
  dropGestureHandler: () => {},
  updateGestureHandler: () => {},
  Direction: {
    RIGHT: 1,
    LEFT: 2,
    UP: 4,
    DOWN: 8,
  },
  State: {BEGAN: 'BEGAN', FAILED: 'FAILED', ACTIVE: 'ACTIVE', END: 'END'},
};
```

```App.js```
```
import React from 'react';
import { View } from 'react-native';
import { NavigationNativeContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';
import renderer from 'react-test-renderer';

const Stack = createStackNavigator();

function ScreenOne() { 
   return <View />
}

function ScreenTwo() {
  return <View />
}

function App() {
  return (
    <NavigationNativeContainer>
      <Stack.Navigator headerMode='none' initialRouteName='RouteOne'>
        <Stack.Screen name='RouteOne' component={ScreenOne} />
        <Stack.Screen name='RouteTwo' component={ScreenTwo} />
      </Stack.Navigator>
    </NavigationNativeContainer>
  );
}
```

```App-test.js```
```
import 'react-native';
import React from 'react';
import App from '../App';
import renderer from 'react-test-renderer';

it('renders correctly', () => {
  renderer.create(<App />);
});
```

### Your Environment

| software         | version
| ---------------- | -------
 ```
"@react-navigation/core": "^5.0.0-alpha.8",
"@react-navigation/native": "^5.0.0-alpha.7",
"@react-navigation/stack": "^5.0.0-alpha.15",
"react-test-renderer": "16.9.0",
"react-native": "0.61.0-rc.2",
 "jest": "^24.9.0",
```

**Comment by bogrees** [comment]
> [BorderlessButton](https://github.com/react-navigation/navigation-ex/blob/master/packages/stack/src/views/BorderlessButton.tsx) uses RNGH `BaseButton`, so you have to mock out that as well.
> 
> And beware that RNGH uses named exports, so the default export won't work.
> 
> ```
> // __mocks__/react-native-gesture-handler.js
> import { TouchableWithoutFeedback } from 'react-native';
> 
> export const BaseButton = TouchableWithoutFeedback;
> export const BorderlessButton = TouchableWithoutFeedback;
> // ... other mocks
> ```

Using this mock fixed the issue referred to by the OP.
