### ISSUE TITLE
error While trying to resolve module @react-navigation/native

### ISSUE THREAD

**Issue by felix-voicehub** [react-navigation/react-navigation#7124]
**Current Behavior**

Getting this in my build log:

```
error While trying to resolve module `@react-navigation/native` from file `/Users/runner/runners/2.165.0/work/1/s/node_modules/react-navigation/src/index.js`, the package `/Users/runner/runners/2.165.0/work/1/s/node_modules/@react-navigation/native/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/runner/runners/2.165.0/work/1/s/node_modules/@react-navigation/native/lib/module/index.js`. Indeed, none of these files exist:

  * /Users/runner/runners/2.165.0/work/1/s/node_modules/@react-navigation/native/lib/module/index.js(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.svg|.native.svg|.svg)
  * /Users/runner/runners/2.165.0/work/1/s/node_modules/@react-navigation/native/lib/module/index.js/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.svg|.native.svg|.svg). Run CLI with --verbose flag for more details.
Error: While trying to resolve module `@react-navigation/native` from file `/Users/runner/runners/2.165.0/work/1/s/node_modules/react-navigation/src/index.js`, the package `/Users/runner/runners/2.165.0/work/1/s/node_modules/@react-navigation/native/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/runner/runners/2.165.0/work/1/s/node_modules/@react-navigation/native/lib/module/index.js`. Indeed, none of these files exist:

  * /Users/runner/runners/2.165.0/work/1/s/node_modules/@react-navigation/native/lib/module/index.js(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.svg|.native.svg|.svg)
  * /Users/runner/runners/2.165.0/work/1/s/node_modules/@react-navigation/native/lib/module/index.js/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.svg|.native.svg|.svg)
    at ResolutionRequest.resolveDependency (/Users/runner/runners/2.165.0/work/1/s/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:65:15)
    at DependencyGraph.resolveDependency (/Users/runner/runners/2.165.0/work/1/s/node_modules/metro/src/node-haste/DependencyGraph.js:282:16)
    at Object.resolve (/Users/runner/runners/2.165.0/work/1/s/node_modules/metro/src/lib/transformHelpers.js:267:42)
    at /Users/runner/runners/2.165.0/work/1/s/node_modules/metro/src/DeltaBundler/traverseDependencies.js:426:31
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/runner/runners/2.165.0/work/1/s/node_modules/metro/src/DeltaBundler/traverseDependencies.js:423:18)
    at /Users/runner/runners/2.165.0/work/1/s/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/runner/runners/2.165.0/work/1/s/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
    at _next (/Users/runner/runners/2.165.0/work/1/s/node_modules/metro/src/DeltaBundler/traverseDependencies.js:107:9)
```

**Expected Behavior**:
This should be there.

**How to reproduce**

I am not sure yet.

**Your Environment**

"react-navigation": "^4.1.1",

**Comment by satya164** [comment]
Fixed in 3.7.1

**Comment by felix-voicehub** [comment]
@satya164 I have tried 4.2.0 and it still persists.

**Comment by satya164** [comment]
Delete your lockfile and retry

**Comment by felix-voicehub** [comment]
@satya164 This is on Microsoft AppCenter. It does a clean build.

**Comment by satya164** [comment]
You don't have a lockfile? I'll check soon but you should have a lockfile to avoid updated breaking your build.

**Comment by ilmatic** [comment]
I am having this exact same issue; inspected node_modules and there is no `lib/module/index.js`, only a `lib/commonjs/index.js`.

**Comment by satya164** [comment]
Can you try again with 3.7.2?

**Comment by jasonbodily** [comment]
Same as other complaints. Tried cache resets, restarts, verified metro configs—nothing is helping. Looks like an expected file just isn't there.

**Comment by satya164** [comment]
Please try again after deleting lockfile. It should install 3.7.2

**Comment by felix-voicehub** [comment]
Btw, this just appeared today out of nowhere. Yesterday my builds were working. Didn’t change anything regarding this lib.

**Comment by satya164** [comment]
@felix-voicehub it's broken publish, but this is why you should commit lockfiles to avoid your builds from breaking

**Comment by Lizhooh** [comment]
This problem still exists: 
npm: 6.10.3
@react-navigation/native: 5.5.0
win10
