### ISSUE TITLE
Exception when using with react-native-screens

### ISSUE THREAD

**Issue by evert-smit** [react-navigation/react-navigation#7242]
Hi - thanks a lot for creating this!

I'm getting the following exception when using the animated SwitchNavigator together with react-native-screens.

The exception doesn't occur when I remove the useScreens(); call in my app, so there must be something in the combination between animated-switch and react-native-screens that causes this.

```
java.lang.IllegalStateException: ScreenContainer is not attached under ReactRootView
        at com.swmansion.rnscreens.ScreenContainer.findRootFragmentActivity(ScreenContainer.java:95)
        at com.swmansion.rnscreens.ScreenContainer.getOrCreateTransaction(ScreenContainer.java:112)
        at com.swmansion.rnscreens.ScreenContainer.detachScreen(ScreenContainer.java:138)
        at com.swmansion.rnscreens.ScreenContainer.updateIfNeeded(ScreenContainer.java:178)
        at com.swmansion.rnscreens.ScreenContainer.onAttachedToWindow(ScreenContainer.java:150)
        at android.view.View.dispatchAttachedToWindow(View.java:18347)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3397)
        at android.view.ViewGroup.addViewInner(ViewGroup.java:5077)
        at android.view.ViewGroup.addView(ViewGroup.java:4865)
        at android.view.ViewGroup.addView(ViewGroup.java:4805)
        at android.view.ViewGroup.addView(ViewGroup.java:4778)
        at android.view.ViewOverlay$OverlayViewGroup.add(ViewOverlay.java:205)
        at android.view.ViewGroupOverlay.add(ViewGroupOverlay.java:72)
        at android.support.transition.ViewGroupOverlayApi18.add(ViewGroupOverlayApi18.java:53)
        at android.support.transition.Visibility.onDisappear(Visibility.java:405)
        at android.support.transition.Visibility.createAnimator(Visibility.java:253)
        at android.support.transition.Transition.createAnimators(Transition.java:744)
        at android.support.transition.TransitionSet.createAnimators(TransitionSet.java:470)
        at android.support.transition.Transition.playTransition(Transition.java:1817)
        at android.support.transition.TransitionManager$MultiListener.onPreDraw(TransitionManager.java:295)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:977)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2474)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:696)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

Are the two libraries incompatible? Or is there something to be done to fix/work around this exception?

**Comment by annjawn** [comment]
Seems to be working fine for me on both Android and iOS.

```js
const appNavigator = createAnimatedSwitchNavigator(
  {
    Main:  {
      screen: Main
    },
    CustomerContainer: {
      screen: CustomerContainer 
    }
  },
  {
    initialRouteName: 'Main',
    transition: (
      <Transition.Together>
        <Transition.Out
          type="fade"
          durationMs={200}
          interpolation="easeIn"
        />
        <Transition.In type="fade" durationMs={500} />
      </Transition.Together>
    )
  }
);
```

**Comment by reimertz** [comment]
Confirmed on android that `<Transition.Out type="fade" durationMs={200} interpolation="easeIn" />` cause a crash.

**Comment by eric-ml** [comment]
This is still happening. Can we reopen this?
Packages version:
```
"react-navigation": "4.4.3",
"react-navigation-animated-switch": "0.6.3",
"react-navigation-drawer": "1.4.0",
"react-navigation-stack": "2.10.2",
"react-navigation-tabs": "2.10.1",
```

**Comment by joel-bitar** [comment]
This is still happening.
Seems to be another issue for the same thing over at react-native-gesture-handler https://github.com/software-mansion/react-native-gesture-handler/issues/950
I can confirm that I get the issue on Android with the following versions:

    "react-native": "0.60.5",
    "react-navigation": "4.4.3",
    "react-navigation-animated-switch": "0.6.3",
    "react-navigation-stack": "2.10.2",
    "react-navigation-tabs": "2.10.1",
    "react-native-gesture-handler": "1.9.0"

Someone mentioned it only happens if you switch away from a StackNavigator. We have this use-case too, and I can confirm it doesn't crash if I put the view that I switch away from directly in the StackNavigator.

Also as it was posted previously it doesn't crash if you remove the Out animation. As they mention at react-native-gesture-handler It doesn't crash if you downgrade react-native-gesture-handler to 1.4.0 (but I do get some weird graphical glitches).

**Comment by cristiano-linvix** [comment]
Im currently with this error, but the navigator is inside of modal?
