### ISSUE TITLE
React Navigation 4 + tab navigation doesn't work with Jest

### ISSUE THREAD

**Issue by FrickenHamster** [react-navigation/react-navigation#7286]
### Current behaviour

When I upgraded to react-navigation 4 from 3, and switched to using the react-navigation-tabs, tests break when rendering TabNavigator.
I get the error
`Invariant Violation: Unable to locate attached view in the native tree

      at invariant (node_modules/fbjs/lib/invariant.js:42:15)
      at AnimatedProps.setNativeView (node_modules/react-native-reanimated/src/core/AnimatedProps.js:82:5)
      at AnimatedComponent.setNativeView [as componentDidMount] (node_modules/react-native-reanimated/src/createAnimatedComponent.js:49:27)
      at commitLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9432:22)
      at commitAllLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10829:7)
      at Object.invokeGuardedCallbackImpl (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2302:10)
      at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2480:31)
      at commitRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11041:7)
      at node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12492:5
      at Object.unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:255:12)`

### Expected behaviour

Test to correctly work as before

### Code sample

I made a new expo project to narrow down and test the behavior

Here is my testfile

```
import { createAppContainer, createSwitchNavigator } from 'react-navigation'

import TestRenderer from "react-test-renderer";
import React from "react";
import { View } from "react-native";
import { createBottomTabNavigator } from "react-navigation-tabs";

const HamFirst = (props) => {
  props.navigation.navigate('Auth')
  console.log('nani')
  return <View>
    {/*<Redirect to="Main" navigation={props.navigation} />*/}
  </View>
}

const HamSecond = () => {
  console.log('seconds')
  return <View>
  </View>
}

const TabStack = createAppContainer(createBottomTabNavigator({
  Auth: HamFirst,
  Main: HamSecond,
}, {
  initialRouteName: 'Auth'
}))


const HamNavigator = createAppContainer(
  createSwitchNavigator(
    {
      Auth: HamFirst,
      Main: HamSecond,
    },
    {
      initialRouteName: 'Auth',
    },
  ),
)



describe('Hamster', () => {
  let cache
  let directorTimelineScreen
  let rendered

  beforeEach(async () => {
    rendered = TestRenderer.create(
      <TabStack />
    )
  })

  it('reeeee', () => {

  })

})
```
### What have you tried

Narrowed down the issue to tab navigator and test the component specifically in a new expo project

### Your Environment

| software              | version
| --------------------- | -------
| jest-expo      | 35.0.0
| react-native          |  rn verison for expo 35
| react-navigation-tabs | 2.5.6
| node                  |  12.11.0
| npm or yarn           | yarn

Thanks

**Comment by satya164** [comment]
https://reactnavigation.org/docs/testing#mocking-native-modules
