### ISSUE TITLE
[next] Can't test with jest:  Unable to locate attached view in the native tree

### ISSUE THREAD

**Issue by kopax** [react-navigation/react-navigation#7496]
**Current Behavior**

I have my test failing as soon as I use the stack navigator

**Expected Behavior**

I expect my test to pass, instead, I have:

```
t SafeAreaProviderCompat.tsx:34)\n' +
          '    in SafeAreaProviderCompat (at DrawerView.tsx:168)\n' +
          '    in DrawerView (at createDrawerNavigator.tsx:44)\n' +
          '    in DrawerNavigator (created by AppCore)\n' +
          '    in ErrorBoundary (created by AppCore)\n' +
          '    in ThemeProvider (at Provider.tsx:21)\n' +
          '    in View (created by View)\n' +
          '    in View (at PortalHost.tsx:128)\n' +
          '    in Portal.Host (at Provider.tsx:17)\n' +
          '    in Provider (created by ConnectedPaperProvider)\n' +
          '    in ConnectedPaperProvider (created by ConnectFunction)\n' +
          '    in ConnectFunction (created by AppCore)\n' +
          '    in PersistGate (created by AppCore)\n' +
          '    in Provider (created by AppCore)\n' +
          '    in AppContextProvider (created by AppCore)\n' +
          '    in EnsureSingleNavigator (at NavigationContainer.tsx:265)\n' +
          '    in ForwardRef(NavigationContainer) (at NavigationNativeContainer.tsx:39)\n' +
          '    in ThemeProvider (at NavigationNativeContainer.tsx:38)\n' +
          '    in ForwardRef(NativeContainer) (created by AppCore)\n' +
          '    in AppCore\n' +
          '    in Unknown'
      }
    console.log src/core/ErrorBoundary.js:16
      Invariant Violation: Unable to locate attached view in the native tree
        name: 'Invariant Violation',
        framesToPop: 1
      } {
        componentStack: '\n' +
          '    in AnimatedComponent (at Drawer.tsx:612)\n' +
          '    in View (created by View)\n' +
          '    in View (created by AnimatedComponent)\n' +
          '    in AnimatedComponent (at Drawer.tsx:559)\n' +
          '    in PanGestureHandler (at Drawer.tsx:549)\n' +
          '    in DrawerView (at DrawerView.tsx:170)\n' +
          '    in RNCSafeAreaView (created by RNCSafeAreaView)\n' +
          '    in RNCSafeAreaView (at src/index.tsx:26)\n' +
          '    in SafeAreaProvider (at SafeAreaProviderCompat.tsx:34)\n' +
          '    in SafeAreaProviderCompat (at DrawerView.tsx:168)\n' +
          '    in DrawerView (at createDrawerNavigator.tsx:44)\n' +
          '    in DrawerNavigator (created by AppCore)\n' +
          '    in ErrorBoundary (created by AppCore)\n' +
          '    in ThemeProvider (at Provider.tsx:21)\n' +
          '    in View (created by View)\n' +
          '    in View (at PortalHost.tsx:128)\n' +
          '    in Portal.Host (at Provider.tsx:17)\n' +
          '    in Provider (created by ConnectedPaperProvider)\n' +
          '    in ConnectedPaperProvider (created by ConnectFunction)\n' +
          '    in ConnectFunction (created by AppCore)\n' +
          '    in PersistGate (created by AppCore)\n' +
          '    in Provider (created by AppCore)\n' +
          '    in AppContextProvider (created by AppCore)\n' +
          '    in EnsureSingleNavigator (at NavigationContainer.tsx:265)\n' +
          '    in ForwardRef(NavigationContainer) (at NavigationNativeContainer.tsx:39)\n' +
          '    in ThemeProvider (at NavigationNativeContainer.tsx:38)\n' +
          '    in ForwardRef(NativeContainer) (created by AppCore)\n' +
          '    in AppCore\n' +
          '    in Unknown'
      }
    console.log src/core/ErrorBoundary.js:16
      Invariant Violation: Unable to locate attached view in the native tree
        framesToPop: 1
      } {
        componentStack: '\n' +
          '    in AnimatedComponent (at Drawer.tsx:559)\n' +
          '    in PanGestureHandler (at Drawer.tsx:549)\n' +
          '    in DrawerView (at DrawerView.tsx:170)\n' +
          '    in RNCSafeAreaView (created by RNCSafeAreaView)\n' +
          '    in RNCSafeAreaView (at src/index.tsx:26)\n' +
          '    in SafeAreaProvider (at SafeAreaProviderCompat.tsx:34)\n' +
          '    in SafeAreaProviderCompat (at DrawerView.tsx:168)\n' +
          '    in DrawerView (at createDrawerNavigator.tsx:44)\n' +
          '    in DrawerNavigator (created by AppCore)\n' +
          '    in ErrorBoundary (created by AppCore)\n' +
          '    in ThemeProvider (at Provider.tsx:21)\n' +
          '    in View (created by View)\n' +
          '    in View (at PortalHost.tsx:128)\n' +
          '    in Portal.Host (at Provider.tsx:17)\n' +
          '    in Provider (created by ConnectedPaperProvider)\n' +
          '    in ConnectedPaperProvider (created by ConnectFunction)\n' +
          '    in ConnectFunction (created by AppCore)\n' +
          '    in PersistGate (created by AppCore)\n' +
          '    in Provider (created by AppCore)\n' +
          '    in AppContextProvider (created by AppCore)\n' +
          '    in EnsureSingleNavigator (at NavigationContainer.tsx:265)\n' +
          '    in ForwardRef(NavigationContainer) (at NavigationNativeContainer.tsx:39)\n' +
          '    in ThemeProvider (at NavigationNativeContainer.tsx:38)\n' +
          '    in ForwardRef(NativeContainer) (created by AppCore)\n' +
          '    in AppCore\n' +
          '    in Unknown'
      }
    console.error node_modules/react-native/Libraries/YellowBox/YellowBox.js:63
      The above error occurred in the <AnimatedComponent> component:
          in AnimatedComponent (at Drawer.tsx:559)
          in PanGestureHandler (at Drawer.tsx:549)
          in DrawerView (at DrawerView.tsx:170)
          in RNCSafeAreaView (created by RNCSafeAreaView)
          in RNCSafeAreaView (at src/index.tsx:26)
          in SafeAreaProvider (at SafeAreaProviderCompat.tsx:34)
          in SafeAreaProviderCompat (at DrawerView.tsx:168)
          in DrawerView (at createDrawerNavigator.tsx:44)
          in DrawerNavigator (created by AppCore)
          in ErrorBoundary (created by AppCore)
          in ThemeProvider (at Provider.tsx:21)
          in View (created by View)
          in View (at PortalHost.tsx:128)
          in Portal.Host (at Provider.tsx:17)
          in Provider (created by ConnectedPaperProvider)
          in ConnectedPaperProvider (created by ConnectFunction)
          in ConnectFunction (created by AppCore)
          in PersistGate (created by AppCore)
          in Provider (created by AppCore)
          in AppContextProvider (created by AppCore)
          in EnsureSingleNavigator (at NavigationContainer.tsx:265)
          in ForwardRef(NavigationContainer) (at NavigationNativeContainer.tsx:39)
          in ThemeProvider (at NavigationNativeContainer.tsx:38)
          in ForwardRef(NativeContainer) (created by AppCore)
          in AppCore
          in Unknown
      
      React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
    console.error node_modules/react-native/Libraries/YellowBox/YellowBox.js:63
      The above error occurred in the <AnimatedComponent> component:
          in AnimatedComponent (at Drawer.tsx:563)
          in View (created by View)
          in View (created by AnimatedComponent)
          in AnimatedComponent (at Drawer.tsx:559)
          in PanGestureHandler (at Drawer.tsx:549)
          in DrawerView (at DrawerView.tsx:170)
          in RNCSafeAreaView (created by RNCSafeAreaView)
          in RNCSafeAreaView (at src/index.tsx:26)
          in SafeAreaProvider (at SafeAreaProviderCompat.tsx:34)
          in SafeAreaProviderCompat (at DrawerView.tsx:168)
          in DrawerView (at createDrawerNavigator.tsx:44)
          in DrawerNavigator (created by AppCore)
          in ErrorBoundary (created by AppCore)
          in ThemeProvider (at Provider.tsx:21)
          in View (created by View)
          in View (at PortalHost.tsx:128)
          in Portal.Host (at Provider.tsx:17)
          in Provider (created by ConnectedPaperProvider)
          in ConnectedPaperProvider (created by ConnectFunction)
          in ConnectFunction (created by AppCore)
          in PersistGate (created by AppCore)
          in Provider (created by AppCore)
          in AppContextProvider (created by AppCore)
          in EnsureSingleNavigator (at NavigationContainer.tsx:265)
          in ForwardRef(NavigationContainer) (at NavigationNativeContainer.tsx:39)
          in ThemeProvider (at NavigationNativeContainer.tsx:38)
          in ForwardRef(NativeContainer) (created by AppCore)
          in AppCore
          in Unknown
      
      React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
    console.error node_modules/react-native/Libraries/YellowBox/YellowBox.js:63
      The above error occurred in the <AnimatedComponent> component:
          in AnimatedComponent (at Drawer.tsx:580)
          in TapGestureHandler (at Drawer.tsx:579)
          in View (created by View)
          in View (created by AnimatedComponent)
          in AnimatedComponent (at Drawer.tsx:563)
          in View (created by View)
          in View (created by AnimatedComponent)
          in AnimatedComponent (at Drawer.tsx:559)
          in PanGestureHandler (at Drawer.tsx:549)
          in DrawerView (at DrawerView.tsx:170)
          in RNCSafeAreaView (created by RNCSafeAreaView)
          in RNCSafeAreaView (at src/index.tsx:26)
          in SafeAreaProvider (at SafeAreaProviderCompat.tsx:34)
          in SafeAreaProviderCompat (at DrawerView.tsx:168)
          in DrawerView (at createDrawerNavigator.tsx:44)
          in DrawerNavigator (created by AppCore)
          in ErrorBoundary (created by AppCore)
          in ThemeProvider (at Provider.tsx:21)
          in View (created by View)
          in View (at PortalHost.tsx:128)
          in Portal.Host (at Provider.tsx:17)
          in Provider (created by ConnectedPaperProvider)
          in ConnectedPaperProvider (created by ConnectFunction)
          in ConnectFunction (created by AppCore)
          in PersistGate (created by AppCore)
          in Provider (created by AppCore)
          in AppContextProvider (created by AppCore)
          in EnsureSingleNavigator (at NavigationContainer.tsx:265)
          in ForwardRef(NavigationContainer) (at NavigationNativeContainer.tsx:39)
          in ThemeProvider (at NavigationNativeContainer.tsx:38)
          in ForwardRef(NativeContainer) (created by AppCore)
          in AppCore
          in Unknown
      
      React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
    console.error node_modules/react-native/Libraries/YellowBox/YellowBox.js:63
      The above error occurred in the <AnimatedComponent> component:
          in AnimatedComponent (at Drawer.tsx:612)
          in View (created by View)
          in View (created by AnimatedComponent)
          in AnimatedComponent (at Drawer.tsx:559)
          in PanGestureHandler (at Drawer.tsx:549)
          in DrawerView (at DrawerView.tsx:170)
          in RNCSafeAreaView (created by RNCSafeAreaView)
          in RNCSafeAreaView (at src/index.tsx:26)
          in SafeAreaProvider (at SafeAreaProviderCompat.tsx:34)
          in SafeAreaProviderCompat (at DrawerView.tsx:168)
          in DrawerView (at createDrawerNavigator.tsx:44)
          in DrawerNavigator (created by AppCore)
          in ErrorBoundary (created by AppCore)
          in ThemeProvider (at Provider.tsx:21)
          in View (created by View)
          in View (at PortalHost.tsx:128)
          in Portal.Host (at Provider.tsx:17)
          in Provider (created by ConnectedPaperProvider)
          in ConnectedPaperProvider (created by ConnectFunction)
          in ConnectFunction (created by AppCore)
          in PersistGate (created by AppCore)
          in Provider (created by AppCore)
          in AppContextProvider (created by AppCore)
          in EnsureSingleNavigator (at NavigationContainer.tsx:265)
          in ForwardRef(NavigationContainer) (at NavigationNativeContainer.tsx:39)
          in ThemeProvider (at NavigationNativeContainer.tsx:38)
          in ForwardRef(NativeContainer) (created by AppCore)
          in AppCore
          in Unknown
      
      React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
    console.log src/core/ErrorBoundary.js:16
      Invariant Violation: Unable to locate attached view in the native tree
          at invariant (/home/dka/workspace/git.kopaxgroup.com/momagroup/icimatin-native/node_modules/fbjs/lib/invariant.js:42:15)
          at AnimatedProps.__detach (/home/dka/workspace/git.kopaxgroup.com/momagroup/icimatin-native/node_modules/react-native-reanimated/src/core/AnimatedProps.js:64:5)
          at AnimatedComponent.componentWillUnmount (/home/dka/workspace/git.kopaxgroup.com/momagroup/icimatin-native/node_modules/react-native-reanimated/src/createAnimatedComponent.js:36:50)
          at callComponentWillUnmountWithTimer (/home/dka/workspace/git.kopaxgroup.com/momagroup/icimatin-native/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12011:12)
          at Object.invokeGuardedCallbackImpl (/home/dka/workspace/git.kopaxgroup.com/momagroup/icimatin-native/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11683:10)
          at invokeGuardedCallback (/home/dka/workspace/git.kopaxgroup.com/momagroup/icimatin-native/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11860:31)
          at safelyCallComponentWillUnmount (/home/dka/workspace/git.kopaxgroup.com/momagroup/icimatin-native/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12018:5)
          at commitUnmount (/home/dka/workspace/git.kopaxgroup.com/momagroup/icimatin-native/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12507:11)
          at commitNestedUnmounts (/home/dka/workspace/git.kopaxgroup.com/momagroup/icimatin-native/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12601:5)
          at unmountHostComponents (/home/dka/workspace/git.kopaxgroup.com/momagroup/icimatin-native/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12923:7) {
        name: 'Invariant Violation',
        framesToPop: 1
      } {
        componentStack: '\n' +
          '    in AnimatedComponent (at Drawer.tsx:559)\n' +
          '    in PanGestureHandler (at Drawer.tsx:549)\n' +
          '    in DrawerView (at DrawerView.tsx:170)\n' +
          '    in RNCSafeAreaView (created by RNCSafeAreaView)\n' +
          '    in RNCSafeAreaView (at src/index.tsx:26)\n' +
          '    in SafeAreaProvider (at SafeAreaProviderCompat.tsx:34)\n' +
          '    in SafeAreaProviderCompat (at DrawerView.tsx:168)\n' +
          '    in DrawerView (at createDrawerNavigator.tsx:44)\n' +
          '    in DrawerNavigator (created by AppCore)\n' +
          '    in ErrorBoundary (created by AppCore)\n' +
          '    in ThemeProvider (at Provider.tsx:21)\n' +
          '    in View (created by View)\n' +
          '    in View (at PortalHost.tsx:128)\n' +
          '    in Portal.Host (at Provider.tsx:17)\n' +
          '    in Provider (created by ConnectedPaperProvider)\n' +
          '    in ConnectedPaperProvider (created by ConnectFunction)\n' +
          '    in ConnectFunction (created by AppCore)\n' +
          '    in PersistGate (created by AppCore)\n' +
          '    in Provider (created by AppCore)\n' +
          '    in AppContextProvider (created by AppCore)\n' +
          '    in EnsureSingleNavigator (at NavigationContainer.tsx:265)\n' +
          '    in ForwardRef(NavigationContainer) (at NavigationNativeContainer.tsx:39)\n' +
          '    in ThemeProvider (at NavigationNativeContainer.tsx:38)\n' +
          '    in ForwardRef(NativeContainer) (created by AppCore)\n' +
          '    in AppCore\n' +
          '    in Unknown'
      }
```

**Comment by markybry** [comment]
If anyone else comes across this while creating tests in jest the react navigation testing with Jest docs are a good source of information. Please select the correct version of the docs.

https://reactnavigation.org/docs/5.x/testing
