### ISSUE TITLE
TypeError: Cannot read property 'light' of undefined

### ISSUE THREAD

**Issue by loic-lopez** [react-navigation/react-navigation#7541]
When using `jest.mock("react-navigation-drawer")`

An error is thrown:
```
● Test suite failed to run

    TypeError: Cannot read property 'light' of undefined

      at Object.DrawerNavigator (node_modules/react-navigation-drawer/lib/commonjs/navigators/createDrawerNavigator.tsx:62:7)
      at Object.<anonymous> (node_modules/react-navigation-drawer/lib/commonjs/index.tsx:19:1)
```

**Comment by jdnichollsc** [comment]
After a lot of issues, it's better injecting the navigation provider for your tests, e.g:
```
const MyComponent = (props) => (
  <NavigationProvider value={props.navigation}>
    <MyComp {...props}></MyComp>
  </NavigationProvider>
)
...
const defaultProps = {
  navigation: {
    navigate: jest.fn()
  },
  ...
}
const rendered = mount(<MyComponent {...defaultProps} />)
```
