### ISSUE TITLE
Android quickly click the back button to apply flashback

### ISSUE THREAD

**Issue by RmondJone** [react-navigation/react-navigation#8057]
Environment：
```
    "react": "16.9.0",
    "react-native": "0.61.4",
    "react-navigation": "4.2.2",
    "react-navigation-stack": "2.2.3",
    "react-navigation-tabs": "2.8.2",
```

Phenomenon：
On android，If I click the back button very quickly, the app will flash back.

Error log：
```
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
        at android.view.ViewGroup.addViewInner(ViewGroup.java:4917)
        at android.view.ViewGroup.addView(ViewGroup.java:4748)
        at android.view.ViewGroup.addView(ViewGroup.java:4688)
        at android.view.ViewGroup.addView(ViewGroup.java:4661)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:887)
        at androidx.fragment.app.FragmentManagerImpl.addAddedFragments(FragmentManagerImpl.java:2100)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1874)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1830)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
        at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
        at android.os.Handler.handleCallback(Handler.java:793)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6701)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:249)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
```

**Comment by RmondJone** [comment]
Upgrading to the latest version solved this problem！
```
    "react-navigation": "4.3.7",
    "react-navigation-stack": "2.3.11",
    "react-navigation-tabs": "2.8.11",
```
And I added this code to higher order components：
```
//Android物理返回键监听
this.backEventListener = BackHandler.addEventListener('hardwareBackPress', () => {
  if (!displayName || displayName === 'HomePage') {
    return false;
  }
  if (this.backPressTime) {
    let duration = moment().diff(this.backPressTime, 'ms', true);
    //点击频率小于1S则截断事件
    if (duration < 1000) {
      return true;
    }
  }
  this.backPressTime = moment();
});
```
