### ISSUE TITLE
Issue with Stack Navigator when building apk using App center

### ISSUE THREAD

**Issue by vineelk8** [react-navigation/react-navigation#8300]
**Current Behavior**

I'm trying to build apk using app center but getting the following errors

FAIL __tests__/App-test.js
  ● Test suite failed to run

    /Users/runner/runners/2.168.2/work/1/s/node_modules/@react-navigation/stack/lib/commonjs/views/assets/back-icon.png:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){�PNG
                                                                                             

    SyntaxError: Invalid or unexpected token

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (node_modules/@react-navigation/stack/lib/commonjs/index.tsx:13:3)

**Expected Behavior**

Should build without errors

**How to reproduce**

[1_Build.txt](https://github.com/react-navigation/react-navigation/files/4658518/1_Build.txt) -- Build log

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       | 5.3.0
| @react-navigation/stack        | 5.3.3
| react-native-gesture-handler   | 1.6.1
| react-native-safe-area-context | 1.0.0
| react-native-screens           | 2.7.0
| react-native                   | 0.62.2
| node                           | 13.7.0
| npm or yarn                    | npm @ 6.13.6

**Comment by vineelk8** [comment]
The issues still persist after upgrading to 5.3.9 stack navigator please re-open it again

**Comment by vineelk8** [comment]
> Found the following packages mentioned in the issue, but couldn't find version numbers for them:
> 
> * `@react-navigation/native`
> 
> Can you update the issue to include version numbers for those packages? The version numbers must match the format 1.2.3.
> 
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/stack` (found: `5.3.3`, latest: `5.3.9`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

The issue still persist after upgrading to @react-navigation/stack 5.3.9
