### ISSUE TITLE
Invalid hook call when testing

### ISSUE THREAD

**Issue by Rc85** [react-navigation/react-navigation#8440]
**Current Behavior**

Trying to test a react native app using react-navigation and it is throwing an invalid hook call error that seems to be coming from NavigationContainer

```
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
    1. You might have mismatching versions of React and the renderer (such as React DOM)
    2. You might be breaking the Rules of Hooks
    3. You might have more than one copy of React in the same app
    See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

      at resolveDispatcher (node_modules/react/cjs/react.development.js:1590:13)
      at Object.useRef (node_modules/react/cjs/react.development.js:1626:20)
      at NavigationContainer (node_modules/@react-navigation/native/lib/commonjs/NavigationContainer.tsx:39:30)
      at renderWithHooks (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5552:18)
      at updateForwardRef (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7288:20)
      at beginWork (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9068:16)
      at performUnitOfWork (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12649:12)
      at workLoopSync (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12622:22)
      at performSyncWorkOnRoot (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12333:9)
      at ../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1825:24

  console.error node_modules/react-native/Libraries/LogBox/LogBox.js:33
    The above error occurred in the <ForwardRef(NavigationContainer)> component:
        in ForwardRef(NavigationContainer)
        in View
        in View
        in View
        in View
        in RCTSafeAreaView
        in RCTSafeAreaView
        in ForwardRef(SafeAreaView)
        in Unknown
        in View
        in View
        in View
        in View
        in AppContainer (at src/index.js:26)

    Consider adding an error boundary to your tree to customize error handling behavior.
    Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
```
Very simple app set up. The Home is View, ScrollView, and Text only. No hooks.
```
export const App = (props? : Object) => {
  return (
    <>
      <StatusBar />
      <SafeAreaView>
        <View style={styles.outerWrapper}>
          <Image source={require('./assets/images/logo_brand_v5.png')} />
          <View style={styles.navigatorWrapper}>
            <NavigationContainer>
              <Tab.Navigator
              initialRouteName='Home'
              barStyle={{backgroundColor: theme.colors.red}}
              >
                <Tab.Screen
                name={'Home'}
                component={Pages.Home}
                options={{
                  tabBarTestID: 'home-nav-button',
                  tabBarIcon: (props) => (<FontAwesome5Pro name='home' color={props.focused ? theme.colors.white : theme.colors.faded} size={20} />)
                }}
                />
              </Tab.Navigator>
            </NavigationContainer>
          </View>
        </View>
      </SafeAreaView>
    </>
  );
};
```

**Expected Behavior**

Should pass test

**How to reproduce**

Create a react native app in Typescript using react-navigation's BottomMaterialTabNavigator. Write a jest test using @testing-library/react-native and run the test of the app.

**Your Environment**

@react-navigation/native 5.5.1
react-native 0.62.2
react 16.11.0
typescript 3.9.5
jest 24.9.0
ts-jest 26.1.0
@testing-library/react-native 5.0.3

**Comment by satya164** [comment]
Closing since you didn't provide a repro. Regardless, if testing library is giving error when testing normal React Native components, you should open an issue with testing library.
