### ISSUE TITLE
Unable to update properties for view tag,ViewManager for tag could not be found

### ISSUE THREAD

**Issue by BAE86AEC1946B6AB60CCD7452DC811F0** [react-navigation/react-navigation#8482]
**Current Behavior**

An error occurs when I use `<Stack.Navigator>`

No error when not using  `<Stack.Navigator>`

error message: 

```
	Time	Tag	Message
5	13:27:53.071	unknown:NativeViewHierarchyManager	Unable to update properties for view tag 2207
com.facebook.react.uimanager.IllegalViewOperationException: ViewManager for tag 2207 could not be found.
 View already dropped? false.
Last index 0 in last 100 views[I@2fd45237
	at com.facebook.react.uimanager.NativeViewHierarchyManager.resolveViewManager(NativeViewHierarchyManager.java:118)
	at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:141)
	at com.facebook.react.uimanager.UIImplementation.synchronouslyUpdateViewOnUIThread(UIImplementation.java:289)
	at com.facebook.react.uimanager.UIManagerModule.synchronouslyUpdateViewOnUIThread(UIManagerModule.java:397)
	at com.facebook.react.animated.PropsAnimatedNode.updateView(PropsAnimatedNode.java:98)
	at com.facebook.react.animated.NativeAnimatedNodesManager.updateNodes(NativeAnimatedNodesManager.java:547)
	at com.facebook.react.animated.NativeAnimatedNodesManager.runUpdates(NativeAnimatedNodesManager.java:456)
	at com.facebook.react.animated.NativeAnimatedModule$1.doFrameGuarded(NativeAnimatedModule.java:101)
	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:28)
	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:174)
	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:765)
	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
	at android.view.Choreographer.doFrame(Choreographer.java:549)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

```

app.js

```
  render() {
    return (
      <Provider store={store}>
        <AppNavigation/>
      </Provider>
    );
  }
```

AppNavigation:

```
export const App = props => {
  return (
    <NavigationContainer>
      <Stack.Navigator>
        <Stack.Screen name="Tags" component={Tags} />
      </Stack.Navigator>
    </NavigationContainer>
  );
 // When writing this, there is no error
 // return <Tags />;
};
```

**Expected Behavior**

- What do you expect should be happening?

How to make it not prompt this error?

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |Android |
| @react-navigation/native       |^5.4.2|
| @react-navigation/stack         |^5.3.9 |
| react-native-gesture-handler   | ^1.5.1 |
| react-native-safe-area-context |^1.0.2   |
| react-native-screens           | ^1.0.0-alpha.23 |
| react-native                   |0.61.5  |
| expo                           |-  |
| node                           | v12.16.1 |
| npm or yarn                    |yarn  |

**Comment by BAE86AEC1946B6AB60CCD7452DC811F0** [comment]
> * igation/stac

```
    "@react-navigation/bottom-tabs": "^5.5.2",
    "@react-navigation/native": "^5.5.1",
    "@react-navigation/stack": "^5.5.1",
```

I updated, but still the same error

**Comment by bakerac4** [comment]
Im seeing this as well - It seems to happen on Android and only on a release version. Downgrading to `"react-navigation-stack": "1.10.3"` seems to fix the issue - but I have tried it on a bunch of 2.X version and they all have the same problem.

**Comment by BAE86AEC1946B6AB60CCD7452DC811F0** [comment]
I can't reproduce it, it's normal to reinstall after deleting `node_modules`

**Comment by BAE86AEC1946B6AB60CCD7452DC811F0** [comment]
It seems to be related to dependent packages. After reinstalling with "npm install", the problem disappeared. If no one encounters the same problem as me, the issues can be close.

**Comment by JiboStore** [comment]
I am encountering the same problem on version ^5.1.1 after upgrading react-native to "^0.63.2" and react "^16.13.1", previously was fine on react-native "0.61.5" and react "16.12.0"

**Comment by aakrandan** [comment]
I am encountering the same issue, @JiboStore did you figure it out?

**Comment by aayushsin** [comment]
Same issue here with "@react-navigation/stack": "^5.10.0",   "react-native": "^0.63.3" and "react": "^17.0.1".

**Comment by tariqj86** [comment]
i face the same issue any solution

**Comment by rpavlovs** [comment]
Same issue here. @BAE86AEC1946B6AB60CCD7452DC811F0 do you know which dependent package was the culprit?

**Comment by Andriiklymiuk** [comment]
Anybody solved it?

**Comment by VillarSaveTime** [comment]
still having this issue. Any ideas to solve it?
