### ISSUE TITLE
HeaderBackButton - Style - error TS2769: No overload matches this call.

### ISSUE THREAD

**Issue by meabed** [react-navigation/react-navigation#8673]
Hey There 👋 ,

Thank you a ton for the useful and helpful library ❤️ 

There is a small typing issue in the file HeaderBackButton.tsx where style doesn't match the typing - would be a small fix :)

```
$ node_modules/@react-navigation/stack/src/views/Header/HeaderBackButton.tsx:164:62 - error TS2769: No overload matches this call.
```
![image](https://user-images.githubusercontent.com/45731/89274876-92655c00-d652-11ea-9659-e829f1631f4a.png)

Package versions: 
```
    "@react-navigation/bottom-tabs": "5.7.3",
    "@react-navigation/drawer": "5.8.7",
    "@react-navigation/native": "5.7.2",
    "@react-navigation/stack": "5.8.0",

    "typescript": "^3.9.7"
```

Thanks a lot 👍

**Comment by SrBrahma** [comment]
Probably is this the cause of my error with StackNavigator:

Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `HeaderBackButton`.

This error is located at:
    in HeaderBackButton (at HeaderSegment.tsx:154)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at HeaderSegment.tsx:332)
    in RCTView (at View.js:34)
    in View (at HeaderSegment.tsx:330)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at HeaderSegment.tsx:322)
    in HeaderSegment (at Header.tsx:58)
    in Header (at HeaderContainer.tsx:153)
    in RCTView (at View.js:34)
    in View (at HeaderContainer.tsx:130)
    in RCTView (at View.js:34)
    in View (at HeaderContainer.tsx:63)
    in HeaderContainer (at StackView.tsx:328)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:197)
    in RCTView (at View.js:34)
    in View (at CardSheet.tsx:33)
    in ForwardRef(CardSheet) (at Card.tsx:562)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:544)
    in PanGestureHandler (at GestureHandlerNative.tsx:13)
    in PanGestureHandler (at Card.tsx:538)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:534)
    in RCTView (at View.js:34)
    in View (at Card.tsx:528)
    in Card (at CardContainer.tsx:167)
    in CardContainer (at CardStack.tsx:552)
    in RCTView (at View.js:34)
    in View (at Screens.tsx:70)
    in MaybeScreen (at CardStack.tsx:545)
    in RCTView (at View.js:34)
    in View (at Screens.tsx:48)
    in MaybeScreenContainer (at CardStack.tsx:455)
    in CardStack (at StackView.tsx:437)
    in KeyboardManager (at StackView.tsx:435)
    in SafeAreaProviderCompat (at StackView.tsx:432)
    in RCTView (at View.js:34)
    in View (at GestureHandlerRootView.android.js:26)
    in GestureHandlerRootView (at StackView.tsx:431)
    in StackView (at createStackNavigator.tsx:82)
    in StackNavigator (at Stores.tsx:36)
    in StoresPage (at SceneView.tsx:122)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:115)
    in EnsureSingleNavigator (at SceneView.tsx:114)
    in SceneView (at useDescriptors.tsx:150)
    in RCTView (at View.js:34)
    in View (created by SceneView)
    in SceneView (created by Pager)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:233)
    in AnimatedComponent(View) (created by PanGestureHandler)
    in PanGestureHandler (created by Pager)
    in Pager (created by TabView)
    in GestureHandlerRootView (at GestureHandlerRootView.android.js:31)
    in GestureHandlerRootView (created by TabView)
    in TabView (at MaterialTopTabView.tsx:50)
    in MaterialTopTabView (at createMaterialTopTabNavigator.tsx:41)
    in MaterialTopTabNavigator (at App.tsx:60)
    in RNCSafeAreaView (at App.tsx:48)
    in RNCSafeAreaProvider (at SafeAreaContext.tsx:74)
    in SafeAreaProvider (at App.tsx:47)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:390)
    in ForwardRef(BaseNavigationContainer) (at NavigationContainer.tsx:91)
    in ThemeProvider (at NavigationContainer.tsx:90)
    in ForwardRef(NavigationContainer) (at App.tsx:46)
    in Wrappers (at App.tsx:56)
    in App (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)

**Comment by SrBrahma** [comment]
Yup, removing this 'style' (that was added [between 5.7.1 and 5.7.3 ](https://github.com/react-navigation/react-navigation/compare/@react-navigation%2Fnative@5.7.1...@react-navigation%2Fnative@5.7.3?diff=unified)) made my error above go away. It was happening when accessing a page with the header and its back button.

**Comment by mksglu** [comment]
That's why our test files are broken.

``` FAIL  src/components/Text/__tests__/Text.test.js
  ● Test suite failed to run

    Invariant Violation: "ios" is not a valid style property.
    StyleSheet container: {
      "alignItems": "center",
      "flexDirection": "row",
      "ios": null,
      "default": {
        "marginVertical": 3,
        "marginHorizontal": 11
      }
    }
    Valid style props: [
      "alignContent",
      "alignItems",
      "alignSelf",
      "aspectRatio",
      "backfaceVisibility",
      "backgroundColor",
      "borderBottomColor",
      "borderBottomEndRadius",
      "borderBottomLeftRadius",
      "borderBottomRightRadius",
      "borderBottomStartRadius",
      "borderBottomWidth",
      "borderColor",
      "borderEndColor",
      "borderEndWidth",
      "borderLeftColor",
      "borderLeftWidth",
      "borderRadius",
      "borderRightColor",
      "borderRightWidth",
      "borderStartColor",
      "borderStartWidth",
      "borderStyle",
      "borderTopColor",
      "borderTopEndRadius",
      "borderTopLeftRadius",
      "borderTopRightRadius",
      "borderTopStartRadius",
      "borderTopWidth",
      "borderWidth",
      "bottom",
      "color",
      "decomposedMatrix",
      "direction",
      "display",
      "elevation",
      "end",
      "flex",
      "flexBasis",
      "flexDirection",
      "flexGrow",
      "flexShrink",
      "flexWrap",
      "fontFamily",
      "fontSize",
      "fontStyle",
      "fontVariant",
      "fontWeight",
      "height",
      "includeFontPadding",
      "justifyContent",
      "left",
      "letterSpacing",
      "lineHeight",
      "margin",
      "marginBottom",
      "marginEnd",
      "marginHorizontal",
      "marginLeft",
      "marginRight",
      "marginStart",
      "marginTop",
      "marginVertical",
      "maxHeight",
      "maxWidth",
      "minHeight",
      "minWidth",
      "opacity",
      "overflow",
      "overlayColor",
      "padding",
      "paddingBottom",
      "paddingEnd",
      "paddingHorizontal",
      "paddingLeft",
      "paddingRight",
      "paddingStart",
      "paddingTop",
      "paddingVertical",
      "position",
      "resizeMode",
      "right",
      "rotation",
      "scaleX",
      "scaleY",
      "shadowColor",
      "shadowOffset",
      "shadowOpacity",
      "shadowRadius",
      "start",
      "textAlign",
      "textAlignVertical",
      "textDecorationColor",
      "textDecorationLine",
      "textDecorationStyle",
      "textShadowColor",
      "textShadowOffset",
      "textShadowRadius",
      "textTransform",
      "tintColor",
      "top",
      "transform",
      "transformMatrix",
      "translateX",
      "translateY",
      "width",
      "writingDirection",
      "zIndex"
    ]

      at invariant (node_modules/invariant/invariant.js:40:15)
      at styleError (node_modules/react-native/Libraries/StyleSheet/StyleSheetValidation.js:81:3)
      at Function.validateStyleProp (node_modules/react-native/Libraries/StyleSheet/StyleSheetValidation.js:35:7)
      at Function.validateStyle (node_modules/react-native/Libraries/StyleSheet/StyleSheetValidation.js:59:28)
      at Object.create (node_modules/react-native/Libraries/StyleSheet/StyleSheet.js:356:30)
      at Object.<anonymous> (node_modules/@react-navigation/stack/lib/commonjs/views/Header/HeaderBackButton.tsx:179:27)```
