### ISSUE TITLE
Running gitpkg publish fails with typescript errors

### ISSUE THREAD

**Issue by thornbill** [react-navigation/react-navigation#8724]
**Current Behavior**

- Following the instructions for [Installing from a fork on GitHub](https://github.com/react-navigation/react-navigation#installing-from-a-fork-on-github) results in a failure due to multiple typescript errors.

```
gitpkg publish v1.0.0-beta.2
  [3/6] 🏇  Running prepublish scripts...
✖ error Command failed with exit code 1: yarn run prepare
bob build

build files for publishing

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]

Error: Failed to build definition files.
    at build (/home/bill/Projects/react-navigation/node_modules/@react-native-community/bob/lib/targets/typescript.js:112:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.handler (/home/bill/Projects/react-navigation/node_modules/@react-native-community/bob/lib/cli.js:350:9)
error Command failed with exit code 1.
yarn run v1.18.0
$ bob build
ℹ Building target commonjs
ℹ Cleaning up previous build at lib/commonjs
ℹ Compiling 12 files in src with babel
✓ Wrote files to lib/commonjs
ℹ Building target module
ℹ Cleaning up previous build at lib/module
ℹ Compiling 12 files in src with babel
✓ Wrote files to lib/module
ℹ Building target typescript
ℹ Cleaning up previous build at lib/typescript
ℹ Generating type definitions with tsc
src/__tests__/index.test.tsx:4:52 - error TS2307: Cannot find module '@react-navigation/native' or its corresponding type declarations.

4 import { NavigationContainer, ParamListBase } from '@react-navigation/native';
                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~

src/navigators/createBottomTabNavigator.tsx:9:8 - error TS2307: Cannot find module '@react-navigation/native' or its corresponding type declarations.

9 } from '@react-navigation/native';
         ~~~~~~~~~~~~~~~~~~~~~~~~~~

src/types.tsx:18:8 - error TS2307: Cannot find module '@react-navigation/native' or its corresponding type declarations.

18 } from '@react-navigation/native';
          ~~~~~~~~~~~~~~~~~~~~~~~~~~

src/views/Badge.tsx:4:26 - error TS2307: Cannot find module '@react-navigation/native' or its corresponding type declarations.

4 import { useTheme } from '@react-navigation/native';
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~

src/views/BottomTabBar.tsx:15:8 - error TS2307: Cannot find module '@react-navigation/native' or its corresponding type declarations.

15 } from '@react-navigation/native';
          ~~~~~~~~~~~~~~~~~~~~~~~~~~

src/views/BottomTabBar.tsx:224:22 - error TS7006: Parameter 'route' implicitly has an 'any' type.

224         {routes.map((route, index) => {
                         ~~~~~

src/views/BottomTabBar.tsx:224:29 - error TS7006: Parameter 'index' implicitly has an 'any' type.

224         {routes.map((route, index) => {
                                ~~~~~

src/views/BottomTabItem.tsx:13:39 - error TS2307: Cannot find module '@react-navigation/native' or its corresponding type declarations.

13 import { Link, Route, useTheme } from '@react-navigation/native';
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~

src/views/BottomTabView.tsx:8:8 - error TS2307: Cannot find module '@react-navigation/native' or its corresponding type declarations.

8 } from '@react-navigation/native';
         ~~~~~~~~~~~~~~~~~~~~~~~~~~

src/views/BottomTabView.tsx:97:28 - error TS7006: Parameter 'route' implicitly has an 'any' type.

97               {routes.map((route, index) => {
                              ~~~~~

src/views/BottomTabView.tsx:97:35 - error TS7006: Parameter 'index' implicitly has an 'any' type.

97               {routes.map((route, index) => {
                                     ~~~~~

src/views/TabBarIcon.tsx:3:28 - error TS2307: Cannot find module '@react-navigation/native' or its corresponding type declarations.

3 import type { Route } from '@react-navigation/native';
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 12 errors.

✖ Failed to build definition files.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Expected Behavior**

- Build should succeed and publish to GitHub

**How to reproduce**

- Follow the steps here: https://github.com/react-navigation/react-navigation#installing-from-a-fork-on-github

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | N/A |
| @react-navigation/native       | main |
| react-native                   | 5.7.3 |
| expo                           | N/A |
| node                           | 12.18.3 |
| npm or yarn                    | yarn |

**Comment by thornbill** [comment]
Updated to include the version found in yarn.lock.

**Comment by thornbill** [comment]
Well I found a solution, but I think this still deserves some attention to either improve the documentation or tooling to fix this experience.

The issue is caused by dependencies on other packages in this repo needing to be built prior to building a given package. In my case I was trying to build the `bottom-tabs` package which depends on the `native` package. In order for `bottom-tabs` to build, I had to build the following packages in **this order** to satisfy the dependencies of each.

* `routers`
* `core`
* `native`
* `bottom-tabs`

**Comment by giantslogik** [comment]
To get yarn to use the gitpkg published packages and non-interactively install dependencies, i had to add/edit the resolutions section of package.json. (First **gitpkg publish** the dependencies.)
```
"resolutions": {
                "@react-navigation/core": "<user>/react-navigation.git#<name>",
                "@react-navigation/routers": "<user>/react-navigation.git#<name>",
  }
```

_This was need as the packages in forked main has unpublished dependency changes _

**Comment by OmarBasem** [comment]
> Well I found a solution, but I think this still deserves some attention to either improve the documentation or tooling to fix this experience.
> 
> The issue is caused by dependencies on other packages in this repo needing to be built prior to building a given package. In my case I was trying to build the `bottom-tabs` package which depends on the `native` package. In order for `bottom-tabs` to build, I had to build the following packages in **this order** to satisfy the dependencies of each.
> 
> * `routers`
> * `core`
> * `native`
> * `bottom-tabs`

I also had to build `elements` package
