### ISSUE TITLE
getting "TypeError: Cannot read property 'add' of undefined" error on running jest

### ISSUE THREAD

**Issue by abolfazlyounesi** [react-navigation/react-navigation#8856]
```
● Test suite failed to run

    TypeError: Cannot read property 'add' of undefined

      at Object.<anonymous> (node_modules/@react-navigation/stack/lib/commonjs/utils/conditional.tsx:3:7)
      at Object.<anonymous> (node_modules/@react-navigation/stack/lib/commonjs/TransitionConfigs/CardStyleInterpolators.tsx:3:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.246 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

"react-native": "0.63.2",
"@react-navigation/native": "^5.7.3",
 "@react-navigation/stack": "^5.9.0",
"babel-jest": "^26.3.0",
"jest": "^26.4.2"
"react-test-renderer": "^16.13.1",

**Comment by pratt3351** [comment]
i'm facing this issue too !
any solutions?

**Comment by jakewtaylor** [comment]
I was seeing this issue because I was mocking `react-native`:
```TS
jest.mock('react-native', () => {
  return {
    StatusBar: {
      setBarStyle: jest.fn(),
    },
  };
});
```

and @react-navigation/stack is using `Animated` from `react-native`, so I solved it by requiring actual:

```TS
jest.mock('react-native', () => {
  const rn = jest.requireActual('react-native');
  return {
    ...rn,
    StatusBar: {
      setBarStyle: jest.fn(),
    },
  };
});
```

**Comment by Steffi3rd** [comment]
Same error here with React Navigation 4.0.10

**package.json** 

```
  "jest": {
    "preset": "react-native",
    "setupFiles": [ 
      "./node_modules/react-native-gesture-handler/jestSetup.js",
      "./node_modules/react-native/jest/setup.js",
      "<rootDir>/jest/setup.js"
    ],
    "transformIgnorePatterns": [
      "node_modules/(?!(jest-)?react-native|react-navigation)"
    ]
  }
```

**setup.js** 

```
jest.mock('react-native', () => ({
  Linking: {
    addEventListener: jest.fn(),
    removeEventListener: jest.fn(),
    openURL: jest.fn(),
    canOpenURL: jest.fn(),
    getInitialURL: jest.fn(),
  },
}));

```


**App-test.js**

```
/**
 * @format
 */

import 'react-native';
import React from 'react';
import App from '../App';

// Note: test renderer must be required after react-native.
import renderer from 'react-test-renderer';

it('renders correctly', () => {
  renderer.create(<App />);
});
```


**`yarn test`** 

```
yarn run v1.21.1
$ jest
 FAIL  __tests__/App-test.js
  ● Test suite failed to run

    TypeError: Cannot read property 'add' of undefined

      at Object.<anonymous> (node_modules/react-navigation-stack/lib/commonjs/vendor/utils/conditional.tsx:3:7)
      at Object.<anonymous> (node_modules/react-navigation-stack/lib/commonjs/vendor/TransitionConfigs/CardStyleInterpolators.tsx:3:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.756s

```

**Comment by satya164** [comment]
Closing since you didn't provide a repro to be able to debug the issue. Please open a new issue if you have a minimal repro which I could take a look at.

**Comment by fahryrozy** [comment]
Did anyone fix this issue?

**Comment by ududsha** [comment]
please update here if anyone fixed it already?

**Comment by JaioSkura** [comment]
Same point... any fix for this?

**Comment by juniordeleon013** [comment]
Did anyone fix this issue?
