### ISSUE TITLE
Error when testing

### ISSUE THREAD

**Issue by DracotMolver** [react-navigation/react-navigation#9023]
**Current Behavior**

After updating some dependencies. My tests are failing on the same component: `<PanGestureHandler />`. 

```sh
console.error
      The above error occurred in the <PanGestureHandler> component:
      
          at PanGestureHandler (/Users/diegomolina/Documents/mobile_archetype/node_modules/react-native-gesture-handler/createHandler.js:140:24)
          at PanGestureHandler (/Users/diegomolina/Documents/mobile_archetype/node_modules/@react-navigation/stack/lib/commonjs/views/GestureHandlerNative.tsx:9:22)
          at View
          at Component (/Users/diegomolina/Documents/mobile_archetype/node_modules/react-native/jest/mockComponent.js:19:18)
          at AnimatedComponent (/Users/diegomolina/Documents/mobile_archetype/node_modules/react-native/Libraries/Animated/src/createAnimatedComponent.js:27:43)
          at AnimatedComponentWrapper
          at View
          at Component (/Users/diegomolina/Documents/mobile_archetype/node_modules/react-native/jest/mockComponent.js:19:18)
          at Card (/Users/diegomolina/Documents/mobile_archetype/node_modules/@react-navigation/stack/lib/commonjs/views/Stack/Card.tsx:91:58)
          at CardContainer (/Users/diegomolina/Documents/mobile_archetype/node_modules/@react-navigation/stack/lib/commonjs/views/Stack/CardContainer.tsx:74:24)
          at View
          at Component (/Users/diegomolina/Documents/mobile_archetype/node_modules/react-native/jest/mockComponent.js:19:18)
          at MaybeScreen (/Users/diegomolina/Documents/mobile_archetype/node_modules/@react-navigation/stack/lib/commonjs/views/Screens.tsx:57:29)
          at View
          at Component (/Users/diegomolina/Documents/mobile_archetype/node_modules/react-native/jest/mockComponent.js:19:18)
          at MaybeScreenContainer (/Users/diegomolina/Documents/mobile_archetype/node_modules/@react-navigation/stack/lib/commonjs/views/Screens.tsx:40:38)
          at CardStack (/Users/diegomolina/Documents/mobile_archetype/node_modules/@react-navigation/stack/lib/commonjs/views/Stack/CardStack.tsx:286:29)
          at KeyboardManager (/Users/diegomolina/Documents/mobile_archetype/node_modules/@react-navigation/stack/lib/commonjs/views/KeyboardManager.tsx:13:69)
          at RNCSafeAreaProvider
          at RNCSafeAreaProvider (/Users/diegomolina/Documents/mobile_archetype/node_modules/react-native/jest/setup.js:324:22)
          at SafeAreaProvider (/Users/diegomolina/Documents/mobile_archetype/node_modules/react-native-safe-area-context/lib/commonjs/SafeAreaContext.tsx:22:34)
          at SafeAreaProviderCompat (/Users/diegomolina/Documents/mobile_archetype/node_modules/@react-navigation/stack/lib/commonjs/views/SafeAreaProviderCompat.tsx:30:50)
          at View
          at Component (/Users/diegomolina/Documents/mobile_archetype/node_modules/react-native/jest/mockComponent.js:19:18)
          at StackView (/Users/diegomolina/Documents/mobile_archetype/node_modules/@react-navigation/stack/lib/commonjs/views/Stack/StackView.tsx:59:70)
          at StackNavigator (/Users/diegomolina/Documents/mobile_archetype/node_modules/@react-navigation/stack/lib/commonjs/navigators/createStackNavigator.tsx:26:25)
          at EnsureSingleNavigator (/Users/diegomolina/Documents/mobile_archetype/node_modules/@react-navigation/core/lib/commonjs/EnsureSingleNavigator.tsx:20:49)
          at BaseNavigationContainer (/Users/diegomolina/Documents/mobile_archetype/node_modules/@react-navigation/core/lib/commonjs/BaseNavigationContainer.tsx:94:5)
          at ThemeProvider (/Users/diegomolina/Documents/mobile_archetype/node_modules/@react-navigation/native/lib/commonjs/theming/ThemeProvider.tsx:10:39)
          at NavigationContainer (/Users/diegomolina/Documents/mobile_archetype/node_modules/@react-navigation/native/lib/commonjs/NavigationContainer.tsx:40:5)
          at MockedNavigator (/Users/diegomolina/Documents/mobile_archetype/__mocks__/mockNavigation.js:10:28)
          at Provider (/Users/diegomolina/Documents/mobile_archetype/node_modules/react-redux/lib/components/Provider.js:19:20)
          at MockProvider (/Users/diegomolina/Documents/mobile_archetype/__mocks__/mockProvider.js:6:25)
      
      Consider adding an error boundary to your tree to customize error handling behavior.
      Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.

      at logCapturedError (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10989:23)
      at update.callback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11022:5)
      at callCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3662:12)
      at commitUpdateQueue (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3683:9)
      at commitLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11855:11)
      at commitLayoutEffects (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14443:7)
      at Object.invokeGuardedCallbackProd (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11308:10)
      at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11499:31)

    console.error
      Warning: An update to ForwardRef(NavigationContainer) inside a test was not wrapped in act(...).
      
      When testing, code that causes React state updates should be wrapped into act(...):
      
      act(() => {
        /* fire events that update state */
      });
      /* assert on the output */
      
      This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
          at NavigationContainer (/Users/diegomolina/Documents/mobile_archetype/node_modules/@react-navigation/native/lib/commonjs/NavigationContainer.tsx:40:5)
          at MockedNavigator (/Users/diegomolina/Documents/mobile_archetype/__mocks__/mockNavigation.js:10:28)
          at Provider (/Users/diegomolina/Documents/mobile_archetype/node_modules/react-redux/lib/components/Provider.js:19:20)
          at MockProvider (/Users/diegomolina/Documents/mobile_archetype/__mocks__/mockProvider.js:6:25)
```
This is a basic test that was working before  the update.

**__test__/stack.spec.js**
```js
import React from 'react';
import { render, cleanup, act } from '@testing-library/react-native';
import TransactionStack from 'src/stack/TransactionStack';
import MockedNavigator from '/__mocks__/mockNavigation';
import MockProvider from '/__mocks__/mockProvider';

describe('STACK', () => {
  afterEach(cleanup);

  it('Should render correctly the stack navigation', () => {
    const { toJSON, update } = render(
      <MockProvider>
        <MockedNavigator component={TransactionStack} />
      </MockProvider>,
    );

    act(() => {
      update();
    });

    expect(toJSON()).toMatchSnapshot();
  });
});
```

**__mocks__/stack.spec.js**
```js
import React from 'react';
import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';
import { Text } from 'react-native';

const TestComponent = () => <Text>home</Text>;

const Stack = createStackNavigator();

const MockedNavigator = ({ component, params = {} }) => (
  <NavigationContainer>
    <Stack.Navigator>
      <Stack.Screen
        name="MockedScreen"
        component={component}
        initialParams={params}
      />
      <Stack.Screen
        name="Home"
        component={TestComponent}
        initialParams={params}
      />
    </Stack.Navigator>
  </NavigationContainer>
);

export default MockedNavigator;
```

**stack/TransactionStack/index.js**
```js
import React from 'react';
import { createStackNavigator } from '@react-navigation/stack';
import Transactions from 'src/containers/Transactions';

const Stack = createStackNavigator();

const TransactionStack = () => (
  <Stack.Navigator headerMode="screen">
    <Stack.Screen
      name="Transactions"
      options={{
        headerTitle: "Transactions"
      }}
      component={Transactions}
    />
  </Stack.Navigator>
);

export default TransactionStack;
```

I've tried already wrapping the `update` function within an `act` function or `await act(async() => { })` function. but I'm still getting the same error.  The Transaction containers it re-render when I update the props using Redux.

```js
import React, { PureComponent } from 'react';
import { connect } from 'react-redux';
import { Text } from 'react-native';

class TransactionsContainer extends PureComponent {
  render() {
    const { currentAccount } = this.props;

    return currentAccount.length === 0 ? (
          <LandingTransactions />
        ) : (
          <Text>Show info here!</Text>
        )}
  }
}

const mapStateToProps = (store) => ({
  currentAccount: store.entities.products.currentAccount,
});

export default connect(mapStateToProps, null)(TransactionsContainer);
```

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| @react-navigation/native       | ^5.8.4
| @react-navigation/stack        | ^5.12.1
| react-native-gesture-handler   | ^1.8.0
| react-native-safe-area-context | ^3.1.8
| react-native-screens           | ^2.12.0
| react-native                   | ^0.63.3
| node                           | v12.16.3
| npm                    | 6.14.8

**Comment by tickietackie** [comment]
Workaround so far for me: Downgrading to the latest version 16.

yarn upgrade react-test-renderer@16.14.0

**Comment by ezequielrozen** [comment]
Hello! Any update here? Downgrading to 16.14.0 of react-test-tenderer is still the only solution for this error? I did that and now I'm having a time out in my test.

```
import React from 'react';
import { render, cleanup } from '@testing-library/react-native';
import { NavigationContainer } from '@react-navigation/native';
import { ApplicationProvider } from '@ui-kitten/components';
import {
  light,
  mapping,
} from '@eva-design/eva';

import './setupTests';

import HomeNavigator from './Home';

describe('HomeNavigator', () => {
  afterEach(cleanup);

  it('renders the correct screen', async () => {
    const { findByText } = render(
      <ApplicationProvider theme={light} mapping={mapping}>
        <NavigationContainer>
          <HomeNavigator />
        </NavigationContainer>
      </ApplicationProvider>
    );

    const homeText = await findByText('THIS IS HOME SCREEN!!!!');

    expect(homeText).toBeTruthy();
  });
});
```
I was following the official guide of react-native-testing-library https://callstack.github.io/react-native-testing-library/docs/react-navigation/

**Comment by satya164** [comment]
Your react-test-renderer version needs to match react version, otherwise you'll have incompatibilities. This is not a bug in React Navigation.

**Comment by ezequielrozen** [comment]
@satya164 ok, I'm using the corresponding version of react-test-renderer now but the original issue is still happening....

```
 console.error
      The above error occurred in the <PanGestureHandler> component:

          at PanGestureHandler (/Users/erozenzwaig/Projects/bitera-app/node_modules/react-native-gesture-handler/createHandler.js:140:24)
          at PanGestureHandler (/Users/erozenzwaig/Projects/bitera-app/node_modules/@react-navigation/stack/lib/commonjs/views/GestureHandlerNative.tsx:9:22)
          at View
          at View (/Users/erozenzwaig/Projects/bitera-app/node_modules/react-native/jest/mockComponent.js:19:18)
          at AnimatedComponent (/Users/erozenzwaig/Projects/bitera-app/node_modules/react-native/Libraries/Animated/src/createAnimatedComponent.js:27:43)
          at AnimatedComponentWrapper
          at View
          at View (/Users/erozenzwaig/Projects/bitera-app/node_modules/react-native/jest/mockComponent.js:19:18)
          at Card (/Users/erozenzwaig/Projects/bitera-app/node_modules/@react-navigation/stack/lib/commonjs/views/Stack/Card.tsx:91:58)
          at CardContainer (/Users/erozenzwaig/Projects/bitera-app/node_modules/@react-navigation/stack/lib/commonjs/views/Stack/CardContainer.tsx:74:24)
          at View
          at View (/Users/erozenzwaig/Projects/bitera-app/node_modules/react-native/jest/mockComponent.js:19:18)
          at MaybeScreen (/Users/erozenzwaig/Projects/bitera-app/node_modules/@react-navigation/stack/lib/commonjs/views/Screens.tsx:57:29)
          at View
          at View (/Users/erozenzwaig/Projects/bitera-app/node_modules/react-native/jest/mockComponent.js:19:18)
          at MaybeScreenContainer (/Users/erozenzwaig/Projects/bitera-app/node_modules/@react-navigation/stack/lib/commonjs/views/Screens.tsx:40:38)
          at CardStack (/Users/erozenzwaig/Projects/bitera-app/node_modules/@react-navigation/stack/lib/commonjs/views/Stack/CardStack.tsx:286:29)
          at KeyboardManager (/Users/erozenzwaig/Projects/bitera-app/node_modules/@react-navigation/stack/lib/commonjs/views/KeyboardManager.tsx:13:69)
          at RNCSafeAreaProvider
          at RNCSafeAreaProvider (/Users/erozenzwaig/Projects/bitera-app/node_modules/react-native/jest/setup.js:324:22)
          at SafeAreaProvider (/Users/erozenzwaig/Projects/bitera-app/node_modules/react-native-safe-area-context/lib/commonjs/SafeAreaContext.tsx:22:34)
          at SafeAreaProviderCompat (/Users/erozenzwaig/Projects/bitera-app/node_modules/@react-navigation/stack/lib/commonjs/views/SafeAreaProviderCompat.tsx:30:50)
          at View
          at View (/Users/erozenzwaig/Projects/bitera-app/node_modules/react-native/jest/mockComponent.js:19:18)
          at StackView (/Users/erozenzwaig/Projects/bitera-app/node_modules/@react-navigation/stack/lib/commonjs/views/Stack/StackView.tsx:59:70)
          at StackNavigator (/Users/erozenzwaig/Projects/bitera-app/node_modules/@react-navigation/stack/lib/commonjs/navigators/createStackNavigator.tsx:26:25)
          at HomeNavigator
          at EnsureSingleNavigator (/Users/erozenzwaig/Projects/bitera-app/node_modules/@react-navigation/core/lib/commonjs/EnsureSingleNavigator.tsx:20:49)
          at BaseNavigationContainer (/Users/erozenzwaig/Projects/bitera-app/node_modules/@react-navigation/core/lib/commonjs/BaseNavigationContainer.tsx:94:5)
          at ThemeProvider (/Users/erozenzwaig/Projects/bitera-app/node_modules/@react-navigation/native/lib/commonjs/theming/ThemeProvider.tsx:10:39)
          at NavigationContainer (/Users/erozenzwaig/Projects/bitera-app/node_modules/@react-navigation/native/lib/commonjs/NavigationContainer.tsx:40:5)
```

**Comment by satya164** [comment]
The comment above you says it fixed it for them. We also have basic test in the repo which doesn't have any errors. So you need to provide a repro if you still have an error after following the required setup https://reactnavigation.org/docs/testing/

**Comment by DracotMolver** [comment]
I have React and their other parties libraries in version 17.0.1. I'll check this out on monday and see if it works downgrading to version 16.14.0  :)

**Comment by bentilley** [comment]
Hello, I'm seeing the same error on 17.0.1 (react and react-test-renderer). I can confirm that downgrading to `16.14.0` fixed the issue for me.

I believe the root error was this in the react render:

```
Unable to find node on an unmounted component.

      at findHostInstanceWithWarning (node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:20401:17)
      at findNodeHandle (node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:21013:20)
      at findNodeHandle (node_modules/react-native-gesture-handler/createHandler.js:14:10)
      at Handler.componentDidMount (node_modules/react-native-gesture-handler/createHandler.js:243:34)
      at commitLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11782:24)
      at commitLayoutEffects (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14443:7)
      at Object.invokeGuardedCallbackProd (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11308:10)
      at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11499:31)
      at commitRootImpl (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14172:9)
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:646:12)
```

Possibly the issue should be reopened @satya164 as it looks like there is an issue for `17.0.1` 🤷‍♀️ ? The react-navigation tests are currently running against react `16.13.x`. Unless there is a bulk issue to bump the react version? You can reproduce in the react-navigation repo by bumping the react and react-dom versions to 17 and running the tests. You'll see several failing with the same error.

**Comment by ahummel25** [comment]
Getting this same error with matching `17.0.1` versions of `react-test-renderer` and `react`. Can this be reopened or does the issue belong in a different repo?

**Comment by MarceloPrado** [comment]
I can confirm this is still happening on `17.0.1`. Downgrading to `16.14.0` fixes the issue.

**Comment by und3f1n3d** [comment]
Once I downgraded from the react-test-renderer from 17.0.1 to 16.4.0.  My snapshot now includes what rendered inside a flatlist.  However, once  using 17.0.1, everything inside the Flatlist went missing.   And then this series of errors like above, would return. 

`      The above error occurred in the <TapGestureHandler> component:
      
          at Handler (<path to project>/node_modules/react-native-gesture-handler/createHandler.js:140:24)
          at View
          at Component (<path to project>/node_modules/react-native/jest/mockComponent.js:19:18)
          at AnimatedComponent (<path to project>/node_modules/react-native/Libraries/Animated/src/createAnimatedComponent.js:27:43)
          at AnimatedComponentWrapper
          at Handler (<path to project>/node_modules/react-native-gesture-handler/createHandler.js:140:24)
          at Swipeable (<path to project>/node_modules/react-native-gesture-handler/Swipeable.js:65:32)`

**Comment by ArshanKhanifar** [comment]
just tried this with both `react` and `react-test-renderer` at `17.0.2` and it works ✅  🎉  . I don't get the `< PanGestureHandler>` error anymore. 
```
react-test-renderer@^17.0.0:
  version "17.0.2"
  resolved "https://registry.yarnpkg.com/react-test-renderer/-/react-test-renderer-17.0.2.tgz#4cd4ae5ef1ad5670fc0ef776e8cc7e1231d9866c"
  integrity sha512-yaQ9cB89c17PUb0x6UfWRs7kQCorVdHlutU1boVPEsB8IDZH6n9tHxMacc3y0JoXOJUsZb/t/Mb8FUWMKaM7iQ==
  dependencies:
    object-assign "^4.1.1"
    react-is "^17.0.2"
    react-shallow-renderer "^16.13.1"
    scheduler "^0.20.2"

react@^17.0.0:
  version "17.0.2"
  resolved "https://registry.yarnpkg.com/react/-/react-17.0.2.tgz#d0b5cc516d29eb3eee383f75b62864cfb6800037"
  integrity sha512-gnhPt75i/dq/z3/6q/0asP78D0u592D5L1pd7M8P+dck6Fu/jJeL6iVVK23fptSUZj8Vjf++7wXA8UNclGQcbA==
  dependencies:
    loose-envify "^1.1.0"
    object-assign "^4.1.1"
```

**Comment by FF-AndresR** [comment]
Has anyone gotten this to work with both `react` and `react-test-renderer` `^17.0.0` ?
@ArshanKhanifar Tried `17.0.2` but it didn't work.

**Comment by hyochan** [comment]
Confirm still happening in `17.0.2`.

**Comment by zfrankdesign** [comment]
Can also confirm with 17.0.2

**Comment by devxoul** [comment]
I can confirm that the problem has fixed in `^17.0.2` with react-native `^0.64.0`.

For me there was no problem with react-native `^0.63.4` and react-test-renderer `^16.9.2` but after I upgraded react-native to `^0.64.0` it started to product the errors.

**Comment by MatkoMilic** [comment]
Having the same issue still. on React 16.13.1 and RN 0.63.3

**Comment by kernelsrinivas** [comment]
If we mock the while navigate, its works fine. 

jest.mock(
  '@react-navigation/stack/lib/commonjs/views/GestureHandlerNative', () => {
    const RN = require('react-native');
    return {
      PanGestureHandler: RN.View,
      GestureHandlerRootView: RN.View,
    };
  },
);
