### ISSUE TITLE
Force Close On Production Build 

### ISSUE THREAD

**Issue by alfianlensun** [react-navigation/react-navigation#9077]
i got this error in production build

- my code :
Route = [componentA, componentB]
{Routes.map((route, key) => <Stack.Screen key={key.toString()} name={route.name !== undefined ? route.name.toString() : route.WrappedComponent.name.toString()} component={route} />)}

- error: 
com.facebook.react.common.JavascriptException: Error: A navigator cannot contain multiple 'Screen' components with the same name (found duplicate screen named 'T')

This error is located at:
    in Unknown
    in Unknown
    in ForwardRef
    in Unknown
    in ForwardRef
    in c
    in E
    in A
    in RCTView
    in View
    in Unknown
    in Unknown
    in p
    in RCTView
    in View
    in RCTView
    in View
    in C, stack:
<unknown>@445:542
reduce@-1
default@445:497
<unknown>@504:1118
fr@95:38814
Ci@95:80333
Cl@95:74704
Rl@95:74629
Pl@95:74396
Tl@95:71529
Tl@-1
<unknown>@95:23572
unstable_runWithPriority@202:3402
an@95:23519
ln@95:23454
ml@95:68215
ra@95:88702
render@95:90971
exports@361:549
run@353:1310
runApplication@353:2322
value@32:3350
<unknown>@32:747
value@32:2610
value@32:719
value@-1

 at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:83)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
 at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
 at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
 at android.os.Handler.handleCallback(Handler.java:914)
 at android.os.Handler.dispatchMessage(Handler.java:100)
 at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
 at android.os.Looper.loop(Looper.java:224)
 at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
 at java.lang.Thread.run(Thread.java:919)

**Comment by raajnadar** [comment]
Don't you think the error message is self explanatory??
