### ISSUE TITLE
expo SDK 41 global.__expo deprecated warning

### ISSUE THREAD

**Issue by codGmer** [react-navigation/react-navigation#9160]
Hello, at several react navigation files i see the code: global.__expo and expo SDK 40 gives a warning that it is deprecated.

**Comment by dave-vazquez** [comment]
I'm receiving the same warning, specifically when using the `SafeAreaView` component. There is a lot of usage of the global object in react-navigation's library.

"expo": "~40.0.0",
"react-navigation": "^4.4.3"

**Comment by yoojeen126** [comment]
I got same issue in expo 40 sdk.
How can i fix it?

**Comment by dave-vazquez** [comment]
It's just a warning, so there's nothing to fix. But if you update to Expo SDK 41, react-navigation will be incompatible. If you intend to continue using react-navigation, don't upgrade to SDK 41 until react-navigation is compatible.

If you want to suppress the warnings in the meantime you can use this:

```
import { LogBox } from "react-native";

LogBox.ignoreLogs([
  "Your project is accessing the following APIs from a deprecated global rather than a module import: Constants (expo-constants).",
]);
```

**Comment by dariocostanzo** [comment]
> Hello, at several react navigation files i see the code: global.__expo and expo SDK 40 gives a warning that it is deprecated.
> 
> > Your project is accessing the following APIs from a deprecated global rather than a module import: Constants (expo-constants).
> > The global "__expo" and "Expo" objects will be removed in SDK 41. Learn more about how to fix this warning: https://expo.fyi/deprecated-globals
> 
> "@react-navigation/material-bottom-tabs": "^5.3.10",
> "@react-navigation/material-top-tabs": "^5.3.10",
> "@react-navigation/native": "^5.8.10",
> "@react-navigation/stack": "^5.12.8",

Hi, did you manage to fix it? I can't find a solution

**Comment by GusMartins499** [comment]
> It's just a warning, so there's nothing to fix. But if you update to Expo SDK 41, react-navigation will be incompatible. If you intend to continue using react-navigation, don't update to SDK 41 until react-navigation is.
> 
> If you want to suppress the warnings in the meantime you can use this:
> 
> ```
> import { LogBox } from "react-native";
> 
> LogBox.ignoreLogs([
>   "Your project is accessing the following APIs from a deprecated global rather than a module import: Constants (expo- constants).",
> ]);
> ```

Hi, my name is Gustavo, i'm from Brazil and i'm not fluent english yet. I have the same problem, but, i'm not understand your resolution, where i put the this code ? thank you.

**Comment by GusMartins499** [comment]
> I'm receiving the same warning, specifically when using the `SafeAreaView` component. There is a lot of usage of the global expo object in react-navigation's library.
> 
> "expo": "~40.0.0",
> "react-navigation": "^4.4.3"

Me too, but now is not work `SafeAreaView` :(

**Comment by dariocostanzo** [comment]
> > I'm receiving the same warning, specifically when using the `SafeAreaView` component. There is a lot of usage of the global expo object in react-navigation's library.
> > "expo": "~40.0.0",
> > "react-navigation": "^4.4.3"
> 
> Me too, but now is not work `SafeAreaView` :(

You can do the followings:
1) Upgrade your version of react native paper, I have chosen the latest one 4.5.0 (_this worked for me_): 
npm install react-native-paper@4.5.0`
`
2) import { SafeAreaView } from 'react-native-safe-area-context'; (_I haven't tried this, but someone said it worked_)
Have a look here: https://github.com/th3rdwave/react-native-safe-area-context

3) Follow this [link ](https://github.com/expo/fyi/blob/master/deprecated-globals.m) if you are using the global **__expo** and **Expo** in your codebase.

**Comment by GusMartins499** [comment]
> > > I'm receiving the same warning, specifically when using the `SafeAreaView` component. There is a lot of usage of the global expo object in react-navigation's library.
> > > "expo": "~40.0.0",
> > > "react-navigation": "^4.4.3"
> > 
> > 
> > Me too, but now is not work `SafeAreaView` :(
> 
> You can do the followings:
> 
> 1. Upgrade your version of react native paper, I have chosen the latest one 4.5.0 (_this worked for me_):
>    `npm install react-native-paper@4.5.0`
> 2. `import { SafeAreaView } from 'react-native-safe-area-context';` (_I haven't tried this, but someone said it worked_)
> 3. Follow this [link ](https://github.com/expo/fyi/blob/master/deprecated-globals.m) if you are using the global **__expo** and **Expo** in your codebase.

Hi, this works.

before:

![before](https://user-images.githubusercontent.com/43645525/103773925-8d924300-500a-11eb-84af-f9b284e88ea0.png)

after:

![after2](https://user-images.githubusercontent.com/43645525/103773957-95ea7e00-500a-11eb-9659-e9da52710a73.png)

the link returns error 404 - page not found.

I'm not using react-native-paper, i don't know what it is. It's use to desgin ?

**Comment by dariocostanzo** [comment]
> > > > I'm receiving the same warning, specifically when using the `SafeAreaView` component. There is a lot of usage of the global expo object in react-navigation's library.
> > > > "expo": "~40.0.0",
> > > > "react-navigation": "^4.4.3"
> > > 
> > > 
> > > Me too, but now is not work `SafeAreaView` :(
> > 
> > 
> > You can do the followings:
> > 
> > 1. Upgrade your version of react native paper, I have chosen the latest one 4.5.0 (_this worked for me_):
> >    `npm install react-native-paper@4.5.0`
> > 2. `import { SafeAreaView } from 'react-native-safe-area-context';` (_I haven't tried this, but someone said it worked_)
> > 3. Follow this [link ](https://github.com/expo/fyi/blob/master/deprecated-globals.m) if you are using the global **__expo** and **Expo** in your codebase.
> 
> Hi, this works.
> 
> before:
> 
> ![before](https://user-images.githubusercontent.com/43645525/103773925-8d924300-500a-11eb-84af-f9b284e88ea0.png)
> 
> after:
> 
> ![after2](https://user-images.githubusercontent.com/43645525/103773957-95ea7e00-500a-11eb-9659-e9da52710a73.png)
> 
> the link returns error 404 - page not found.
> 
> I'm not using react-native-paper, i don't know what it is. It's use to desgin ?

I mentioned react-native-paper because after upgrading it I got rid of the warning, however, you probably have it, check your package.json.

Regarding `SafeAreaView`, the only thing I understood by reading [here](https://github.com/expo/expo-cli/issues/3022#issuecomment-754897791) is that you no longer need to import it from `react-native` but from 'react-native-safe-area-context' instead. I am sorry, I can't tell you more as I haven't tried it and I don't use it.

**Comment by GusMartins499** [comment]
> > > > > I'm receiving the same warning, specifically when using the `SafeAreaView` component. There is a lot of usage of the global expo object in react-navigation's library.
> > > > > "expo": "~40.0.0",
> > > > > "react-navigation": "^4.4.3"
> > > > 
> > > > 
> > > > Me too, but now is not work `SafeAreaView` :(
> > > 
> > > 
> > > You can do the followings:
> > > 
> > > 1. Upgrade your version of react native paper, I have chosen the latest one 4.5.0 (_this worked for me_):
> > >    `npm install react-native-paper@4.5.0`
> > > 2. `import { SafeAreaView } from 'react-native-safe-area-context';` (_I haven't tried this, but someone said it worked_)
> > > 3. Follow this [link ](https://github.com/expo/fyi/blob/master/deprecated-globals.m) if you are using the global **__expo** and **Expo** in your codebase.
> > 
> > 
> > Hi, this works.
> > before:
> > ![before](https://user-images.githubusercontent.com/43645525/103773925-8d924300-500a-11eb-84af-f9b284e88ea0.png)
> > after:
> > ![after2](https://user-images.githubusercontent.com/43645525/103773957-95ea7e00-500a-11eb-9659-e9da52710a73.png)
> > the link returns error 404 - page not found.
> > I'm not using react-native-paper, i don't know what it is. It's use to desgin ?
> 
> I mentioned react-native-paper because after upgrading it I got rid of the warning, however, you probably have it, check your package.json.
> 
> Regarding `SafeAreaView`, the only thing I understood by reading [here](https://github.com/expo/expo-cli/issues/3022#issuecomment-754897791) is that you no longer need to import it from `react-native` but from 'react-native-safe-area-context' instead. I am sorry, I can't tell you more as I haven't tried it and I don't use it.

I have installed `react-native-paper` because I am following the steps you said. I now have `react-native-paper` in my package.json. I understand that you can tell me more about `SafeAreaView`. Thank you very much. I am going to study about react-native-paper, maybe it will help me in something.

**Comment by chefk5** [comment]
Will React Navigation 4 get an update regarding the usage of expo constants? Or should we upgrade to v5?

**Comment by Jevgeni-i-am** [comment]
"react-navigation-drawer": "^2.7.0" gives me same issue. Did somebody done with this?

```
Your project is accessing the following APIs from a deprecated global rather than a module import: Constants (expo-constants).

The global "__expo" and "Expo" objects will be removed in SDK 41. Learn more about how to fix this warning: https://expo.fyi/deprecated-globals

at node_modules\react-native\Libraries\LogBox\LogBox.js:117:10 in registerWarning
at node_modules\react-native\Libraries\LogBox\LogBox.js:63:8 in warnImpl
at node_modules\react-native\Libraries\LogBox\LogBox.js:36:4 in console.warn
at node_modules\expo\build\environment\react-native-logs.fx.js:18:4 in warn
```
