### ISSUE TITLE
TypeError: _reactNative.Linking.removeEventListener is not a function

### ISSUE THREAD

**Issue by oxilor** [react-navigation/react-navigation#9183]
Repo: https://github.com/oxilor/react-navigation-jest-bug
When I run jest I have the following error:
```
TypeError: _reactNative.Linking.removeEventListener is not a function
    at /Users/oxilor/WebstormProjects/os-team/apps/englika/ReactNavigationJestBug/node_modules/@react-navigation/native/lib/commonjs/useLinking.native.tsx:33:28
    at commitHookEffectListUnmount (/Users/oxilor/WebstormProjects/os-team/apps/englika/ReactNavigationJestBug/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10324:11)
    at commitPassiveHookEffects (/Users/oxilor/WebstormProjects/os-team/apps/englika/ReactNavigationJestBug/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10382:11)
    at Object.invokeGuardedCallbackImpl (/Users/oxilor/WebstormProjects/os-team/apps/englika/ReactNavigationJestBug/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9897:10)
    at invokeGuardedCallback (/Users/oxilor/WebstormProjects/os-team/apps/englika/ReactNavigationJestBug/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10073:31)
    at flushPassiveEffectsImpl (/Users/oxilor/WebstormProjects/os-team/apps/englika/ReactNavigationJestBug/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13345:9)
    at unstable_runWithPriority (/Users/oxilor/WebstormProjects/os-team/apps/englika/ReactNavigationJestBug/node_modules/scheduler/cjs/scheduler.development.js:653:12)
    at runWithPriority (/Users/oxilor/WebstormProjects/os-team/apps/englika/ReactNavigationJestBug/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1775:10)
    at flushPassiveEffects (/Users/oxilor/WebstormProjects/os-team/apps/englika/ReactNavigationJestBug/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13312:12)
    at /Users/oxilor/WebstormProjects/os-team/apps/englika/ReactNavigationJestBug/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13191:11
```
If the `App.tsx` file does not use the `react-navigation`, then jest works without errors and the snapshot is created. Otherwise, the error appears.

**Note**
This repo is an empty react-native project created by `npx react-native init MyApp --template react-native-template-typescript`.

| software                       | version |
| ------------------------------ | ------- |
| @react-navigation/native       | 5.8.10
| react-native                   | 0.63.3
| node                           | 15.4.0

**Comment by phuochau** [comment]
I have the same problem

**Comment by dupuysylvain** [comment]
Same problem after upgrading expo sdk to 40 : 


software | version
-- | --
@react-navigation/native | 5.7.1
react-native | 0.63.3
node | 14.15.3

**Comment by zrhythm** [comment]
Same issue when upgrading @react-navigation/native from 5.1.5 to 5.8.10


software | version
-- | --
@react-navigation/native | 5.8.10
react-native | 0.63.3

**Comment by satya164** [comment]
Fixed in https://github.com/react-navigation/react-navigation/commit/b26b90706fe0a0d914d4a868df1310d2dc3a7623

**Comment by metelskyy** [comment]
when i have updated expo from 44 to 49 i got this err, and updating of all navigation packages solved this err for me
