### ISSUE TITLE
Can't run `yarn install` on Mac

### ISSUE THREAD

**Issue by AlastairTaft** [react-navigation/react-navigation#9352]
**Current Behavior**

Clone the repo and run `yarn install`. I get the following error message on Mac (version details below).

```sh
[4/4] 🔨  Building fresh packages...
[6/11] ⠄ nodemon
[2/11] ⠄ husky
[-/11] ⠄ waiting...
[4/11] ⠄ fsevents
error /Users/alastairtaft/projects/react-navigation/node_modules/playwright: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /Users/alastairtaft/projects/react-navigation/node_modules/playwright
Output:
/Users/alastairtaft/projects/react-navigation/node_modules/playwright-core/lib/helper.js:288
        throw new Error(message);
              ^

Error: Unsupported platform for chromium: mac11.1
    at Object.assert (/Users/alastairtaft/projects/react-navigation/node_modules/playwright-core/lib/helper.js:288:15)
    at Object.executablePath (/Users/alastairtaft/projects/react-navigation/node_modules/playwright-core/lib/server/browserFetcher.js:130:14)
    at downloadOptionsFromENV (/Users/alastairtaft/projects/react-navigation/node_modules/playwright-core/download-browser.js:45:36)
    at /Users/alastairtaft/projects/react-navigation/node_modules/playwright/install.js:21:40
    at Object.<anonymous> (/Users/alastairtaft/projects/react-navigation/node_modules/playwright/install.js:24:3)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
```

**Expected Behavior**

All dependencies should install.

**How to reproduce**

I'm on Mac with an M1 chip. OS version 11.1

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| @react-navigation/native       | Latest on `main` branch
| node                           | node v15.7.0
| npm or yarn                    | yarn v1.18.0

**Comment by chrisjlan89** [comment]
Having a similar issues on M1
