### ISSUE TITLE
JEST breaks with "Unexpected token import" after calling "createStackNavigator()" anywhere inside react native app

### ISSUE THREAD

**Issue by christian-hess-invillia-tembici** [react-navigation/react-navigation#9488]
**Current Behavior**

- I'm running a simple react-native app with typescript template. There are only 2 tests, one of them renders the <app>. The code works fine until I import and call "createStackNavvigator()". It literally breaks even if I don't actually use it in the component itself. The video below shows it best, sorry for handheld and vertical:

https://user-images.githubusercontent.com/78170721/114053229-241e0c80-9865-11eb-916f-273206e17f47.mp4

Full error message:
```
/Users/christian.hess/Desktop/Repositorios/AppTest/node_modules/react-native-iphone-x-helper/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { Dimensions, Platform, StatusBar } from 'react-native';
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (node_modules/@react-navigation/stack/lib/commonjs/TransitionConfigs/CardStyleInterpolators.tsx:2:1)
```
I've tried adding many transformIgnorePatterns to the jest configuration, but the error always changes to the following:
```
/Users/christian.hess/Desktop/Repositorios/AppTest/node_modules/@react-native/polyfills/error-guard.js:14
    type ErrorHandler = (error: mixed, isFatal: boolean) => void;
         ^^^^^^^^^^^^

    SyntaxError: Unexpected identifier

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (node_modules/react-native/jest/setup.js:439:6)
```
**Expected Behavior**

- The test shouldn't break if I simply call createStackNavigator();

**How to reproduce**
- Clone and follow readme @ https://github.com/christian-hess-94/repro-jest-bug
OR

- Create a new app with `npx react-native init MyApp --template react-native-template-typescript`
- Add @react-navigation/native and @react-navigation/stack with yarn or npm
- Follow the installation instructions and setup with jest: https://reactnavigation.org/docs/getting-started & https://reactnavigation.org/docs/testing
- import NavigationContainer and wrap the entire app with it.
- run "yarn test" or "npm test" while only having the default App-test.tsx that comes with the project. It should pass.
- import and call createStackNavigator() and the test should break.

**Your Environment**
- I'm not using expo
- node: 14.15.5
- yarn: 1.22.10
Package.json (incluiding jest configurations):
```json
{
  "name": "AppTest",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx"
  },
  "dependencies": {
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.4",
    "react": "17.0.1",
    "react-native": "0.64.0",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-reanimated": "^2.1.0",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^3.1.0",
    "ts-jest": "^26.5.4"
  },
  "devDependencies": {
    "@babel/core": "^7.13.14",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "@types/jest": "^26.0.20",
    "@types/react-native": "^0.64.0",
    "@types/react-test-renderer": "^16.9.2",
    "babel-jest": "^26.6.3",
    "eslint": "^7.14.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.65.2",
    "react-test-renderer": "17.0.1",
    "typescript": "^3.8.3"
  },
  "resolutions": {
    "@types/react": "^17"
  },
  "jest": {
    "preset": "react-native",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ],
    "setupFiles": [
      "<rootDir>/jest/setup.js"
    ]
  }
}
```

jest/setup.js:
```js
import 'react-native-gesture-handler/jestSetup';
jest.useFakeTimers();
jest.mock('react-native-reanimated', () => {
  const Reanimated = require('react-native-reanimated/mock');

  // The mock for `call` immediately calls the callback which is incorrect
  // So we override it with a no-op
  Reanimated.default.call = () => {};

  return Reanimated;
});

// Silence the warning: Animated: `useNativeDriver` is not supported because the native animated module is missing
jest.mock('react-native/Libraries/Animated/NativeAnimatedHelper'); 
//This line is different, missing the src folder inside the path as it no longer exists. I've created a PR addressing this issue in the documentation: https://github.com/react-navigation/react-navigation.github.io/pull/969
```

**Comment by christian-hess-invillia-tembici** [comment]
Added repo link for easy reproduction:
https://github.com/christian-hess-94/repro-jest-bug

**Comment by christian-hess-invillia-tembici** [comment]
@satya164 any news on this? I've posted the repro

**Comment by christian-hess-invillia-tembici** [comment]
reopening as this was never addressed and ignored
