### ISSUE TITLE
React-Native-CLI project breaks when adding react-navigation/native in android build

### ISSUE THREAD

**Issue by Mahern-13** [react-navigation/react-navigation#9656]
**Current Behavior**

- Currently running react native 0.64 with Hermes enabled
- The app builds successfully for ios with Xcode and renders in the android emulator but breaks in the terminal

**Expected Behavior**

- npx react-native run-android should not error out in the terminal

**How to reproduce**

- Make new react native app with typescript template
- Add react-navigation/native with dependencies
- Run coco pods to fix ios
- Run ios successfully
- clean the Gradle build
- npx react-native run-android produces error
- I have tried deleting the node packages and running them again
- I have tried running npx jetify
- Unable to clear the console errors
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-community_masked-view:generateDebugRFile'.
> Could not resolve all files for configuration ':react-native-community_masked-view:debugCompileClasspath'.
   > Could not resolve androidx.appcompat:appcompat:1.0.2.
     Required by:
         project :react-native-community_masked-view > com.facebook.react:react-native:0.64.1
      > Could not resolve androidx.appcompat:appcompat:1.0.2.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/androidx/appcompat/appcompat/1.0.2/appcompat-1.0.2.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/androidx/appcompat/appcompat/1.0.2/appcompat-1.0.2.pom'.
               > dl.google.com
      > Could not resolve androidx.appcompat:appcompat:1.0.2.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/androidx/appcompat/appcompat/1.0.2/appcompat-1.0.2.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/androidx/appcompat/appcompat/1.0.2/appcompat-1.0.2.pom'.
               > dl.google.com
      > Could not resolve androidx.appcompat:appcompat:1.0.2.
         > Could not get resource 'https://jcenter.bintray.com/androidx/appcompat/appcompat/1.0.2/appcompat-1.0.2.pom'.
            > Could not GET 'https://jcenter.bintray.com/androidx/appcompat/appcompat/1.0.2/appcompat-1.0.2.pom'.
               > jcenter.bintray.com
      > Could not resolve androidx.appcompat:appcompat:1.0.2.
         > Could not get resource 'https://www.jitpack.io/androidx/appcompat/appcompat/1.0.2/appcompat-1.0.2.pom'.
            > Could not GET 'https://www.jitpack.io/androidx/appcompat/appcompat/1.0.2/appcompat-1.0.2.pom'.
               > www.jitpack.io: nodename nor servname provided, or not known
      > Could not resolve androidx.appcompat:appcompat:1.0.2.
         > Could not get resource 'https://jcenter.bintray.com/androidx/appcompat/appcompat/1.0.2/appcompat-1.0.2.pom'.
            > Could not GET 'https://jcenter.bintray.com/androidx/appcompat/appcompat/1.0.2/appcompat-1.0.2.pom'.
               > jcenter.bintray.com
      > Could not resolve androidx.appcompat:appcompat:1.0.2.
         > Could not get resource 'https://jitpack.io/androidx/appcompat/appcompat/1.0.2/appcompat-1.0.2.pom'.
            > Could not GET 'https://jitpack.io/androidx/appcompat/appcompat/1.0.2/appcompat-1.0.2.pom'.
               > jitpack.io
   > Could not resolve androidx.versionedparcelable:versionedparcelable:1.0.0.
     Required by:
         project :react-native-community_masked-view > androidx.core:core:1.0.0
      > Could not resolve androidx.versionedparcelable:versionedparcelable:1.0.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/androidx/versionedparcelable/versionedparcelable/1.0.0/versionedparcelable-1.0.0.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/androidx/versionedparcelable/versionedparcelable/1.0.0/versionedparcelable-1.0.0.pom'.
               > dl.google.com
      > Could not resolve androidx.versionedparcelable:versionedparcelable:1.0.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/androidx/versionedparcelable/versionedparcelable/1.0.0/versionedparcelable-1.0.0.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/androidx/versionedparcelable/versionedparcelable/1.0.0/versionedparcelable-1.0.0.pom'.
               > dl.google.com
      > Could not resolve androidx.versionedparcelable:versionedparcelable:1.0.0.
         > Could not get resource 'https://jcenter.bintray.com/androidx/versionedparcelable/versionedparcelable/1.0.0/versionedparcelable-1.0.0.pom'.
            > Could not GET 'https://jcenter.bintray.com/androidx/versionedparcelable/versionedparcelable/1.0.0/versionedparcelable-1.0.0.pom'.
               > jcenter.bintray.com
      > Could not resolve androidx.versionedparcelable:versionedparcelable:1.0.0.
         > Could not get resource 'https://www.jitpack.io/androidx/versionedparcelable/versionedparcelable/1.0.0/versionedparcelable-1.0.0.pom'.
            > Could not GET 'https://www.jitpack.io/androidx/versionedparcelable/versionedparcelable/1.0.0/versionedparcelable-1.0.0.pom'.
               > www.jitpack.io
      > Could not resolve androidx.versionedparcelable:versionedparcelable:1.0.0.
         > Could not get resource 'https://jcenter.bintray.com/androidx/versionedparcelable/versionedparcelable/1.0.0/versionedparcelable-1.0.0.pom'.
            > Could not GET 'https://jcenter.bintray.com/androidx/versionedparcelable/versionedparcelable/1.0.0/versionedparcelable-1.0.0.pom'.
               > jcenter.bintray.com
      > Could not resolve androidx.versionedparcelable:versionedparcelable:1.0.0.
         > Could not get resource 'https://jitpack.io/androidx/versionedparcelable/versionedparcelable/1.0.0/versionedparcelable-1.0.0.pom'.
            > Could not GET 'https://jitpack.io/androidx/versionedparcelable/versionedparcelable/1.0.0/versionedparcelable-1.0.0.pom'.
               > jitpack.io

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5m 0s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-community_masked-view:generateDebugRFile'.
> Could not resolve all files for configuration ':react-native-community_masked-view:debugCompileClasspath'.
   > Could not resolve androidx.appcompat:appcompat:1.0.2.
     Required by:
         project :react-native-community_masked-view > com.facebook.react:react-native:0.64.1
      > Could not resolve androidx.appcompat:appcompat:1.0.2.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/androidx/appcompat/appcompat/1.0.2/appcompat-1.0.2.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/androidx/appcompat/appcompat/1.0.2/appcompat-1.0.2.pom'.
               > dl.google.com
      > Could not resolve androidx.appcompat:appcompat:1.0.2.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/androidx/appcompat/appcompat/1.0.2/appcompat-1.0.2.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/androidx/appcompat/appcompat/1.0.2/appcompat-1.0.2.pom'.
               > dl.google.com
      > Could not resolve androidx.appcompat:appcompat:1.0.2.
         > Could not get resource 'https://jcenter.bintray.com/androidx/appcompat/appcompat/1.0.2/appcompat-1.0.2.pom'.
            > Could not GET 'https://jcenter.bintray.com/androidx/appcompat/appcompat/1.0.2/appcompat-1.0.2.pom'.
               > jcenter.bintray.com
      > Could not resolve androidx.appcompat:appcompat:1.0.2.
         > Could not get resource 'https://www.jitpack.io/androidx/appcompat/appcompat/1.0.2/appcompat-1.0.2.pom'.
            > Could not GET 'https://www.jitpack.io/androidx/appcompat/appcompat/1.0.2/appcompat-1.0.2.pom'.
               > www.jitpack.io: nodename nor servname provided, or not known
      > Could not resolve androidx.appcompat:appcompat:1.0.2.
         > Could not get resource 'https://jcenter.bintray.com/androidx/appcompat/appcompat/1.0.2/appcompat-1.0.2.pom'.
            > Could not GET 'https://jcenter.bintray.com/androidx/appcompat/appcompat/1.0.2/appcompat-1.0.2.pom'.
               > jcenter.bintray.com
      > Could not resolve androidx.appcompat:appcompat:1.0.2.
         > Could not get resource 'https://jitpack.io/androidx/appcompat/appcompat/1.0.2/appcompat-1.0.2.pom'.
            > Could not GET 'https://jitpack.io/androidx/appcompat/appcompat/1.0.2/appcompat-1.0.2.pom'.
               > jitpack.io
   > Could not resolve androidx.versionedparcelable:versionedparcelable:1.0.0.
     Required by:
         project :react-native-community_masked-view > androidx.core:core:1.0.0
      > Could not resolve androidx.versionedparcelable:versionedparcelable:1.0.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/androidx/versionedparcelable/versionedparcelable/1.0.0/versionedparcelable-1.0.0.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/androidx/versionedparcelable/versionedparcelable/1.0.0/versionedparcelable-1.0.0.pom'.
               > dl.google.com
      > Could not resolve androidx.versionedparcelable:versionedparcelable:1.0.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/androidx/versionedparcelable/versionedparcelable/1.0.0/versionedparcelable-1.0.0.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/androidx/versionedparcelable/versionedparcelable/1.0.0/versionedparcelable-1.0.0.pom'.
               > dl.google.com
      > Could not resolve androidx.versionedparcelable:versionedparcelable:1.0.0.
         > Could not get resource 'https://jcenter.bintray.com/androidx/versionedparcelable/versionedparcelable/1.0.0/versionedparcelable-1.0.0.pom'.
            > Could not GET 'https://jcenter.bintray.com/androidx/versionedparcelable/versionedparcelable/1.0.0/versionedparcelable-1.0.0.pom'.
               > jcenter.bintray.com
      > Could not resolve androidx.versionedparcelable:versionedparcelable:1.0.0.
         > Could not get resource 'https://www.jitpack.io/androidx/versionedparcelable/versionedparcelable/1.0.0/versionedparcelable-1.0.0.pom'.
            > Could not GET 'https://www.jitpack.io/androidx/versionedparcelable/versionedparcelable/1.0.0/versionedparcelable-1.0.0.pom'.
               > www.jitpack.io
      > Could not resolve androidx.versionedparcelable:versionedparcelable:1.0.0.
         > Could not get resource 'https://jcenter.bintray.com/androidx/versionedparcelable/versionedparcelable/1.0.0/versionedparcelable-1.0.0.pom'.
            > Could not GET 'https://jcenter.bintray.com/androidx/versionedparcelable/versionedparcelable/1.0.0/versionedparcelable-1.0.0.pom'.
               > jcenter.bintray.com
      > Could not resolve androidx.versionedparcelable:versionedparcelable:1.0.0.
         > Could not get resource 'https://jitpack.io/androidx/versionedparcelable/versionedparcelable/1.0.0/versionedparcelable-1.0.0.pom'.
            > Could not GET 'https://jitpack.io/androidx/versionedparcelable/versionedparcelable/1.0.0/versionedparcelable-1.0.0.pom'.
               > jitpack.io

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5m 0s

    at makeError (/Users/ryanahern/dev/soiree/node_modules/execa/index.js:174:9)
    at /Users/ryanahern/dev/soiree/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/ryanahern/dev/soiree/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:5)
    at async Command.handleAction (/Users/ryanahern/dev/soiree/node_modules/@react-native-community/cli/build/index.js:186:9)
```

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       | latest
| react-native                   | 0.64
| expo                           | react-native-cli
| node                           | 16
| npm or yarn                    | latest

**Comment by satya164** [comment]
Please open the issue in masked view repo. It's a dependency, but we don't maintain the library.

**Comment by numboDumbo** [comment]
It is failing for me also with
    "@react-navigation/bottom-tabs": "^6.0.9",
    "@react-navigation/native": "^6.0.6",
    "react": "17.0.2",
    "react-native": "0.66.4",
    "react-native-safe-area-context": "^3.3.2",
    "react-native-screens": "^3.10.1",
    "react-redux": "^7.2.6",
    "redux": "^4.1.2"
