### ISSUE TITLE
React Native Testing Library console.error

### ISSUE THREAD

**Issue by henrymoulton** [react-navigation/react-navigation#9701]
**Current Behavior**

- What code are you running and what is happening?

Rendering a Navigator 

```
it("...", async () => {
    const { Screen, Navigator } = createStackNavigator();

    const AppNavigator = () => {
      return (
        <Navigator>
          <Screen name="Screen" component={Screen} />
        </Navigator>
      );
    };

    const component = (
      <NavigationContainer>
        <AppNavigator />
      </NavigationContainer>
    );

    const { getByTestId, findByText } = render(component, { wrapper: AllTheProviders });

   ....
```

by default gives the console.error:

```
console.error
    Warning: An update to CardContainer inside a test was not wrapped in act(...).
    
    When testing, code that causes React state updates should be wrapped into act(...):
    
    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */
    
    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
        at CardContainer
        at RNSScreen
        at construct (/Users/henrymoulton/app/node_modules/react-native/jest/setup.js:332:22)
        at construct (/Users/henrymoulton/app/node_modules/react-native/Libraries/Animated/createAnimatedComponent.js:42:43)
        at AnimatedComponentWrapper
        at construct (/Users/henrymoulton/app/node_modules/react-native-screens/lib/commonjs/index.native.tsx:101:51)
        at MaybeScreen
        at RNSScreenContainer
        at construct (/Users/henrymoulton/app/node_modules/react-native/jest/setup.js:332:22)
        at construct (/Users/henrymoulton/app/node_modules/react-native-screens/lib/commonjs/index.native.js:213:34)
        at MaybeScreenContainer
        at construct (/Users/henrymoulton/app/node_modules/@react-navigation/stack/lib/commonjs/views/Stack/CardStack.tsx:288:29)
        at construct (/Users/henrymoulton/app/node_modules/@react-navigation/stack/lib/commonjs/views/KeyboardManager.tsx:15:69)
        at SafeAreaConsumer
        at SafeAreaConsumer
        at SafeAreaProviderCompat
        at View
        at construct (/Users/henrymoulton/app/node_modules/react-native/jest/mockComponent.js:28:18)
        at construct (/Users/henrymoulton/app/node_modules/@react-navigation/stack/lib/commonjs/views/Stack/StackView.tsx:59:70)
        at StackNavigator
        at AppNavigator
        at EnsureSingleNavigator
        at BaseNavigationContainer
        at ThemeProvider
        at NavigationContainer
        at ToastProvider
        at SafeAreaProvider
        at Provider
        at AllTheProviders

      at printWarning (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:68:30)
      at error (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:44:5)
      at warnIfNotCurrentlyActingUpdatesInDev (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15034:9)
      at setPointerEvents (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7129:9)
      at Object.<anonymous> (node_modules/@react-navigation/stack/lib/commonjs/views/Stack/CardContainer.tsx:190:9)
      at AnimatedInterpolation.__callListeners (node_modules/react-native/Libraries/Animated/nodes/AnimatedNode.js:139:7)
      at AnimatedInterpolation.__callListeners (node_modules/react-native/Libraries/Animated/nodes/AnimatedWithChildren.js:76:5)
```

This can be fixed by mocking react-native-screens with the mock:

```
import { View } from "react-native";

export const enableScreens = jest.fn();
export const screensEnabled = jest.fn().mockReturnValue(false);
export const ScreenContainer = View;
```

It might be a good idea to add this to the https://reactnavigation.org/docs/testing/ doc?

**Expected Behavior**

- What do you expect should be happening?

No console.error

**How to reproduce**

Issue is outlined here:

https://github.com/callstack/react-native-testing-library/issues/750

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | test environment
| @react-navigation/native       | ^5.9.4
| @react-navigation/stack        | ^5.14.5
| react-native-gesture-handler   | ^1.10.3
| react-native-safe-area-context | ^3.2.0
| react-native-screens           | ^3.2.0
| react-native                   | 0.64.1

**Comment by ajsmth** [comment]
Hey there- thanks for this! I was able to reproduce but unable to fix with the suggestion you provided - are you sure this is the only thing you've changed? can you provide a more thorough repro? The testing docs do seem a bit out of date at the moment, thanks for suggesting

**Comment by henrymoulton** [comment]
@ajsmth sorry the fix is actually by changing the navigators to not use animations.

when rendering therefore:

```
export const STOP_JEST_TEST_WARNING = { animationEnabled: false };

const AppNavigator = () => {
    return (
      <Navigator screenOptions={STOP_JEST_TEST_WARNING}>
        <>
          {screensWithConfig.map(({ screen, initialParams, name }) => (
            <Screen
              key={name ?? screen.name}
              name={name ?? screen.name}
              component={screen}
              initialParams={initialParams}
            />
          ))}
        </>
      </Navigator>
    );
  };
```

Does remove the error. However this is not ideal if I want to just pass in a Navigator I will still get the errors. Ideally React Navigation would stop these Jest warnings for users.

**Comment by henrymoulton** [comment]
updated stack trace:

```
console.error
Warning: An update to CardContainer inside a test was not wrapped in act(...).

    When testing, code that causes React state updates should be wrapped into act(...):

act(() => {
    /* fire events that update state */
});
/* assert on the output */

This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
at CardContainer
at View
at construct (app/node_modules/react-native/jest/mockComponent.js:28:18)
at MaybeScreen
at View
at construct (app/node_modules/react-native/jest/mockComponent.js:28:18)
at MaybeScreenContainer
at construct (app/node_modules/@react-navigation/stack/lib/commonjs/views/Stack/CardStack.tsx:288:29)
at construct (app/node_modules/@react-navigation/stack/lib/commonjs/views/KeyboardManager.tsx:15:69)
at SafeAreaConsumer
at SafeAreaConsumer
at SafeAreaProviderCompat
at View
at construct (app/node_modules/react-native/jest/mockComponent.js:28:18)
at construct (app/node_modules/@react-navigation/stack/lib/commonjs/views/Stack/StackView.tsx:59:70)
at StackNavigator
at fn (app/src/navigation/onboarding-open-banking/onboarding-open-banking-navigator.tsx:19:3)
at StaticContainer
at EnsureSingleNavigator
at SceneView
at View
at construct (app/node_modules/react-native/jest/mockComponent.js:28:18)
at View
at construct (app/node_modules/react-native/jest/mockComponent.js:28:18)
at View
at construct (app/node_modules/react-native/jest/mockComponent.js:28:18)
at CardSheet
at View
at construct (app/node_modules/react-native/jest/mockComponent.js:28:18)
at construct (app/node_modules/react-native/Libraries/Animated/createAnimatedComponent.js:42:43)
at AnimatedComponentWrapper
at construct (app/node_modules/react-native-gesture-handler/lib/commonjs/handlers/createHandler.ts:196:51)
at fn (app/node_modules/@react-navigation/stack/lib/commonjs/views/GestureHandlerNative.tsx:9:22)
at View
at construct (app/node_modules/react-native/jest/mockComponent.js:28:18)
at construct (app/node_modules/react-native/Libraries/Animated/createAnimatedComponent.js:42:43)
at AnimatedComponentWrapper
at View
at construct (app/node_modules/react-native/jest/mockComponent.js:28:18)
at construct (app/node_modules/@react-navigation/stack/lib/commonjs/views/Stack/Card.tsx:91:58)
at CardContainer
at View
at construct (app/node_modules/react-native/jest/mockComponent.js:28:18)
at MaybeScreen
at View
at construct (app/node_modules/react-native/jest/mockComponent.js:28:18)
at MaybeScreenContainer
at construct (app/node_modules/@react-navigation/stack/lib/commonjs/views/Stack/CardStack.tsx:288:29)
at construct (app/node_modules/@react-navigation/stack/lib/commonjs/views/KeyboardManager.tsx:15:69)
at SafeAreaConsumer
at SafeAreaConsumer
at SafeAreaProviderCompat
at View
at construct (app/node_modules/react-native/jest/mockComponent.js:28:18)
at construct (app/node_modules/@react-navigation/stack/lib/commonjs/views/Stack/StackView.tsx:59:70)
at StackNavigator
at AppNavigator
at EnsureSingleNavigator
at BaseNavigationContainer
at ThemeProvider
at NavigationContainer
at TestScreensSetup
at ToastProvider
at SafeAreaProvider
at Provider
at AllTheProviders
```

**Comment by henrymoulton** [comment]
Will see if exists in v6
