### ISSUE TITLE
getting "TypeError: Cannot read property 'add' of undefined" error on running jest

### ISSUE THREAD

**Issue by JaioSkura** [react-navigation/react-navigation#9865]
### Current behavior

I am getting the following error in a test with jest:

TypeError: Cannot read property 'add' of undefined

      at Object.<anonymous> (node_modules/@react-navigation/stack/lib/commonjs/utils/conditional.tsx:3:7)
      at Object.<anonymous> (node_modules/@react-navigation/stack/lib/commonjs/TransitionConfigs/CardStyleInterpolators.tsx:3:1)`

jest.config.js
```module.exports = {
  preset: 'react-native',
  setupFiles: ['./node_modules/react-native-gesture-handler/jestSetup.js'],
  transformIgnorePatterns: [
    'node_modules/(?!(jest-)?@?react-native|@react-native-community|@react-navigation)',
  ],
  testMatch: [
    '**/__tests__/**/*.js?(x)',
    '**/__tests__/**/*.ts?(x)',
    '**/?(*.)(spec|test).js?(x)',
    '**/?(*.)(spec|test).ts?(x)',
  ],
  moduleNameMapper: {
    'react-dom': 'react-native',
  },
};
```

package.json:

```
...
 "@react-navigation/native": "^5.9.4",
 "@react-navigation/stack": "^5.14.5",
 "react": "17.0.1",
 "react-native": "0.64.1",
...
```

Similar problem in closed issue:  #8856

Any fix for this?

Thanks in advance!

### Expected behavior

Run test succesfully.

### Reproduction

app-test.js

### Platform

- [ ] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |5.9.4
| @react-navigation/stack                |5.14.5
| react-native                           |0.64.1
| node                                   |
| npm or yarn                            |

**Comment by JaioSkura** [comment]
> Hey! Thanks for opening the issue. The issue doesn't seem to contain a link to a repro (a [snack.expo.dev](https://snack.expo.dev) link or link to a GitHub repo under your username).
> 
> Can you provide a [minimal repro](https://stackoverflow.com/help/minimal-reproducible-example) which demonstrates the issue? A repro will help us debug the issue faster. Please try to keep the repro as small as possible and make sure that we can run it without additional setup.

Cannot make the project public sorry, but can share with you concrete parts of course. What do you exactly need. I am trying to test the default App-test.js of react native project, where the App is created from a simple stack creator:

```
import React from "react";
import { NavigationContainer } from "@react-navigation/native";
import { createStackNavigator } from "@react-navigation/stack";
import NavigatorService from './navigatorService'
import HomeScreen from '../ui/screens/homeScreen';
import RegulatorsDataScreen from '../ui/screens/regulatorsDataScreen'
import {VIEWS} from './views';


const Stack = createStackNavigator();
export default function App() {
  return (
    <NavigationContainer ref={navigatorRef => { NavigatorService.setContainer(navigatorRef); }}>
      <Stack.Navigator initialRouteName={VIEWS.HOME} headerMode="none">
        <Stack.Screen name={VIEWS.HOME} component={HomeScreen} />
        <Stack.Screen name={VIEWS.REGULATORS_DATA} component={RegulatorsDataScreen} />
      </Stack.Navigator>
    </NavigationContainer>
  );
}
```

Tell me please what else would be helpfull to reproduce my issue.

**Comment by JaioSkura** [comment]
> Couldn't find version numbers for the following packages in the issue:
> 
>     * `@react-navigation/bottom-tabs`
> 
>     * `@react-navigation/drawer`
> 
>     * `@react-navigation/material-bottom-tabs`
> 
>     * `@react-navigation/material-top-tabs`
> 
> 
> Can you update the issue to include version numbers for those packages? The version numbers must match the format 1.2.3.
> 
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
>     * `@react-navigation/native` (found: `5.9.4`, latest: `6.0.2`)
> 
>     * `@react-navigation/stack` (found: `5.14.5`, latest: `6.0.7`)
> 
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Yes, the issue still exist with versions:
```"@react-navigation/native": "^6.0.2",
    "@react-navigation/stack": "^6.0.7",
```
About the versions of the packages you mention, I didn't expecify any version because I am not using them. 

Thanks
