### ISSUE TITLE
the example does not work due to EISDIR: illegal operation on a director

### ISSUE THREAD

**Issue by Macilias** [react-navigation/react-navigation#9985]
### Current behavior

after cloning your current branch and performing the following steps:
$cd example && yarn && yarn ios

the app is build correctly but metro bundler fails with:
`Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:523:3)
    at tryReadSync (fs.js:348:20)
    at Object.readFileSync (fs.js:385:19)
    at UnableToResolveError.buildCodeFrameMessage (/Users/mac/Programming/environment/react-navigation/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:304:17)
    at new UnableToResolveError (/Users/mac/Programming/environment/react-navigation/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:290:35)
    at ModuleResolver.resolveDependency (/Users/mac/Programming/environment/react-navigation/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:168:15)
    at DependencyGraph.resolveDependency (/Users/mac/Programming/environment/react-navigation/node_modules/metro/src/node-haste/DependencyGraph.js:353:43)
    at /Users/mac/Programming/environment/react-navigation/node_modules/metro/src/lib/transformHelpers.js:271:42
    at Server.<anonymous> (/Users/mac/Programming/environment/react-navigation/node_modules/metro/src/Server.js:842:41)
    at Generator.next (<anonymous>)
`

the iOS simulator on the other hand reports that it can not connect to the development server.

### Expected behavior

the app example app should start in the simulator

### Reproduction

https://github.com/react-navigation/react-navigation

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [X] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by Macilias** [comment]
Hi, thanks for answering so quickly. There has been no changes I was just following you example here. Actually it must have been something related to the iOS pods along with cocoa pods or Xcode CLI tools, since I updated those and now its working fine. Sorry for bothering you.
